### ISSUE TITLE
Improve distribution of Chromium extension outside the Chrome/Edge stores

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1029]
There was some discussion of this in #666, but the need for a rethink has been raised by the switch from MV2 to MV3. Here are some issues:

* It is extremely difficult to download a CRX using Chrome or Edge browsers, because the browser sniffs the file type, tries to install it and fails:
  + If it's a signed nightly file, it refuses point-blank even to download the file, and just displays the CRX_REQUIRED_PROOF_MISSING error, which it is impossible to work around inside Chrome/Edge. The user would have to use a different browser (Firefox!) to download the CRX.
  + If it's a signed release version, i.e. one that has been signed by the Chrome or Edge Stores, then at least the user can download the file, although the browser still tries and fails to install it during download. It is then not obvious how to install it (the user has to drag and drop it into the extension management page, possibly with developer mode turned on, though this needs thorough testing).
+ For now, it is paradoxically much easier to install an unsigned extension from a ZIP than a signed CRX (turning on developer mode), hence this is what we recommend to users who still want to use the MV2 extension. This has the disadvantage that the user is asked every couple of weeks whether they want to turn off developer-mode extensions.
+ We should at least provide the nightly CRX files inside a ZIP, given that otherwise there is no way at all to download them from within Chrome/Edge/Chromium. 
* We need to provide better instructions to users, even though installing from outside the Stores is an edge case. It should be easier than this.
* See also #1026 for related extension signing woes in Firefox.

@kelson42 Any thoughts?

**Comment by kelson42** [comment]
@Jaifroid On Chrome, following https://download.kiwix.org/release/browsers/README instructions work fine for me. Not sure if we can achieve something simpler and not sure if this is worse on Edge. So this maybe a problem mostly impacting nightlies?

**Comment by Jaifroid** [comment]
@kelson42 The method described works for the signed CRX files we get from the Chrome/Edge stores after certification, although it's still difficult (or rather, misleading) trying to download that CRX from within Chrome/Edge (you get a failed install message, but the CRX still downloads).

However, the instructions don't work at all for CRX files that we sign ourselves, i.e. for the nightly CRX files we publish, for the simple reason that there is no way at all to download them in a Chromium browser. The browser deletes them in the process of downloading. At the least, these should be provided as ZIP archives, not as bare CRX files.

**Comment by Jaifroid** [comment]
Additional information:

Once a user does manage to download a **_nightly_** (signed) CRX, installing it by drag-and-drop without developer mode on does nothing. Installing it with developer mode turned on (via drag-and-drop) produces the message seen in the screenshots below. There is no way to enable it. Note that this is the experience on Windows. I believe it may be allowed on Linux, needs testing.

![image](https://github.com/kiwix/kiwix-js/assets/4304337/edc8380d-0065-41b5-a220-85818d6882d8)

![image](https://github.com/kiwix/kiwix-js/assets/4304337/63e301c9-85a5-49ec-ae3b-de193b26c918)

**Comment by Jaifroid** [comment]
And another interesting observation:

If I simply change the extension of the _nightly_ CRX from `.crx` to `.zip`, it can be installed (in Developer mode) with the drag-and-drop method. It is not clear if it is installed with any more privileges than installing the unsigned nightly ZIP we already publish.

This is clearly a side-effect, because the resulting ZIP is not in fact a valid ZIP and can't be opened with normal unzipping tools. It's probably not therefore a good way to serve the signed nightly CRX files, even if it would be an improvement on the current situation...

**Comment by Jaifroid** [comment]
OK, I've discovered that `.crx` files are in fact valid ZIP files, only they have a signature in their headers, which can confuse some unzipping software. On Linux, `unzip` can unzip a `.crx` archive that has been renamed to `.zip` without any problem. On Windows, 7Zip can expand these (though they need to be renamed to `.crx`).

So, my proposed solution to this issue is:

- [ ] Serve all signed nightly `.crx` files as `.zip` files (when we move them out of the tmp directory during build, we can simply change the file extension)
- [ ] Continue to serve Store-signed released `.crx` as `.crx`, as we currently do. These can be downloaded and installed relatively easily
- [ ] Update the documentation to explain the change

This has the advantage, at least, that the nightly signed versions can be downloaded within Chrome itself, and they can be installed in Developer mode. This is simply not possible if they remain as `.crx` files (as seen in screenshots above, they are blocked as suspicious, and cannot be enabled even if the user manages to install).
