### ISSUE TITLE
Enable end-to-end testing on a range of platforms using Browser Stack

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1041]
Since some basic e2e testing is now enabled with Selenium + Mocha for latest Firefox, Edge, Chrome and IE11 (via Edge's IE Mode) on GitHub actions (once #1038 is merged), it should be relatively easy to add some older Firefox and Chromium browsers, possibly also Safari, via Browser Stack.

**Comment by RG7279805** [comment]
@Jaifroid, I will take this issue. I have one question: How many previous versions of the browser should we include in our coverage?
UPDATE: I accidentally commented on other issue by mistake
