### ISSUE TITLE
ZIM backend : Improve performance of article search

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#107]
It's currently much slower than with an Evopedia archive

**Comment by mossroy** [comment]
This issue is really not crucial in my opinion.

**Comment by kelson42** [comment]
@mossroy @Jaifroid Should we close that one. I think we all agree that this is quite fast currently and that the real solution is Emscripten.

**Comment by mossroy** [comment]
It's not very fast IMHO but yes, the solution is Emscripten.

**Comment by Jaifroid** [comment]
The only place where binary search is really slow is on Android, for which I've opened #581 . Otherwise, in most other contexts this issue has been solved. So I'm closing for now.
