### ISSUE TITLE
Should next release be numbered 3.9.5 or 4.0 or wait for more features?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1077]
@kelson42, some advice please. We have a large number of merged PRs since last release, and it would in principle be good to do the next release of the Browser Extension. But we've hit a numbering issue, because we are currently on v3.9, but I'm not sure what we have qualifies us to go to v4.0 ("major release") yet.

We use the major.minor.patch release scheme here, and so we don't normally release a patch version unless it's an emergency bugfix. However, going to v4.0 seems like it should only be justified if we have something major to release. While having translated the UI into two globally important languages was a "major" piece of work, is it major enough in terms of users' normal experience (remembering that our current users already use the app in English) to warrant a "major" release? I always envisaged that v4.0 would include support for Zimit, but we're not there yet.

In favour of 3.9.5:

* All the PRs since last release except translating the UI have been development-focused (re-enabling Unit tests, updating e2e testing framework, developing and stabilizing those tests);
* We don't have a killer new feature to distinguish v3 from v4 yet, like Zimit support would be.

In favour of 4.0:

* It could be advertised as a "ten-year anniversary edition";
* Translation of UI makes the app accessible to a wider range of potential users in Africa and Latin America, so although not a major release for our current users, maybe it could be considered so given the potential to expand user-base.

I'd appreciate some help in deciding how to proceed!

**Comment by Jaifroid** [comment]
It's just occurred to me that we can solve this dilemma by releasing a v3.10 ... Obvious solution, I don't know why I thought after 3.9 must inevitably come 4.0...

**Comment by kelson42** [comment]
@Jaifroid Sorry for the late feedback. As long as the sementic versioning is respected, this is fine to me. To my own tate, I tend to be conservativ considering major release numbering, but this is only my personal preference.

**Comment by Jaifroid** [comment]
I agree, I think a major version should have some major differentiation.
