### ISSUE TITLE
Code cleanup for Tab transition animation

### ISSUE THREAD

**Issue by RG7279805** [kiwix/kiwix-js#1101]
While working on issue #846 Adding a new tab seems more complex than expected code seems really confusing and there is a lot of repetition for the same function
check out 
 https://github.com/kiwix/kiwix-js/blob/main/www/js/lib/uiUtil.js#L490

**Comment by Jaifroid** [comment]
Thanks! This is probably a duplicate of #78? Or at least, it might also close #78.

**Comment by Jaifroid** [comment]
Also see #701.

**Comment by Jaifroid** [comment]
Closing as duplicate. Please add any discussion in #78.

**Comment by Jaifroid** [comment]
Or add discussion to #701 if more appropriate.
