### ISSUE TITLE
Unable to execute 'npm ci' command

### ISSUE THREAD

**Issue by aaditya9899** [kiwix/kiwix-js#1119]
**Environment Information:**

Node.js version: v12.22.9
npm version: 9.8.1
Operating System: Windows 11 as well as Ubuntu 

**Issue Description:**
When running `npm ci ` to setup my development environment , it showing an error 

![error](https://github.com/kiwix/kiwix-js/assets/38832156/03604e95-9604-4899-abd9-2a34897638a2)

**Comment by Jaifroid** [comment]
@aaditya9899 Did you post this in the right place? The log you show appears to be for mwoffliner. We don't have libzim as a dependency installed via npm here in Kiwix JS.

Having said that, an alternative to `npm ci` is `npm install`. The former can only be used if you have a valid `package-lock.json` file in the root of the repository you are trying to install. You can build or overwrite `package-lock.json` with `npm install`.

**Comment by aaditya9899** [comment]
Yeah you are right its definitely not the right place to post it sorry for that , and yeah it got fixed now, thank you.
