### ISSUE TITLE
ZIM backend : enable full-text search

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#112]
That will need to be able to handle the index of ZIM files. This index uses Xapian file format, which does not seem to have a javascript implementation for now. Maybe with emscripten?

**Comment by Jaifroid** [comment]
@kelson42 I'm still interested in experimenting with the full text index in ZIM files, but there is a lack of information to go on. I understand from https://wiki.openzim.org/wiki/ZIM_file_format#Namespaces that the index is in namespace `X`, but that's all I've been able to find out. There is a broken link on that page to information about the full text index, with the address `ZIM_Index_Format` (see screenshot) -- I assume this hasn't been written yet, but on the offchance, is there a draft that might provide some hints about the format (other than that it's based on Xapian)?

![image](https://user-images.githubusercontent.com/4304337/62310993-ab0cc600-b482-11e9-81b4-18ceb480fabd.png)

**Comment by mossroy** [comment]
This might be superseded by #769 (use libzim for that), but there are still blockers like #513

**Comment by kelson42** [comment]
@Jaifroid The ft/suggestion indexes are not part of the openZIM spec. Our Actually, libzim as ref. implementation can be built withput any dependence to Xapian. But, if it is, then the whole conplexity of using Xapian or locating the indexes is abstracted by the libzim. Therefore, you should now about the libzim API only IMO. More info about the libzim API at https://libzim.readthedocs.io/en/latest/.

**Comment by kelson42** [comment]
Should we close this ticket as duplicate of #769?

**Comment by mossroy** [comment]
Yes, I think so : closing

**Comment by kelson42** [comment]
@Jaifroid Crazy... somehow this notification came in my inbox. Sorry for the slight delay in my answer ;)
