### ISSUE TITLE
Active content warning not detecting PhET ZIMs

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1157]
At least in Firefox, the user is just presented with a blank page if attempting to access a PhET ZIM in jQuery mode. This won't affect most users, as those with the ability to run a Service Worker should already be in SW mode, but for completeness, this regression should be fixed.

**Comment by Jaifroid** [comment]
Actually the check for active content is done in `app.js` only when the app is in Safe Mode (jQuery mode). You can find where it is done by looking for `activeContentWarning` in `app.js`. Basically, all I did for the active content warning was craft a regular expression that could detect the presence of certain scripts (and exclude some other scripts that shouldn't trigger an active content warning). It's a bit of a monster regex, but shouldn't be too hard to tweak so that PhET is detected again.

The first thing to do, though, would be to check that this ticket is still valid, by downloading a recent PhET ZIM, putting the app into Safe Mode, and seeing whether the warning is shown when attempting to load the ZIM. It's possible it was a temporary blip.

**Comment by Jaifroid** [comment]
Sounds like it's still broken then! Though you could download a very recent small PhET (some of them are very small) to corroborate.

**Comment by Greeshmanth1909** [comment]
I've checked a latest download, the issue persists.
