### ISSUE TITLE
Release v4.0.0

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1186]
With the new Zimit support, I think we have enough to justify a major version release in the New Year - 4.0. Although this has been released only to the browser-extension.kiwix.org (PWA) channel as a "sneak preview", I think we should capitalize on this and use it as a good reason for a v4.0.

These are the steps to complete a new release:

-  [x] Wait for some Issues / PRs to be completed (t.b.c.)
    - [x]  #1160 (@Rishabhg71)
    - [x] #1190 (@Greeshmanth1909, but waiting on my review)
    - [x] #1183 
    - [x] #1194
    - [x] If #1192 is completed in time, then we can quickly do #1197
    - [x] #1199 
    - [x] #1206
    - [x] #1209
    - [x] ~~Possibly #1031 (@kelson42)~~
-  [x] Create PR to update the changelog file
-  [x] Rename all higher milestones by incrementing their names, create a new 4.1 milestone and move open issues to this new one
-  [x] Draft the new release with desired tag
-  [x] Run Set-AppVersion script (or manually change in 6 files) the version number to v4.0.0, also run `npm install` to update `package-lock.json`, and commit
-  [x] Final tests (some can be done on https://kiwix.github.io/kiwix-js)
   +  [x] Firefox OS
   +  [x] IE11
   +  [x] Edge Legacy
   +  [x] Chromium Extension
   +  [x] Firefox Extension 
-  [x] Add release date to changelog and squash/merge PR
-  [x] Publish the new release (this will create the tag and start the release workflow)
-  [x] Check that dockerfile built correctly
-  [x] Generate unsigned extensions (should be automatically triggered on GitHub Actions by the tag creation)
-  [x] Check that the PWA version was correctly set in browser-extension.kiwix.org (should be automatically triggered by tag creation)
-  [x] Upload the unsigned extensions to Stores:
   +  [x] Firefox - https://addons.mozilla.org/fr/firefox/addon/kiwix-offline/
      +  [x] Check that the minimum Firefox version is correct
   +  [x] Chrome MV3 - https://chrome.google.com/webstore/devconsole
   +  [x] Edge MV3 - https://partner.microsoft.com/en-us/dashboard/microsoftedge/
   +  [x] Ubuntu touch - https://open-store.io
-  [x] Prepare the source code for version 4.0.1 (changes should be made to 9 files, or use the `Set-AppVersion` script to update 8 files, followed by `npm install` to update `package-lock.json`.)
-  [x] When available, copy the signed extension binaries to https://download.kiwix.org/release/browsers/
   +  [x] Firefox - [xpi downloadable from extension page](https://addons.mozilla.org/fr/developers/addon/kiwix-offline/versions)
   +  [x] Chrome - [crx downloadable from extension mgmt page](https://chrome.google.com/webstore/devconsole/)
   +  [x] Edge - [check version is published](https://microsoftedge.microsoft.com/addons/detail/kiwix/jlepddlenlljlnnhjinfaciabanbnjbp), then use [direct link for Edge-specific crx](https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3Djlepddlenlljlnnhjinfaciabanbnjbp%26installsource%3Dondemand%26uc)
-  [x] Check that the implementation on kiwix.github.io/kiwix-js/ is synchronized automatically with main
-  [x] Publicize these new versions
-  [x] Close this issue and close the v4.0 milestone

**Comment by Jaifroid** [comment]
@kelson42 We now have unsigned extension versions for release 4.0.0! I've validated that this is uploadable to the Edge Extension store, so it should also work for the Chrome Extension store. This is the package you need:

https://download.kiwix.org/nightly/2024-02-22/kiwix-chrome-unsigned-extension-mv3-4.0.0.zip

Could you kindly upload it? I'll take care of the remaining packages (Firefox and Ubuntu). The changelog is here: https://github.com/kiwix/kiwix-js/blob/main/CHANGELOG.md .

**Comment by kelson42** [comment]
@Jaifroid I missed your message, will do that ASAP

**Comment by Jaifroid** [comment]
@kelson42 Thank you, I see it's all done!

Just waiting for MS to certify the Edge extension now.... (submitted last week!).

**Comment by Jaifroid** [comment]
All updated now.
