### ISSUE TITLE
Rename "JQuery mode" to "safe mode"?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1197]
Following on from a description suggested by @Greeshmanth1909 in #1192, I wonder if it might be a good idea to rename "JQuery mode" to "safe mode".

Arguments in favour:

* "JQuery mode" is a misnomer. It doesn't require JQuery, and in reality it is a mode that injects resources into the DOM using DOM manipulation instead of a Service Worker
* It would align with the proposal in #1192 to warn the user to consider whether they trust the source of a ZIM when opening an archive for the first time
* JQuery mode would effectively be aligned with `noscript` extensions, etc., which prevent JS form running
* It is indeed a mode that is secure against any JS-based attack, because it simply ignores JS from the ZIM
* We know that many largely static archives work passably in this mode, even several Zimit 1.0 archives scraped from older, static web sites
* Some OSs have a "safe mode" which prevent many features from running, but allows users to run basic diagnostic code; this could be seen as similar for peeking at the contents of an untrusted archive before allowing it to run

Arguments against:

* The name "safe mode" might lure users into thinking it is somehow superior, when in fact it is a mode in which many modern ZIMs are pretty much broken (the UI of Gutenberg, PhET, many dynamic Zimit-based archives) -- anything that relies on dynamic content
* Some time ago we marked "JQuery mode" as deprecated. Giving it a new lease of life as a safe mode will require maintaining it to some extent (though in reality it has been maintained since deprecated)

**Comment by kelson42** [comment]
The overall idea looks good, even if I would just remove the whole jquery mode and recommend to do so ASAP.

**Comment by Jaifroid** [comment]
Thanks for your thoughts @kelson42. It would be quite a big step, as there are still users of the app(s) who are only interested in Wikipedia, Wiktionary, etc. and who have systems or contexts that don't support Service Workers. However, I do understand the large technical debt that has built up, and that at some point we have to take some hard decisions...

**Comment by Jaifroid** [comment]
In Spanish, "modo seguro" is straightforward. In French, I think "mode sécurisé" rather than "mode sans échec", because we want to emphasize security. And in fact it is security at the expense of functionality, so it's not "sans échec".

**Comment by Greeshmanth1909** [comment]
I'd like to work on this if we choose to proceed with changing `jQuery` to `Safe` mode.

**Comment by Jaifroid** [comment]
You're welcome to work on this. However, don't change any variable names or comments in code. This would just be a UI change (but that would include any dialogue-box text or tooltips, basically, anything an end user sees). You should leave code like `params.conetnInjectionMode === 'jquery'` as is. That would be a much bigger task to change, and would involve a lot of testing of edge cases!

In the translation files, use these forms:

Spanish: 'modo jQuery' = 'modo seguro'
French: 'mode jQuery' = 'mode sécurisé'

Try to respect capitalization in the languages. E.g. if in French we have 'Mode JQuery', then change to 'Mode Sécurisé'. But where it's lowercase 'mode jQuery', keep as 'mode sécurisé'.
