### ISSUE TITLE
Add ZIM info to the security dialogue box when opening a ZIM for the first time

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1247]
See Kiwix PWA for existing implementation. I propose simply providing the same info as in screenshot:

![image](https://github.com/kiwix/kiwix-js/assets/4304337/f009a48d-7196-470c-896d-7610003da5b7)

**Comment by D3V-D** [comment]
I'd also be interested in helping in this issue if help is needed.

**Comment by Jaifroid** [comment]
> I'd also be interested in helping in this issue if help is needed. @Jaifroid

Happy for you to do it -- it should be pretty easy to use the PWA template/code for this. The only complication is adding the translation strings. Also, instead of "can easily be spoofed" I think it would be more accurate to say "can be spoofed" (and I'll probably change that in the PWA when I've finished another PR I'm working on).

**Comment by Jaifroid** [comment]
Oh, and you'll need to make sure all the required metadata are available when the ZIM first opens, which may require a small change to `zimArchive.js`.

**Comment by D3V-D** [comment]
Yeah, once I take a look at it ill let you know what I think. I have yet to work with "translation strings" - is that the alternate language versions of the text i assume?

**Comment by Jaifroid** [comment]
@D3V-D Yes, I've implemented French and Spanish (as well as English) in Kiwix JS (but not in the PWA). It's sort of obvious how it's done when you look at it -- there are lots of examples of invoking a dialogue box like that with the language string keys, and then the translation backend takes care of displaying the appropriate language. You can use https://www.deepl.com/translator to get the French and Spanish versions (but that comes at the end, after code is working). I can check French and Spanish, as I know these languages.

**Comment by D3V-D** [comment]
Sorry I haven't had time to take a good look at the issue. I have exams for the next week or two, but after that I'll be able to do some work on this issue.

Just a heads-up.
