### ISSUE TITLE
Create new function in uiUtil.js to navigate to the opened ZIM in order to reduce redundancy

### ISSUE THREAD

**Issue by D3V-D** [kiwix/kiwix-js#1248]
See title.

Already made a function in app.js, and it's being used in at least one other place within the uiUtil.js file as well.

**Comment by D3V-D** [comment]
@Jaifroid let me know if any special details; otherwise please assign me

**Comment by Jaifroid** [comment]
No special details! Thanks for opening the issue.

**Comment by D3V-D** [comment]
@Jaifroid do you want to close this issue?

**Comment by Jaifroid** [comment]
Yes, not sure why it didn't auto-close!

**Comment by D3V-D** [comment]
I believe the issue was not linked to the PR. @Jaifroid
