### ISSUE TITLE
Users seem confused when the Chrome extension won't do some stuff in ServiceWorkerLocal mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1257]
Not really sure what we can do about this, as we clearly post a warning message at the top of the landing page "Unable to display active content..." and tell them what to do about it (see screenshot). But two experienced users have recently ignored this and have reported video isn't working. It can't work, because Chrome browser extensions prohibit any inline JS as well as eval and other stuff. Also, when first installing the extension, it asks for permission to fetch the browser-extension.kiwix.org PWA, which solves the issue (and works offline thereafter). Same issue in Firefox, only worse, because Service Workers are prohibited in local Firefox extensions, so to do anything reasonable at all, users must agree to fetch the browser-extension PWA.

Is there anything more we could do? Maybe make that warning into a modal that users must actively acknowledge (could be annoying...)? @kelson42, any UX advice here?

![image](https://github.com/kiwix/kiwix-js/assets/4304337/b47064df-b482-4eae-90e3-774748e4da5e)

**Comment by audiodude** [comment]
In particularly it's not clear what "active content" is, or what the difference between the "ServiceWorkerLocal" and "ServiceWorker" modes are and why I would want to switch. Even "content may be available by clicking search button above (or type a letter of the alphabet)" seems both vague and oddly specific. It should probably read "Some content may still be available via searching, above" or something.

**Comment by Jaifroid** [comment]
@audiodude Thanks for the feedback. I suppose it's one of those cases of "developer-speak". The wording "active content" and what is called in the code "activeContentWarning" has been used ever since Service Workers were introduced in the app and we had to warn users that things would be broken if they didn't start using it. There are a few versions of this warning.

I agree it needs simplification. I propose something like:

> **Warning: you must [switch to ServiceWorker mode](#something) to view all content in this ZIM**.  Some content may still be available by searching above (tap the search icon, or type a letter of the alphabet in the search field).

The instruction on how to search is a workaround for those people who don't have a browser that supports Service Workers, but still want to access content in ZIMs like Gutenberg. The link [switch to ServiceWorker mode](#something) takes them straight to the setting they need to change.

FYI The problem here is a technical one: as mentioned, Firefox doesn't support Service Workers in browser extensions (not considered a secure context like `https:`), and while Chrome does support Service Workers in extensions, it blocks a lot of JS, so many things break in modern ZIMs.

The solution we came up with for this problem is to fetch an external offline-first PWA (which is secure) and cache it. We try very hard to steer users who have modern browsers to this solution from the first time they install the extension, but some users don't want to or don't trust it, or are running older browsers... Hence we try to make as much as possible still work for them.

**Comment by audiodude** [comment]
Yes, developer speak is definitely the problem.

I like you're rewording, but telling the user to "type a letter of the alphabet" seems very patronizing.

Can we just have something like "...searching above, or [clicking here](#) to view the index..."?

I assume that's what an empty search does?

**Comment by Jaifroid** [comment]
We don't have a dedicated ZIM Index view in this app, just a search function. You can approximate a list by tapping/clicking the search icon without typing anything. For more granular search in a larger ZIM, you might need to go through the alphabet. But I agree it risks sounding patronizing, and maybe we can just trust users to work this out for themselves... So:

> **Warning: you must [switch to ServiceWorker mode](#something) to view all content in this ZIM.** Some content may still be available by searching above (or tap the search icon for a list).

FYI, clicking the search icon just displays the first 30 (or more -- it's a setting in Config) directory entries. In a TED Talks ZIM, which will usually contain fewer than 30 videos, clicking the search icon will be very useful, because it will give a full list of the contents, but this isn't obvious to users, hence the hint to "tap the search icon for a list". A Gutenberg ZIM, on the other hand, will usually contain hundreds of entries, so to see any meaningful list, users would have to use a more granular search. For Gutenberg, TED talks and other YouTube-based ZIMs, users can still retrieve the books or play the videos when not in ServiceWorker mode, but the JS-based UI that gives a graphical view of what's in the ZIM mostly doesn't work...

**Comment by audiodude** [comment]
Yes I like that wording. Thanks for the explanation!

**Comment by kelson42** [comment]
A simple sentence telling "limited support..." should be enough. No strong opinions about how it should be displayed.

**Comment by Jaifroid** [comment]
Thanks, both. I'll make a PR (in due course, certainly before next release) with suggested wording. There are a couple of different versions of this warning for different app configurations / scenarios, so it will tackle the other too along the same lines.
