### ISSUE TITLE
When displaying external link dialogue box from zimit2 archives, we need to decode the over-encoded querystring

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1258]
See https://github.com/openzim/warc2zim/issues/276#issuecomment-2142177838 for more info. It's not really a regression in KJS code, but is due to a recent decision to encode all querystrings in Zimit 2 ZIM anchors. Fix will need to be ported to PWA as well.

**Comment by Jaifroid** [comment]
Any fix for this should wait on what is decided in https://github.com/openzim/warc2zim/issues/276.

**Comment by Jaifroid** [comment]
No solution offered in https://github.com/openzim/warc2zim/issues/276, so I think we just go ahead and decode the overencoded querystring of external resources, otherwise they simply won't work when a user opens them in a browser.

Overencoding the querystring in zimit2 ZIMs was a kludge introduced upstream solely because some backend code in libzim strips querystrings before sending them to the server or backend. It's a shame we have to work around that workaround, but so be it. It wasn't possible to change all the other apps without major disruption.

**Comment by benoit74** [comment]
Do you mean that since https://github.com/openzim/warc2zim/issues/276 will take time to be solved, you intend to add a "workaround" in KiwixJS which decodes the over-encoded querystring when a link is found to be external / absent from the ZIM?

I don't mind about it, but you could as well consider this is a known scraper bug / limitation and people will have to live with it until scraper issue is solved. At least I'm sure this is what most other readers will do unless we consider that fixing https://github.com/openzim/warc2zim/issues/276 is too complex and it is way simpler to tackle this at runtime when you know which URL is fetched and whether this is present in the ZIM or not.

**Comment by Jaifroid** [comment]
@benoit74 Yes, I mean a temporary workaround which would only be applied in the custom code we have already implemented that detects whether a ZIM link is an external resource or not, so it can be opened outside the sandbox. This is our version of the custom reader-side code introduced into libkiwix here https://github.com/kiwix/libkiwix/pull/1036, although the latter doesn't (yet) deal with querystrings on external resource URLs in Zimit2.

Having said that, it's not as easy as it seems to detect an overencoded querystring versus the appearance of a legitimately encoded `?` (`%3F`) inside the main URL. Encoding the querystring and its separators leads to information loss, so we can only guess an approximate reversal that should work in, say, 95% of cases.

@audiodude Do you have a view on whether this workaround should be slated for v4.1.0?

**Comment by Jaifroid** [comment]
This is actually a very small workaround as can be seen in https://github.com/kiwix/kiwix-js/pull/1267/files . It's not perfect because there is a risk of overdecoding the URL itself. But as it's just a workaround, and as it should fix more cases than it breaks, I think it's an improvement. It's not worth developing more elaborate logic, unless this interferes with PDFs, which I need to test thoroughly.

This fixes the case with Twitter and Facebook share links in mesquartierschinois reported in https://github.com/openzim/warc2zim/issues/276 .

**Comment by audiodude** [comment]
> @audiodude Do you have a view on whether this workaround should be slated for v4.1.0?

I don't really have an opinion either way, no.
