### ISSUE TITLE
Release v4.1.0

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#1263]
We're overdue a new release of the Browser Extension, as we have a major new feature (the Popover feature), plus some key elements of Zimit2 support and a number of bugfixes. It's been some six months since the last release, and we normally release this app quarterly...

These are the steps to complete a new release:

-  [x] Fix some important but relatively simple issues if possible
    - [x] #1118  
    - [x] #1255
    - [x] #1254
    - [x] #1257
    - [x] #1258 
    - [x] #1259 
    - [x] #1260
-  [x] Create PR to update the changelog file
-  [x] Rename all higher milestones by incrementing their names, create a new 4.1 milestone and move open issues to this new one
-  [x] Draft the new release with desired tag
-  [x] Run Set-AppVersion script (or manually change in 8 files) the version number to v4.1.0, also run `npm install` to update `package-lock.json`, and commit
-  [x] Final tests (some can be done on https://kiwix.github.io/kiwix-js)
   +  [x] Firefox OS
   +  [x] IE11
   +  [x] Edge Legacy
   +  [x] Chromium Extension
   +  [x] Firefox Extension 
   +  [x] Safari on macOS 
   +  [x] Safari on iOS 
-  [x] Add release date to changelog and squash/merge PR
-  [x] Publish the new release (this will create the tag and start the release workflow)
-  [x] Check that dockerfile built correctly
-  [x] Generate unsigned extensions (should be automatically triggered on GitHub Actions by the tag creation)
-  [x] Check that the PWA version was correctly set in browser-extension.kiwix.org (should be automatically triggered by tag creation)
-  [x] Upload the unsigned extensions to Stores:
   +  [x] Firefox - https://addons.mozilla.org/fr/firefox/addon/kiwix-offline/
      +  [x] Check that the minimum Firefox version is correct
   +  [x] Chrome MV3 - https://chrome.google.com/webstore/devconsole
   +  [x] Edge MV3 - https://partner.microsoft.com/en-us/dashboard/microsoftedge/
   +  [x] Ubuntu touch - https://open-store.io
-  [x] Prepare the source code for version 4.1.1 (changes should be made to 9 files, or use the `Set-AppVersion` script to update 8 files, followed by `npm install` to update `package-lock.json`.)
-  [x] When available, copy the signed extension binaries to https://download.kiwix.org/release/browsers/
   +  [x] Firefox - [xpi downloadable from extension page](https://addons.mozilla.org/fr/developers/addon/kiwix-offline/versions)
   +  [x] Chrome - [crx downloadable from extension mgmt page](https://chrome.google.com/webstore/devconsole/)
   +  [x] Edge - [check version is published](https://microsoftedge.microsoft.com/addons/detail/kiwix/jlepddlenlljlnnhjinfaciabanbnjbp), then use [direct link for Edge-specific crx](https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3Djlepddlenlljlnnhjinfaciabanbnjbp%26installsource%3Dondemand%26uc)
-  [x] Check that the implementation on kiwix.github.io/kiwix-js/ is synchronized automatically with main
-  [x] Publicize these new versions
-  [x] Close this issue and close the v4.1 milestone

**Comment by Jaifroid** [comment]
While testing on Firefox OS, I found that this old OS doesn't support `innerText` in some contexts, so I need to test for that and substitute `textContent` in two places in the popover code. As this is a trivial change to get the code working on Firefox OS (`textContent` is *nearly* the same as `innerText`, certainly for our purposes), I'll go ahead and do that so I can continue testing.

**Comment by Jaifroid** [comment]
And while testing fallback extensions (Manifest V2 for Firefox and Chromium, Manifest V3 for Firefox, I realized that I forgot to internationalize these manifests in line with the changes made to the Chromium Manifest V3. Again, this is a trivial change just copying the new fields to these manifests.

**Comment by Jaifroid** [comment]
@audiodude I've finished testing as indicated in the checked boxes above (or as we say in British English: the "ticked boxes" 😉). Apart from Chrome / Firefox / Edge extensions on Windows, plus some old browsers, I tested the offline webapp version in Safari 17 on an iPad Pro 2021, and Safari 14.1 on Big Sur (macOS) via BrowserStack.

I didn't attempt to test the packaged extensions themselves in macOS Chrome or Firefox via BrowserStack because it's not possible to test extensions that are not in one of the Stores in BrowserStack, given that access to files is severely locked down in macOS on BrowserStack. Please note we do not publish an extension for Safari, but the offline webapp version can still be used with full features in Safari. Users can install the extension in Chrome or Firefox on macOS.

My testing is pretty comprehensive, but do you want to do any further testing? If so, I can explain an easy way to test the code using the development webapp, or a more involved way of installing a temporary extension (which is a bit fiddly).

If you don't need to test further on macOS, then I'm pretty ready to start the release process once you're happy with the CHANGELOG PR.

**Comment by audiodude** [comment]
> If you don't need to test further on macOS, then I'm pretty ready to start the release process once you're happy with the CHANGELOG PR.

I'll trust your judgement and do additional testing if you think it is required. I have a macOS 10.15 Catalina system with an M3.

**Comment by Jaifroid** [comment]
Thanks @audiodude I have tested now in Firefox 126 and Chrome 125 on Catalina, and in Safari on the latest Sonoma (both via BrowserStack). So I think we're covered. There is no native code running in Kiwix JS, only JavaScript, so running on any chip that supports a full copy of Firefox or Chrome (or indeed a recent Safari) works fine.

FYI, on iOS, the app only works as a webapp in Safari, because for now Apple blocks the use of Service Workers in any browser other than Safari (on iOS, not on macOS). But users would be better off using the dedicate iOS app on iOS rather than running this Extension as a webapp, so while I test on iOS to be sure that we maintain compatibility, I'm not targeting it here, or optimizing UX for it.

**Comment by Jaifroid** [comment]
The Firefox extension update is already published: https://addons.mozilla.org/en-US/firefox/addon/kiwix-offline/ (also in Spanish and French). Edge is in review with newly translated information and graphics now that the internationalization of Chromium store entries is enabled in the packages. I'll upload Ubuntu touch and Chrome tomorrow.

**Comment by audiodude** [comment]
Let me know when it's time for :champagne: and :tada: , I'm ready!

**Comment by Jaifroid** [comment]
As the two most important browser stores (Mozilla and Chrome) have certified the extension, and people will be receiving updates, I've made some publicity for this release: see [Reddit post](https://www.reddit.com/r/Kiwix/comments/1e5b1e5/release_kiwix_js_browser_extension_v410_unleash/) and [Mastodon post](https://mastodon.social/@kiwix/112800469045844321).

Even though the Edge Store is ridiculously slow to certify (they say 5 working days, and it usually does take that), people will already be seeing the update if they use the default ServiceWorker mode (the vast majority), because the extension runs as an instantly updating offline PWA in that mode due to previously mentioned severe restrictions in local Chromium browser extensions.

**Comment by Jaifroid** [comment]
Edge Store finally certified, and all publicity done, so we can close.
