### ISSUE TITLE
Spelled mistakes in About The App section

### ISSUE THREAD

**Issue by Cibiyanna26** [kiwix/kiwix-js#1277]
Section *About this App* describe about the app and the word encyclopedia was misspelled. Even though this was a minor issue, I would to make changes in the misspelled word.

![image](https://github.com/user-attachments/assets/c4b49229-f942-4adf-8b65-0c59211c8fe6)

**Comment by Jaifroid** [comment]
That's not a misspelling. It's the correct original spelling of the word, still used in the UK and Australia, not the simplified US spelling!
