### ISSUE TITLE
Can't Download File into Local Device : not enough storage available Error!!

### ISSUE THREAD

**Issue by nahcol10** [kiwix/kiwix-js#1280]
When I an trying to download the file it shows this error:  ![Image](https://github.com/user-attachments/assets/9c033798-052e-4e74-b658-4134873d05f1)

**Comment by Jaifroid** [comment]
Hello, you appear to be using Kiwix Desktop. This Repo is for Kiwix JS the browser extension! You should post at https://github.com/kiwix/kiwix-desktop ,

**Comment by nahcol10** [comment]
ok man. Thank you!!
