### ISSUE TITLE
[Improvement] Home page | In tablet and mobile devices, the 'Select random' icon should have the same size as the search input and

### ISSUE THREAD

**Issue by CREDO23** [kiwix/kiwix-js#1288]
Desktop view ✅ 

![Image](https://github.com/user-attachments/assets/29fcce70-8f00-4d10-a828-3023acf8d9be)

Tablet, mobile (need improvement)

![Image](https://github.com/user-attachments/assets/c6ae7b68-587c-42a4-b914-0321ea3e6982)

**Comment by Jaifroid** [comment]
Thanks for the report. I suppose the CSS that resizes the UI is not being applied uniformly at some screen widths.

**Comment by FizanMuhammedFaisal** [comment]
can I work on this

**Comment by asmit27rai** [comment]
@Jaifroid I Want To Work On This Issue ?

**Comment by Jaifroid** [comment]
> [@Jaifroid](https://github.com/Jaifroid) I Want To Work On This Issue ?

There's already a PR fixing this.
