### ISSUE TITLE
Ability to read and handle the different MIME-types included in the ZIM file

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#137]
For now, the MIME types are often hard-coded, despite the fact that they are available in the ZIM file with each content.
We should be able to retrieve this information and use it

**Comment by kelson42** [comment]
This ticket might start to be critical if https://github.com/openzim/mwoffliner/issues/278 is implement, which probably will happen in the next 2/3 quarters.

**Comment by mossroy** [comment]
I agree that it's something that needs to be done in the mid-term.
But, to be precise : with the current implementation, removing the .html extension in URLs should not hurt kiwix-js. We're using the suffix to guess the MIME-type of images, CSS, javascript etc, but not for the article HTML content. Currently, it's the use of namespace "A" that tells us it's an article.
So https://github.com/openzim/libzim/issues/15 should be a bigger problem than https://github.com/openzim/mwoffliner/issues/278.

All these guesses were a quick-and-dirty way to move on, when developing kiwix-js. The right way to do it is to read and use the MIME-types from the ZIM file.
So far, nobody took the time to implement that. I think it's because we never faced any bug on that (so far), and because it's low-level file reading that not many people like to work on.

As the ZIM file format changes and improves, it will be more a more difficult to maintain the ZIM backend in pure javascript. That's why I think we need to work on #116 first.

**Comment by Jaifroid** [comment]
@mossroy Looking at the spec, I don't think it's difficult to add a function to `zimArchive.js` to get the MIME type table, and it would be a more robust solution for some code I have that is currently having to "guess" the type from the namespace.

I envisage that we would want to store the MIME Type List in the selectedArchive (prototype) to avoid a large number of binary lookups at the head of the ZIM file (where the Mime Type List is stored) for every article loaded.

Could you let me know if the following be a good way to do this?

1. Create a prototype `mimeTypeList` (array or map) in `zimArchive.js` and populate it once on archive load (or, alternatively, the first time that a MIME type lookup is requested); and
2. Create a prototpye lookup function in `zimArchive.js` that returns a MIME type string looked up from the `mimeTypeList` (using `dirEntry.mimeType` value).

**Comment by Jaifroid** [comment]
And we'll need code in `zimfile.js` equivalent to `ZIMFile.prototype.dirEntryByUrlIndex` that reads the zero-terminated values stored at the position indicated in `zf.mimeListPos` (this value is already defined in `zimfile`.

**Comment by Jaifroid** [comment]
I put some working code (with an issue that needs resolving) in #490 .
