### ISSUE TITLE
Links do not work on StackExchange archives

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#205]
It seems to be because the articles are not all at the same directory level

**Comment by kelson42** [comment]
Yes, I confirm that bug. If articles have "/" in their URL then it fails. Try for example with that file http://tmp.kiwix.org/prog.zim

**Comment by kelson42** [comment]
This problem basically impacts all StackExchange ZIM files http://download.kiwix.org/zim/stack_exchange/

**Comment by dattaz** [comment]
If i remember what we say in hackathon, you should inject an "base" tag  (https://developer.mozilla.org/fr/docs/Web/HTML/Element/base) when you have a redirect.

**Comment by Jaifroid** [comment]
@mossroy The two edits in commit https://github.com/kiwix/kiwix-js/commit/76055a921372047560d885530a325d1a19495936 on the [Support-for-Stackexchange-links](https://github.com/kiwix/kiwix-js/tree/Support-for-Stackexchange-links) branch seem to do the trick. Question links, tags, and user profile links all seem to be working.

I tested with the FFOS Simulator (thanks for your help re-enabling it) using `mathoverflow.net_en_all_2017-10.zim` . I've also tested this code with `wikipedia_fr_tunisie_2017-12.zim
` to be sure we haven't introduced a problem with non-Stackexchange ZIMs, and so far haven't found anything that's not working.

Would you like to test that branch before I do a PR from it? It would be good also to test with other Stackexchange ZIMs, as the mathsoverflow one may have its own peculiarities or be a special case.

![image](https://user-images.githubusercontent.com/4304337/33946128-da8890e8-e018-11e7-9453-c879189121d1.png)

**Comment by mossroy** [comment]
Great : I'll try to test that tomorrow. But you can create the PR if you like

**Comment by Jaifroid** [comment]
OK, PR https://github.com/kiwix/kiwix-js/pull/309 created from that branch.

**Comment by Jaifroid** [comment]
I've added commit https://github.com/kiwix/kiwix-js/pull/309/commits/0253fb3b7f0a2864badf083b4916f418bbf7aee7 to the PR to support "Duplicate" and "Related" question types. See comment in code.
