### ISSUE TITLE
Different Article Counts when opening the same ZIM in Kiwix and Kiwix-html5

### ISSUE THREAD

**Issue by sharun-s** [kiwix/kiwix-js#229]
wikiquote_en_all_nopic_2017-03.zim - 29195 on kiwix, 53511 on kiwix-html5
wiktionary_en_simple_all_nopic_2017-01.zim - 25092 on kiwix, 254444 on kiwix-html5

kiwix-html5 doesn't really show the counts to the user. I noticed it while inspecting the zimarchive object in the chrome debugger.

**Comment by kelson42** [comment]
Here is the approach in the kiwix-lib https://github.com/kiwix/kiwix-lib/blob/master/src/reader.cpp#L122

**Comment by sharun-s** [comment]
hmm...looks like two different approaches. kiwix-lib is picking it out of some article "M/Counter" while kiwix-html5 is picking it out of the header 24-27 byte of the ZIM

**Comment by kelson42** [comment]
Yes, like describe here http://www.openzim.org/wiki/ZIM_file_format#Header this includes all the entries (image included), that's why we have an other solution which allows to differentiate a bit the content (based on mime-type).

**Comment by sharun-s** [comment]
Ah I see. So I guess a switch to the kiwix-lib implementation is required.
I see the (header based) article count number being used in search, get random article etc in kiwix-html5. Probably causing other issues too.

**Comment by mossroy** [comment]
I don't think this is a bug.
This article count is not displayed. It is used in technical algorithms to find articles, where I think it is necessary because different MIME types are mixed in the indexes of ZIM files.

But you're right in the sense that, if we want to display this count, we should use the same approach as in kiwix-lib.

**Comment by sharun-s** [comment]
In the wikiquote zim the header based count is 53K while the M\Counter based count is 29K. 
Binary search is using this as the end index, so it's probably producing a couple extra iterations per search. No big deal if the end index jumps from 29K to 53K. 
I expected there to be a bigger difference in the en wikipedia zim, but to my surprise the counts are the same. I was expecting with all the images and stuff the difference would be huge. So what is going on there guys?

Side Note: 
This was an accidental discovery while debugging, so just making a note here may or maynot be useful elsewhere. Direct access to a byte range in the zim file is possible using the "HTTP Range" request header. I have a Chrome shortcut that starts chrome with the "--allow-file-access-from-files" argument

So this is how I pull header data out
var req = new XMLHttpRequest(); 
req.open('GET', "wikiquote_en_all_nopic_2017-03.zim", false); 
req.overrideMimeType('text\/plain; charset=x-user-defined');
req.setRequestHeader('Range', 'bytes=0-88');
req.send(null);
req.response contains the data header as a string.
articleCount = getData(24,4);

function leftShift(int, bits) {return int * Math.pow(2, bits);} 
function getData(rr, offset, size){r=0;for(i=0;i<size;i++){r = r+ leftShift( (rr.charCodeAt(offset+i) + 256) & 0xff, 8*i)}return r;}

**Comment by kelson42** [comment]
@mossroy @Jaifroid Seeing #724, I wonder if this ticket is still valid?

**Comment by Jaifroid** [comment]
I think there was probably a misunderstanding here about what the article counts are used for. The one in M/Counter probably shows the number of unique articles, excluding redirects (I'm guessing here). In a v0 ZIM, the entryCount in the file header will show all the entries, including images, etc., that are in the title pointer list. In a v1 ZIM (forthcoming), we have a different, article-only pointer list as well, which contains only articles, no images, and that one is labelled articleCount. Kiwix JS now calculates articleCount for a v0 ZIM as well, hence cutting out those extra hops that sharun-s referred to.

In any case, we never use (and cannot technically use) an article count that would exclude redirects, aliases, etc., so this issue can be safely closed. You're right that in a way #724 resolved this issue indirectly, I think.
