### ISSUE TITLE
Firefox 54 needs a local webserver for unit tests to run

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#257]
It was working fine on Firefox 53.
It looks like Mozilla added the same restrictions that exist in Chrome?
I'm not 100% sure.
Anyway, on my computer, the same unit tests work when served through a local webserver (on http://localhost), but fail if I simply open the file (file:///)

**Comment by mossroy** [comment]
If it's confirmed, it will certainly be an issue on Sauce, making the unit tests fail.
For now, Sauce still uses Firefox 53

**Comment by mossroy** [comment]
I tested again on another machine (under Windows) : 
Firefox 53.0.3 : all unit tests OK
After an upgrade to Firefox 54.0 : all unit tests of category "zim_direntry_search_and_read" are failing
I did not see anything related in the official changelog of version 54

**Comment by mossroy** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1374395 for that issue

**Comment by mossroy** [comment]
Second look, it should not be an issue for Travis/Sauce, as it runs the unit tests and UI tests through a local webserver

**Comment by mossroy** [comment]
They concluded on Bugzilla that it's a Firefox bug that should be fixed in Firefox 55.
For Firefox 54, a workaround is to set browser.tabs.remote.separateFileUriProcess to true in about:config, or to disable e10s

**Comment by sharun-s** [comment]
Good catch!
