### ISSUE TITLE
Rebrand the app as "Kiwix JS"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#262]
Result of https://github.com/kiwix/kiwix-html5/issues/248 discussion.

**Comment by Jaifroid** [comment]
I did a quick grep on the repo and came up with the candidate files in PR #263 . Please check these are all needed, as some are in project files.

**Comment by Jaifroid** [comment]
PS it looks like at least one of the changes might need corresponding filename changes in the repo.
