### ISSUE TITLE
Provide an optional dark theme both for interface and Wiki articles

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#265]
@Jaifroid wrote:

> Windows Mobile users tend to prefer dark themes, white text on black or dark background. This should be a simple matter of providing some CSS classes and an option to apply them in the interface.

@mossroy replied:

> I think it's an option that might be generic for all devices/platforms.
> Such option exists in the Android Kiwix app, it's called "night mode".
> For the UI, it is indeed simply switching CSS classes, but it might be more complicated for the article content itself. Because the CSS comes from the ZIM file.

**Comment by Jaifroid** [comment]
There is initial support for a dark theme in commit https://github.com/kiwix/kiwix-js/commit/137b81e2f0631c602996ff5a722339a49a7e9e5f. Some pages are inverting black-and-white images and making the image hard to see (e.g. molecular diagrams for medicines), but on the whole this is working quite well. The css is from https://github.com/StylishThemes/Wikipedia-Dark and is on a CC-BY-SA licence (see https://userstyles.org/styles/105844/wikipedia-dark-st ).

![image](https://user-images.githubusercontent.com/4304337/28788760-2af0e576-761a-11e7-851c-6b15c6fa8d80.png)

![image](https://user-images.githubusercontent.com/4304337/28788895-a99eab92-761a-11e7-8723-1bf66b90a9ff.png)

**Comment by b16r05** [comment]
Excellent! Just wanted to point out that I have been using stylish "Wikipedia Minimalistic Dark Material Design" for a while and it is really good and "material" ; ) link: https://userstyles.org/styles/122072/wikipedia-minimalistic-dark-material-design with source code available at Github: https://github.com/n0x-styles/wikipedia-dark, in case you need to test an alternative!

**Comment by Jaifroid** [comment]
Thanks @b16r05 . I think I went for the other one from that site because of explicit support for equations and because at the time it was the most up-to-date. However it's easy to change the dark theme code -- just drop in the file, really. I've found I've needed to tweak the source css to support different Wikipedia ZIM archives in other languages.

**Comment by Jaifroid** [comment]
@b16r05 One year on! This is the current state of the dark theme, including UI, in Kiwix JS Windows. It's not hard to backport this or something similar upstream to Kiwix JS. Regarding Wikiwand, we wouldn't use anyone else's UI unless it were completely Open Source and freely licensed for re-use and adaptation.

![image](https://user-images.githubusercontent.com/4304337/50854653-8386cc80-137d-11e9-8d40-ffe7b0284ae5.png)

**Comment by Jaifroid** [comment]
And... one year further on (!), we have PR #582 for this issue. It is currently implemented using inversion filters. However, specific themes for Web sites such as https://github.com/StylishThemes/Wikipedia-Dark could be used.

**Comment by deadlydud** [comment]
I just went to the https://www.kiwix.org/en/ and downloaded the linux kiwix reader, however my OS is setup for Dark theme, and when I open up the ./kiwix-desktop_x86_64_2.0.5.appimage, the screen looks like this:  (unreadable text)

Is there some export VARIABLE=something trick one can do to make kiwix honor the operating system choice on DARK vs LIGHT them?

![image](https://user-images.githubusercontent.com/35307604/101782136-5317b200-3b01-11eb-98bd-3122910b9284.png)

**Comment by Jaifroid** [comment]
@deadlydud You are using Kiwix Desktop,. whereas this is the GitHub for Kiwix JS, which is the version for use in browser extensions, and is a very different code base. So you should ask on https://github.com/kiwix/kiwix-desktop .

We do have a dark theme in our browser extension. If you are running Windows, and Windows 10 in particular, then there is also a version in the Microsoft Store (search for "Kiwix") which has a dark theme too. See https://kiwix.github.io/kiwix-js-windows/kiwix-js-uwp.html .

**Comment by Jaifroid** [comment]
Ah, it looks like you might be using a Mac, in which case ask on Kiwix Desktop as mentioned above.

**Comment by deadlydud** [comment]
Thank you Jaifroid for you comment. I'm trying to make an off-line instance for someone, so they can view some Wikipedia articles, Was un-aware about Kiwix "Desktop mode vs JS version"...   I just followed the normal "dumb-drone-user" mode.. googled for Kixiw after reading about it, got to https://www.kiwix.org/en/ ... and hit Download..   chose GNU/Linux – x86-64 bit binaries (Yes the machine is a Kubuntu 18.04 not a MAC), .. .
 (Download .appimage file, then set executable permission and execute it.).... and went from there...

Maybe a good idea to mention on that web-page that there are differences between a Desktop version and a JS version...

I'll look on https://github.com/kiwix/kiwix-desktop  to see if I can find an answer on how to switch between light-mode and dark-mode on the Desktop app..

**Comment by deadlydud** [comment]
aargh.. .this is NOT my day .... went through all Jaifroid's advise... and ended up on trying get help only for the
git-hub "submit new issue" button to be totally non-reactive... nothing happens on the button click ...
I'm giving up.. moving onto other things... (grumbles) that was on https://github.com/kiwix/kiwix-desktop/issues/new

I am just wondering how many other internet citizens are stumbling over these "rocks" and never mentions it.



![image](https://user-images.githubusercontent.com/35307604/101784923-cff85b00-3b04-11eb-867d-2e058c9ef727.png)

**Comment by mossroy** [comment]
@deadlydud : could it be because you did not give a title?

**Comment by Jaifroid** [comment]
@deadlydud Looking at your screenshot, it looks like you didn't add an issue title, which is probalby why you couldn't submit it.

**Comment by deadlydud** [comment]
Blush. you are correct. In a Noob's defence: button stays green.. doesn't grey out if info is missing.. 
and human interface design: if click button and can't submit: validate alert with "title needed".
Thanks for pointing it out. Time for me to sleep and get fresh concentration.

**Comment by b16r05** [comment]
@Jaifroid I noticed that you mentioned a stylish theme on Jan 5, 2020. I urge you to look at this: https://kinda-static.userstyles.org/styles/154881/wikipedia-clean-dark. It is hands down the best wikipedia theme out there. The font, colors, and the pop up on either side would be excellent in kiwix. Very similar to wikiwand, without the privacy issue!

**Comment by Jaifroid** [comment]
@b16r05 Thanks for the recommendation. The only issue is that the theme doesn't seem to have been updated since early 2018, which is probably not a problem if it still works fine. We have an inversion-based theme in Kiwix JS which seems to work well and looks good, and in Kiwix JS Windows I have both a simple inversion theme and a more complex one that has rules for most Wikipedia elements, but it's not perfect. I think Kiwix Android also has an inversion-based dark theme.

**Comment by b16r05** [comment]
@jaifroid

Yes, it's true! That theme has not been updated, but it does works well - I have been using it for a long time (years) : )

I finally, finally, tried Kiwix-js 3.1.0 ... and, wow, wow, wow : ) Very nice! Color is nice. Inversion-based theme works well. 

Suggestions:

1. I, personally, don't like the spinning circle... but, not a problem. Links are fast enough.

2. SEARCH and RANDOM take up space. They can put on the same line as Kiwix logo (version) [I will call this MENU line), placed on the right side. 

3. Navigation bar at the bottom still does not make sense. We are in a browser after all. HOME link can be programmed on top of the kiwix name (top left). BACK and FORWARD link not required (We are in a browser).  SCROLL TO TOP could be moved up, on the MENU bar for now. 

... 

Moving items to menu bar: 

KIWIX 3.1.0 || HOME || CONFIG || ABOUT || SCROLL TO TOP ICON || SEARCH || RANDOM

Rearranging items on menu bar: 

KIWIX 3.1.0 || SEARCH || RANDOM || SCROLL TO TOP ICON || CONFIG || ABOUT 

Now, that is a professional look. Making the font of the menu bar items even more compact, will give readers even more digital real-estate for... reading :)

Finally, Wikipedia Clean Dark Stylish theme has an excellent, scrollable pop up, with links, on the right. The install page, here: https://userstyles.org/styles/154881/wikipedia-clean-dark

has a button that shows CSS code. Maybe this code can be tried out with kiwix-js and modified as needed. Just a thought! 

I would try it if I knew CSS! But, I don't know enough!

**Comment by Jaifroid** [comment]
@b16r05 I re-posted part of your comment relating to UI in #523 and will answer there.

**Comment by b16r05** [comment]
@jaifroid ... feature requests (Le me know if this is already decided somewhere)

Since we are talking, I wasn't sure if I should create new issues. So, I will just ask here. You can move and create new issues as you like, or, let me know, and I will create new issues. 

Bookmarks: Can we have bookmarks in kiwix-js? Maybe this might be an intensive feature request, but, it would be nice to be able to bookmark pages and go back to them, as needed, especially if someone is researching. 

Mutiple instances: Can we have multiple instances, in tabs? Say, we want to have two kiwix-js tabs open in a browser This, again, can be used for researching. 

Links: There are some links that are internal to kiwix-js using the zim file, and some links that are external. Maybe, we need to have color differentiation, so, users know that a particular link will browse within Kiwix-js, and others, point the greater internet.

That's all for now : )

**Comment by Jaifroid** [comment]
@b16r05 Thanks for suggestions:

* Bookmarks: I think you could create a separate issue for this, describing how you envisage this working. Problem would be knowing how to deal with multiple ZIMs.
* Multiple instances: there is already a PR in-progress for this #680 (issue #678). PR is basically complete, pending getting it to pass tests and review. Note that if you are able to use Service Worker mode (doesn't work in Firefox Extension), you can already use multiple tabs. You can try this with the Chrome or Edge extensions/add-ons: install the extension, switch to Service Worker mode (Configuration) and then open a new tab with Ctrl-click or right-click -> "open link in new tab". PR #680 allow this to work also in JQuery mode.
* External links should already have an external icon, at least in Wikimedia ZIMs. Do you not see it?

Thanks once again for the valuable feedback.
