### ISSUE TITLE
Update jQuery to 3.2.1 or 3.2.1.slim

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#268]
I have tested both in Edge and Firefox, and they cause no problems I can see. Since we seem to be using only standard jQuery functionality, it may make sense to use the slim version (NB this is not minified, it's just a subset of jQuery functionality, the most used ones).

**Rationale**: keeping it up to date keeps on top of latest bugfixes and security issues.

**Disadvantage**: may not be backwardly compatible with legacy browsers or browser engines. Needs testing on FFOS, Symbian (?), Internet Explorer.

**Comment by mossroy** [comment]
Officially, jQuery does not support that much browsers/versions (see http://jquery.com/browser-support/). It only supports very recent versions of Firefox and Chrome, no Edge on mobile, no IE on mobile, Symbian etc.
But that's the official support. We currently only use some basic features of jQuery, so it might work without problems, even on some older browsers. But that needs to be checked.
I think it's worth a PR.
I don't know if the slim version is enough : bootstrap uses some effects on menus (on small screens), and I don't know if it's based on jQuery or not.
I was thinking about adding some transitions (see #74), but we can stil switch to the non-slim version later, if we need it. So it's probably worth trying the slim version, to see if it works or not.
I'll do the testing on FirefoxOS

**Comment by Jaifroid** [comment]
I'll include 3.2.1 and 3.2.1-slim in the repo and a commented switch between them in init.js.

(Btw, Edge mobile is supposed to be compiled from the same source as Edge desktop, and MS keeps them in sync approx. every other build.)
