### ISSUE TITLE
Update requireJS to 2.3.3

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#270]
Tested and working in Edge and Firefox. See rationale and drawbacks in #268.

**Comment by mossroy** [comment]
Why not. We only use very basic features of requireJS so it should not be an issue.
And it still has a very broad range of browsers/versions support.
Please create a PR

**Comment by Jaifroid** [comment]
Quick question, @mossroy  - should I do a separate PR for each of these separate libraries (require, jQuery, bootstrap), or a single "Update libraries to latest stable versions" PR?

**Comment by mossroy** [comment]
It's probably better to do a PR for each upgraded library. It would help debugging/reverting in case of a regression due to one of these upgrades

**Comment by Jaifroid** [comment]
Rebased, merged, squashed.
