### ISSUE TITLE
Noticed img links with data-file-type=bitmap aren't being injected

### ISSUE THREAD

**Issue by sharun-s** [kiwix/kiwix-js#294]
Noticed this on two pages (wikipedia_en_all_2016-12.zim) 
Boeing GA-1 
Boeing P-12
files are *.jpg files with data-file-type set to bitmap. 
I tried changing the  mimetype to different things while creating the Blob but it didn't help. Some weird content is being sent back from file.blob read so I am guessing these files are not in the zim or some decoding/encoding issue.

**Comment by mossroy** [comment]
Did you try with the desktop version of Kiwix, to check it does not from the ZIM file itself?

**Comment by sharun-s** [comment]
Just checked those articles there, and images don't show. So probably missing from ZIM.
Raises couple issues:
1. What's the desired behavior here? Maybe collapse the image and leave a console.error log

2. This data-file-type attribute is misleading - says bitmap while src points at a jpeg and blob gets created with image mimetype. Similar ambiguity with the svg images as seen on the sine.html issue. What needs to happen here with different images needs some clarity.

3. Where to report issues about errors in the zim file? There are two kinds here - one is for whoever is creating the file, And the other is things like the img attribute data-file-type ambiguity.

**Comment by Jaifroid** [comment]
I patch the mimetype issue [this way](https://github.com/kiwix/kiwix-js/blob/Preload-stylesheets/www/js/app.js#L1303), as mentioned in another thread. I think if an image is actually broken, it should show as broken -- we shouldn't cover for that, or else problems won't get discovered. Report ZIM-file issues at https://github.com/openzim/mwoffliner .

**Comment by mossroy** [comment]
I agree with last comment, and close this issue
