### ISSUE TITLE
Provide capability for searching within article

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#301]
Edit: I'm aware this functionality is principally for mobile, where the in-browser search option (Control or Command F) is not available. But this also applies to UWP apps on tablets.

@mossroy , @sharun-s  Commit https://github.com/kiwix/kiwix-js/commit/d3c29e4f17cfb0e5af994d3472b572ad205a01f4 now provides a search-in-article capability. For now, what this does is to highlight the text that has been typed, but it doesn't (yet) automatically scroll to the first found item -- I think I'll add a button to do that. It works with accented characters at least in European languages, though I might need to add some more as for now, they are the main ones in French, German and Spànish. **Important note**: For this to work in Firefox OS, and indeed I suspect in any OS, `util.js` (where the main function lives) must be UTF8 format with BOM, otherwise accented characters do NOT work. Tested and working on UWP, Edge, Firefox, FFOS and Internet Explorer. Screenshots below.

You'll notice I've commandeered the search button for this, and have inserted a Book glyphicon instead for the search-for-article, though that button doesn't seem so necessary to me since search operates through onKeyUp (except that @Sharun-s isn't using the onKeyUp option in his repo). I've adopted @sharun-s's UI, but with some larger elements for mobile, as it seems more compact and modern, and does away with the infuriating hamburger toggle ;-) .

This is the French article on Colombie in FFOS:

![image](https://user-images.githubusercontent.com/4304337/29462525-9459a852-8427-11e7-8196-d8d7bcaabea1.png)

This is Spanish article on the Trojan prince Paris in dark mode on Windows Mobile:

![image](https://user-images.githubusercontent.com/4304337/29462858-a260c0ec-8428-11e7-88ce-b23a0555f536.png)

**Comment by sharun-s** [comment]
Nice. I like your night mode! And the keyup should work, you just have to set autoComplete to true in init.js

**Comment by Jaifroid** [comment]
Ha, @sharun-s , I should have guessed you'd made autoComplete an option! Nice idea.

**Comment by Jaifroid** [comment]
Quick update: commit https://github.com/kiwix/kiwix-js/commit/ebac2cb3e5085c443fe37476cab2293092510b42 now enables scrolling to the first full match, either by pressing enter key, or by tapping the Full: ... link.

![image](https://user-images.githubusercontent.com/4304337/29497505-b6df9f84-85e0-11e7-8b2b-339414eabc26.png)

**Comment by Jaifroid** [comment]
I've now enabled auto-scroll and scroll to next item by pressing enter/return or tapping Full:... link or pressing find key on mobile keyboard. Commit https://github.com/kiwix/kiwix-js/commit/f3c1c57b5eb235135a58f5e977c47c84abb8b8a1 .

![image](https://user-images.githubusercontent.com/4304337/29509229-70d19a64-864f-11e7-9b46-edf68fe901f8.png)

**Comment by kelson42** [comment]
Maybe this ticket needs a refresh. Kiwix-JS being meanwhile to 99% a browser extension solution, I challenge the pertinence of this ticket. Or maybe it should be rephrased, or just moved to kiwix/kiwix-js-windows?

**Comment by Jaifroid** [comment]
The issue is fully implemented in Kiwix JS Windows. I'm not convinced Kiwix JS will always only be a browser extension solution. For example, if it converges a bit more with Kiwix JS Windows, then Kiwix JS could also be a PWA which, on mobile, could still have this issue. However, it's perfectly fine to close this issue given that there is an implementation in KJSW, and re-open should the need arise here int he future.
