### ISSUE TITLE
Use Bootstrap panels to organize Configuration page

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#302]
In Kiwix JS Windows I'm now using Bootstrap panels to organize the Configuration page. I'd be very happy to backport it here, if it's wanted. Obviously only the options implemented / used in Kiwix JS would be backported, so this should be decided after it is decided which, if any, of those options to adopt. So I haven't added a milestone. Screenshots below (please ignore typo in second screenshot!!).

### Top half of Configuration page:

![image](https://user-images.githubusercontent.com/4304337/29748955-a2f7ff0a-8b19-11e7-87a4-d0bc91718fba.png)
 
 
 
### Bottom half of Configuration page:

![image](https://user-images.githubusercontent.com/4304337/29748969-cb19688e-8b19-11e7-9519-a135ced3e68b.png)

**Comment by mossroy** [comment]
Good idea, it makes the UI more clear and prettier. That's worth a pull request, even if it might not be a top priority.
It's probably not an issue to add/remove some options afterwards, I suppose the merge would not be very complicated

**Comment by Jaifroid** [comment]
OK, I've added a PR, but with only one panel the benefit is not so obvious. But it lays down the standard grid system which is then  very easy to add to as we add more options and potentially more sections (plain Settings as well as Expert Settings, as per screenshots above).

**Comment by Jaifroid** [comment]
Just to say, there is a new commit for PR #303 .
