### ISSUE TITLE
Fix alignment of icons in bottom toolbar

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#311]
It's not clear at what point in the repository this happened, but bottom toolbar icons are now no longer evenly spaced, as per image below. Need to investigate the bootstrap css required to produce even alignment. 

![image](https://user-images.githubusercontent.com/4304337/34078160-766b230e-e30c-11e7-9697-93ceeddaebbc.png)

**Comment by Jaifroid** [comment]
Commit  https://github.com/kiwix/kiwix-js/commit/ab4c3ba4bc5ac423178cb51f22b4db6e50912c3d seems to fix this issue (tested in FFOS simulator, shown in screenshot).

The "restrictedSize" class seems to interfere with things, and it may be redundant anyway. It is better to let bootstrap manage resizing according to screen size. Do we need to keep it?

@mossroy , please test with your physical device, and I can do a PR if this seems like the right approach.

![image](https://user-images.githubusercontent.com/4304337/34149761-05850ef0-e49e-11e7-9c62-5841e7bfbcbe.png)

**Comment by mossroy** [comment]
I tested on my physical device : the icons location seem to be fine, thank you!
Please create a PR for that

**Comment by mossroy** [comment]
And I did not reproduce the issue that made me add this "restrictedSize" class at some point
