### ISSUE TITLE
Links in article to footnotes do not function correctly

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#318]
When I click / tap on a footnote reference marker, I get the message shown in the screenshot below (this is Kiwix JS in the FFOS Simulator with a recent Wikipedia-style ZIM). On Kiwix JS Windows nothing at all happens. Could this error have been introduced with the code to support subdirectories in ZIMs, or has it always existed and we've just not noticed it till now?

![image](https://user-images.githubusercontent.com/4304337/34198671-21066492-e563-11e7-893d-ac32ebac0b1c.png)

**Comment by mossroy** [comment]
This is certainly a regression due to the base tag I added in #310 
I did not expect that it would change the href of anchors like that.

**Comment by Jaifroid** [comment]
Ah yes, of course. Looking at the actual URL in the Inspector, it appears as

`<a href="#cite_note-1" style="counter-reset: mw-Ref 1;"><span class="mw-reflink-text">[1]</span></a>`

However, when I look at the value of "url" in:
```
                else if (url.slice(0, 1) === "#") {
                    // It's an anchor link : do nothing
                }

```
It is registering as `A/Tunisie.html`. Therefore, the code is hitting the else clause below and adding an event listener (thinks it's a link to another article). We could work around by changing above line to: `else if (url.slice(0, 3) === "A/#")`. 
```
                else {
                    // It's a link to another article
                    // Add an onclick event to go to this article
                    // instead of following the link
                    $(this).on('click', function(e) {
                        var decodedURL = decodeURIComponent(url);
                        pushBrowserHistoryState(decodedURL);
                        goToArticle(decodedURL);
                        return false;
                    });
                }
```

**Comment by mossroy** [comment]
Sorry about that regression.
I'll try to propose a fix that works in every case (including with subdirectories in article URL)

**Comment by kelson42** [comment]
This ticket might be related. Thought this is important you know about: https://github.com/openzim/mwoffliner/issues/136
