### ISSUE TITLE
Rename misleading variable name after #310

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#325]
This is something I came across when porting the changes in #310 and #319 to Kiwix-js-windows, and it caused me a bit of confusion:

We still have in app.js several instances of a variable called `readableTitle` that is returned from zimArchive.js. For example:

`selectedArchive.readBinaryFile(dirEntry, function(readableTitle, content) {`

This variable `readableTitle` is no longer a readable title, it is the full dirEntry, following the [changes made in zimArchive.js](https://github.com/kiwix/kiwix-js/pull/310/files#diff-1916c6001d87418e72ffda9cfa7b2d82L245) as a result of #310 (Support subdirectories in articles).

So I propose we rename `readableTitle` to `fileDirEntry` or something similar. There are currently four instances in app.js. While it doesn't affect the functionality of the code, it makes it a bit less comprehensible for a human.

**Comment by mossroy** [comment]
I fully agree.

**Comment by Jaifroid** [comment]
OK, I'll do a PR.

**Comment by mossroy** [comment]
Fixed by #326
