### ISSUE TITLE
Random page button does not produce a title with namespace set

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#332]
While the random page is correctly found, the returned title variable does not have the namespace `A/`. Therefore an incorrect page gets stored in the windows.history, affecting the back button.

I think this is a regression caused by #310 ? We could either add a namespace if one is missing in the pushBrowserHistoryState function, or (better) fix the random page function.

I'm slightly guessing at how this issue affects Kiwix JS, because it has arisen while investigating a remember last visited page function in Kiwix JS Windows, but it's definitely storing the page without namespace in pushBrowserHistoryState.

@mossroy

**Comment by Jaifroid** [comment]
Additional info: when you navigate to a page using a URL link, the title gets stored with namespace `A/` in pushBrowserHistoryState. It's only with the random button that the namespace does not get set.

**Comment by mossroy** [comment]
Strange : I don't reproduce the issue. When I use this random button, it does push a complete URL (starting with A/) in the browser history (and in the URL). And the back/forward buttons seem to work fine.

**Comment by Jaifroid** [comment]
Oh, maybe I've got Kiwix JS Windows into a strange state then. Clearly I need to investigate further. I thought I'd ported the namespace fix fully to Kiwix JS Windows....

**Comment by Jaifroid** [comment]
Sorry, @Mossroy, I had missed out the addition of `dirEntry.namespace` in my backport of your namespace fixes:

`pushBrowserHistoryState(dirEntry.namespace + "/" + dirEntry.url);`

in the goToRandomArticle function!
