### ISSUE TITLE
Links with a # in the URL are failing when it is not anchor

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#359]
At least in jQuery mode.
For example in the stackoverflow ZIM file, click on "C#" (the programming language) in the home screen : nothing happens, where all the other links are working.

**Comment by kelson42** [comment]
@mossroy Still buggy?

**Comment by mossroy** [comment]
@kelson42 Yes, it's still buggy with `stackoverflow.com_eng_all_2017-05.zim` but it probably comes from the file itself.
There is the same issue with kiwix desktop 2.0-beta5, and in our jQuery and SW modes. In all cases, it tries to read article `C` instead of `C#`. I suppose the `#` is not encoded correctly in this file.

If you have the `stackoverflow.com_en_all_2019-02.zim` file, could you test with it? (It's really big to download...)

**Comment by kelson42** [comment]
@mossroy You are right `../I/tag/c%23/1.html` and it should be `../A/tag/c%23/1.html`. Should be quite trivial to fix. I'll move the whole ticket.

**Comment by kelson42** [comment]
See https://github.com/openzim/sotoki/issues/86
