### ISSUE TITLE
Use more functional programming in javascript

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#363]

**Comment by kelson42** [comment]
@Jaifroid I’m not reall sure how this ticket could be actionable. I’m not even sure to fully understand it, Do you?

**Comment by Jaifroid** [comment]
Our codebase is very object-oriented, which I think has fallen out of fashion. But no real way to change that, so I agree there's not much we could do in real terms, other than in the future think about providing clearly defined and self-contained functions that don't modify global variables, etc... So closing.

**Comment by kelson42** [comment]
Object-oriented is not out of fashion, to the contrary.

**Comment by Jaifroid** [comment]
Debate is all the rage over at r/JavaScript - e.g. https://www.reddit.com/r/javascript/comments/sssf2r/askjs_object_oriented_or_functional_which_one_you/ . Six of one and half-a-dozen of the other!

**Comment by Jaifroid** [comment]
As someone writes there "These FP-vs-OOP topics usually feel more like an attempt at tribalist validation than a proper technical discussion." 😲
