### ISSUE TITLE
CI should be able to create the nightly directory (with the date)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#364]
_From @kelson42 on May 2, 2018 15:28_

It is currently created by a cron, but most of the time, the last directory is empty and this is a problem. To avoid this the first to write to download.kiwix.org should create the directory YYYY-MM-DD. One time this is done the cron will be removed (we will still keep the part cleaning the old nightlies).

_Copied from original issue: kiwix/kiwix-tools#191_

**Comment by kelson42** [comment]
@mossroy Could you please fix that pb, so we can stop created empty directories?

**Comment by mossroy** [comment]
I should be able to work on that next weekend
