### ISSUE TITLE
Sometimes, some CSS can not be loaded, due to "out of memory" errors, at least in a browser extension

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#365]
At least on Firefox 52 ESR, as a browser extension, some CSS fail to load with following error in the console : `could not find DirEntry for CSS : -/s/css_modules/inserted_style_mobile.css out of memory`.
Stacktrace : 
```
13:48:18,961 could not find DirEntry for CSS : -/s/css_modules/inserted_style_mobile.css out of memory 1 app.js:971:33
	loadCSSJQuery/</< moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/app.js:971:33
	_rejected moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:804:24
	Promise.prototype.then/</< moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:830:30
	reject/rejection<.when moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:1064:31
	Promise/promise.promiseDispatch moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:748:26
	become/</< moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:564:17
	flush moz-extension://9b084d9a-6efc-493d-a669-38bcd831a085/www/js/lib/q.js:110:17
```
I had that on Firefox 52 ESR, using wikivoyage_en_all_novid_2018-03.zim, on the main page. Sometimes it's a different CSS.

I have to test more to better understand in which circumstances this happens

**Comment by Jaifroid** [comment]
I wonder if this is a problem I encountered with too many .svg images being sent at once for decompression hanging xzdec.js. As xdec.js errors are swallowed by Q it can be hard to tell where they're coming from. CSS are like SVG in that they are plain text and *highly* compressed. On low-memory devices, @kelson42 and I discovered (vis-à-vis his test Windows Mobile device) that we had to send the svg images one by one to the decompressor. Even sending them in batches of two or three could hang a low-memory device.

**Comment by mossroy** [comment]
It looks like a real weakness of our current decompressor. I'd really like to avoid queuing the decompressions.
I should test that with the WebAssembly version and/or the newly re-compiled version of xzdec (#219).
I'll try to investigate when I find some time.

**Comment by mossroy** [comment]
I still don't reproduce, so close this issue for now
