### ISSUE TITLE
Read CSS as UTF8 strings instead of binary

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#370]
This has puzzled me for some time and I believe I've now discovered the cause. At least in jQuery mode, we currently use `zimArchive.readBinaryFile()` to decode CSS files, whereas for articles (i.e. html files) we use `zimArchive.readArticle()`. The only difference between these two is that the latter decodes the binary array using `utf8.parse()` whereas the former transforms the binary array using a slightly hacky `util.uintToString()` function that also claims to convert a binary array to UTF8 (we call that in jQuery mode in app.js to turn the binary into a string).

If we examine the footer of a typical article from full English Wikipedia, e.g. Piracetam.html (NB this needs to be a desktop-style ZIM, not mobile, to see the difference), using Firefox Quantum, this is what we see in our current master branch:

![image](https://user-images.githubusercontent.com/4304337/40304369-6eceadb2-5cee-11e8-9360-41153bd7d4f1.png)

If we instead use the same routine to decode the CSS file that we use to decode the HTML file, this is what we get:

![image](https://user-images.githubusercontent.com/4304337/40304439-a7efd684-5cee-11e8-990e-69a699db822c.png)

The second is clearly correct. Commit https://github.com/kiwix/kiwix-js/commit/abadc19543447abd6f4e081cc5c81626c836324c shows suggested changes (so far only in jQuery mode) that could solve this issue. I note that all files (other than the article) are sent to the Service Worker in binary format: it may be that the browser knows how to decode the CSS files, but it would be worth testing whether the first image above is what is shown in Service Worker (on master), or the second. If it is the first, then a similar fix may be needed in Service Worker.

**Comment by Jaifroid** [comment]
PS Ray Charles articles show the same effect as the article above on master vs the [Decode-CSS-as-UTF8-byte-array](https://github.com/kiwix/kiwix-js/tree/Decode-CSS-as-UTF8-byte-array-instead-of-uint8-binary) branch.

**Comment by mossroy** [comment]
Excellent discovery!
I reproduce the issue, and can confirm it does not happen in ServiceWorker mode (with Firefox or Chrome). Your branch seems to solve the issue in jQuery mode.
Cool! That's worth a PR

**Comment by Jaifroid** [comment]
I changed title of this issue because I think technically we "encode" binary as UTF8 rather than "decode". "Read" should avoid (my) confusion.

**Comment by Jaifroid** [comment]
Merged #371
