### ISSUE TITLE
Should Random button exclude user profiles for Stackexchange ZIMs?

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#373]
I realize this isn't really generic, but not sure otherwise how to deal with this. I find it annoying, when using the random button to read something new in Stackexchange ZIMs, that more than half the time I will land on a user profile page. These are not articles.

We currently have a test that ensures that the random page we land on is an article. Would it be legitimate to extend that test to filter out other non-article types such as user profiles? It can be done like this: change just the asterisked [line below](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L1058) in `function gotoRandomArticle()` to the example given after:

```
              * if (dirEntry.namespace === 'A') {
                    $("#articleName").html(dirEntry.title);
                    $("#readingArticle").show();
                    $('#articleContent').contents().find('body').html("");
                    readArticle(dirEntry);
                }
```

Change to:

```
               if (dirEntry.namespace === 'A' && !/^user\//.test(dirEntry.url)) {
                    $("#articleName").html(dirEntry.title);
                    $("#readingArticle").show();
                    $('#articleContent').contents().find('body').html("");
                    readArticle(dirEntry);
                }
```

**Comment by kelson42** [comment]
I do not think the reader should make that kind of decision. All the articles in the A/ namespace should be considered as content. IMO we should think to a more generic approach - at ZIM level - if we want to provide this kind of feature.

**Comment by Jaifroid** [comment]
OK, thanks @kelson42 . Is there another namespace that user profiles can be assigned to for Stackexchange ZIMs? IMHO, these profiles pollute the concept of an 'Article', which is presumably what the A/ namespace was intended for. There are other content types such as tags that probably shouldn't be in A/ either.

**Comment by kelson42** [comment]
@Jaifroid The concept of namespace is going to be removed soon, so we need to find a way without them. Maybe we should remove these pages? IMO, this is worth asking to an option to avoid to create them in https://github.com/openzim/sotoki

**Comment by mossroy** [comment]
I also find that annoying, even if it's not a major issue.
But I also agree that this should be handled on the ZIM builder side.

**Comment by Jaifroid** [comment]
I have opened https://github.com/openzim/sotoki/issues/77 .
