### ISSUE TITLE
Sections are still closed in ServiceWorker mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#374]
I've finally managed to get ServiceWorker mode working in Chromium (not Chrome), and I notice that #355 is not fixed in this mode. We need to add our workaround to the iframe onload event, and not cancel that event the first time it fires, because it will need to fire for every subsequent page load in ServiceWorker mode.

The alternative would be to enable JavaScript in ServiceWorker -- @mossroy, you mentioned you had got it working. But it may be premature to merge that.

Either way, we need a fix before completing 2.3, I think, because recent ZIMs are effectively unusable in ServiceWorker. I'm happy to try to tackle it, but it may be easier for you to do, @mossroy , as you know much better how exactly ServiceWorker works. I understand it has no access to the DOM, so we have to do this in app.js.

**Comment by mossroy** [comment]
I know, I saw that.
My opinion is that we should leave it as it is for 2.3. The ServiceWorker mode is not the default mode. Activating it displays a big warning saying it is unstable : I don't expect anybody to actually use it, except for testing purpose.
The right way to fix this is to enable javascript, which does not seem difficult to do (but needs some testing and might reduce performance) : I suppose we'll be able to do that for 2.4. The "only" issue with that will be inline javascript (blocked by CSP in browser extensions).

My goal is to keep the ServiceWorker mode as clean and simple as possible : we should not parse the DOM or modify the HTML, and we should not code workarounds for problems inside some ZIM files.
I know it might be difficult and take some time : sometimes it involves modifying the ZIM files themselves (as for the inline javascript). But the jQuery mode provides a fallback that gives us some time.

**Comment by Jaifroid** [comment]
OK, that's fine -- thanks for the explanation!
