### ISSUE TITLE
Multiple 404 errors in Chromium and Edge when running from localhost in jQuery mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#376]
This is effectively the same error as #272. It occurs also with stylesheets when the browser is running kiwix-js from localhost -- screenshot below is from Chromium. I see this in the console log of Chromium and Edge (but not Firefox). I imagine it's also occurring under the hood when running from the file:// protocol, but the console log doesn't bind the network stack in file:// protocol.

The solution is the same as for images. We can add this line below the current regex for images, but for the sake of completeness, we should do the same for scripts. Full suggested revised code is:
```
    if (contentInjectionMode === 'jquery') {
        // Fast-replace img and script src with data-kiwixsrc [kiwix-js #272]
        htmlArticle = htmlArticle.replace(/(<(?:img|script)\s+[^>]*\b)src(\s*=)/ig, '$1data-kiwixsrc$2');
        // Replace link hrefs to prevent 404 errors in http:// mode
        htmlArticle = htmlArticle.replace(/(<link\s+[^>]*\b)href(\s*=)/ig, '$1data-kiwixhref$2');            
    }

```
Then, in `loacCSSJQuery()`, just as in `loadImagesJQuery()` we reference `link.attr("data-kiwixhref")` instead of `link.attr("href")`.

![image](https://user-images.githubusercontent.com/4304337/40539454-b7a9c96a-600c-11e8-91c0-4bf2466746e7.png)

**Comment by mossroy** [comment]
I agree (I saw that too), but I'll change the label to "enhancement", as it has no impact for the user.

**Comment by Jaifroid** [comment]
Commit https://github.com/kiwix/kiwix-js/commit/64061cc8d9ca88957e60c80dd57cc7e33e7a3e4c implements this fix. Tested on Edge, IE11, FFOS and Chromium (Edge and Chromium in http: mode as well as file:// mode). I'm happy to wait to do a PR after v2.3 or, as it's small, if you decide to change the milestone, I can do a PR now. No rush. -- I don't want to delay 2.3.

**Comment by Jaifroid** [comment]
Forgot to update `loadJavaScriptJQuery()` too. Done (branch [Fix-404-errors-in-http-mode](https://github.com/kiwix/kiwix-js/compare/Fix-404-errors-in-http-mode)).

**Comment by mossroy** [comment]
Please create the PR : we'll see if it can be in 2.3 or not.
