### ISSUE TITLE
In old Stackexchange files (at least) some content is still hidden under the bottom bar

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#386]
I noticed this on several (all?) of the tag question lists on `stackoverflow.com_eng_all_2017-05.zim` (in Firefox, but that's just because it's what I was using). It affects mostly non-mobile screen widths: sometimes actual content is hidden, or a "Next" link becomes impossible to click (you can see it beneath the transparency, but not click on it) sometimes part of the Kiwix info footer is hidden. Mobile-width displays are not so affected.

This may be better addressed through #120 or #337.

**Comment by kelson42** [comment]
@Jaifroid I don't think I can reproduce the problem anymore on recent FF with recent Stackoverflow ZIM file. That said, it is true that if the bottom bar can not be removed, or the some kind of page padding introduced, then if something is clickable at the really bottom of the page, it won't be anymore.

**Comment by Jaifroid** [comment]
It seems less of a problem now. In any case, we have #523 that covers this, as one of the ideas there is to make the bottom bar disappear a few seconds after scroll stop. So I'm closing this.
