### ISSUE TITLE
Correct the mimetype for SVG images in jQuery and ServiceWorker

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#390]
As noted in #219 and #278, SVG images (the usual format for equation fallback images) have no hope of being displayed correctly currently in ServiceWorker or in jQuery modes, because no correct mimetype is applied to them. This would also address, but not fully fix #308 (#389 would be needed fully to enable display of equations).

**Comment by Jaifroid** [comment]
I should add that there is already an issue #137 for a possible ZIM-based solution. I shall propose a pragmatic solution, but we should also see if a more generic one is possible either now or later (I don't feel I have the knowledge to do the latter).

**Comment by mossroy** [comment]
Fixed by #391 
A more generic way to handle mimetypes is tracked on #137

**Comment by Jaifroid** [comment]
@kelson42 I think the issue is that we don't have a function to read the ZIM's mimetype table, so we can't (currently) derive the mimetype from the dirEntry's mimetype byte, as it's meaningless without the table. If the mimetype table is always the same for every ZIM, then we could do it. But we don't know that, I think, looking at the specs. It's quite low-level stuff...

**Comment by kelson42** [comment]
@Jaifroid OK, no the mime-type is not always the same. This should be retrieved at each file opening.

**Comment by kelson42** [comment]
@Jaifroid @mossroy This is a quite dangerous approach on the longer term. I have for example in project to implement https://github.com/openzim/mwoffliner/issues/278. That mean that web pages would not end anymore with an ".html" extension.

**Comment by Jaifroid** [comment]
I completely agree. It shouldn't be *too* difficult to read the mimetype table on ZIM opening. We don't even need xzdec to do that. It's just like reading a dirEntry, I believe, but it's low-level stuff I don't feel very confident about atm. Hopefully we'll get that implemented before the change you mention, though. We have issue #137 to work on it.
