### ISSUE TITLE
search doesn't work properly for wikipedia_de_all_nopic_2018-05.zim

### ISSUE THREAD

**Issue by practik** [kiwix/kiwix-js#399]
I'm finding it impossible to search the latest German Wikipedia ZIM (`wikipedia_de_all_nopic_2018-05.zim`) with kiwix-js.  By chance I discovered that typing the letter U into the search box will return a small number of results ("U 1 (Schiff, 1906)" through "U 225").  The letters V–Z return some results as well, as do some longer combinations starting with those letters, but for the most part this ZIM file is unusable with kiwix-js.  I also have `wikipedia_en_all_nopic_2017-08.zim`, and that  works fine.

Kiwix 2.3.0 on Firefox 60.0.2 on macOS

**Comment by kelson42** [comment]
@practik I think this file is somehow broken we have meanwhile published a new one.

**Comment by practik** [comment]
Thank you, @kelson42. Do you know where I can find the new file? It's not at http://wiki.kiwix.org/wiki/Content/de.

**Comment by Jaifroid** [comment]
@practik Try the later "novid" files as an alternative in the meantime. I don't see a later "nopic" file for German Wikipedia than the broken 2018_05, but there are larger "novid" files. Try ftp://download.kiwix.org/zim/wikipedia .

**Comment by practik** [comment]
Thank you, @Jaifroid ! The novid file is too big for me, but the FTP site had an older nopic version that works (`wikipedia_de_all_nopic_2018-04.zim`).
