### ISSUE TITLE
feature request: add favicon

### ISSUE THREAD

**Issue by practik** [kiwix/kiwix-js#401]
For those of us using kiwix-js on desktop browsers, it would be helpful to have the favicon showing on the Kiwix tab. I know this was mentioned in passing at https://github.com/kiwix/kiwix-js/issues/280#issuecomment-314118966, but since that issue is really about the window title, I figured the favicon should have its own issue.

Kiwix 2.3.0 on Firefox 61.0.1 on macOS

**Comment by mossroy** [comment]
That makes sense. It's probably easy to do.
We currently have an obsolete www/favicon.ico file (with an evopedia logo instead of kiwix), that should be removed, and replaced by some HTML `link rel="icon"` tags in the header of www/index.html, pointing to the existing PNG icons in www/icons

**Comment by mossroy** [comment]
It might also be worth adding `link rel="apple-touch-icon"` tags for Apple devices. And maybe the meta `name="msapplication-*"` ones plus the browserconfig.xml file?
http://faviconit.com seems to give some templates

**Comment by Jaifroid** [comment]
But would Apple devices use this app? Wouldn't they install the Kiwix app from their respective stores? If we are going to be fully inclusive, we would probably need to do everything on this cheat sheet:

https://github.com/audreyr/favicon-cheat-sheet 

But it may be over the top!

**Comment by mossroy** [comment]
This guide handles very old browsers that we do not even support : I agree with you it's no use adding hacks in our code for them.
