### ISSUE TITLE
Check version 2.4.0 of kiwix-js on Ubuntu Touch

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#407]
Hi @ernesst ,

I've uploaded a version 2.3.1 of kiwix-js on https://open.uappexplorer.com/ : could you please check it works properly?
It's a minor fix-version, because version 2.3.0 was using too much memory on recent ZIM files. It was crashing on devices without much RAM (512MB on Firefox OS devices).

**Comment by mossroy** [comment]
Version 2.4.0 should be uploaded today

**Comment by mossroy** [comment]
Version 2.4.0 is now available on https://open.uappexplorer.com/app/kiwix

**Comment by ernesst** [comment]
Thanks, the previous one seems to working fine. I'll check the 2.4 from the store.

**Comment by kelson42** [comment]
@ernesst Any feedback?

**Comment by mossroy** [comment]
Cool, thanks!
So I close this issue. Switching to 16.04 can be tracked on #375
