### ISSUE TITLE
In the Ray Charles zim, ogg audio file shows up in img tag

### ISSUE THREAD

**Issue by sharun-s** [kiwix/kiwix-js#409]
I was looking for a zim with audio files to test audio loading and found ../I/m/Beatles_eleanor_rigby.ogg in the Ray Charles zim inside a img tag. 
`<img src="../I/m/Beatles_eleanor_rigby.ogg" data-file-width="" data-file-height="" data-file-type="audio" >`
Is there some simple way to regenerate the Ray Charles zim to fix this? 
Also any zim's out there with audio files embedded?

**Comment by Jaifroid** [comment]
I've just checked the full English Wikipedia ZIM from June of this year, and for the same article on Eleanor Rigby (Song), there is no sign in the source HTML of the .ogg file. It appears to have been stripped probably as part of the stripping of video to make the filesize "manageable" (if you call 81GB manageable!). Looking at the corresponding page online, https://en.wikipedia.org/wiki/Eleanor_Rigby , the ogg file is clearly referenced in the media box, but even the plain href link has gone in the most recent ZIM version...

**Comment by sharun-s** [comment]
hmm...that's a lot of code in that media box. Have you done any zim file creation @Jaifroid ? Any idea what steps are involved in adding an audio file to the zim...trying to figure out which repo to use...

**Comment by Jaifroid** [comment]
Sorry, @sharun-s, I haven't done any ZIM creation. Maybe the people at mwoffliner can help? 
https://github.com/openzim/mwoffliner/issues

**Comment by sharun-s** [comment]
Thanks @Jaifroid. Will do some digging...

**Comment by mossroy** [comment]
This issue is now tracked in https://github.com/openzim/mwoffliner/issues/381 : I close here
