### ISSUE TITLE
Make use of the browser standard cache in ServiceWorker mode

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#411]
We have a ServiceWorker that traps the HTTP requests and reads the content inside the ZIM file.
It works fine, but we would greatly improve performance if we allowed the browser engine to make use of its standard HTTP cache.

I thought it would be simple to add an `ETag` in the responses coming from the ServiceWorker to the browser, so that next time a resource is needed, the ServiceWorker would get the request with a `If-None-Match` HTTP header. And the ServiceWorker could answer that the resource is unchanged.

But I did not manage to make it work so far, because I can not get the `If-None-Match` request header in the ServiceWorker.
It looks like the `event.request.header` object does not have all the headers, but only a few of them. I've created https://stackoverflow.com/questions/51696766/how-to-make-browsers-pass-all-http-headers-to-a-serviceworker in the hope to have some help.
The code of my initial (non-working) tests is in branch use-browser-cache-in-serviceworker-mode

**Comment by mossroy** [comment]
Based on https://github.com/w3c/ServiceWorker/issues/212 , I suppose that, inside the ServiceWorker spec, there are some rules to not expose all the request headers. At least when the request is not for the same origin.
Could we be in such a case?

I tested by putting the stackoverflow test-case on a distant https web server (so that I'm sure everything comes from that same origin), it did not change the result. So it's probably not a question of origin.

**Comment by mossroy** [comment]
Maybe another way to achieve what we want is to use the fetch API with the "only-if-cached" parameter, in order to grab a cached version if it exists?
See https://developer.mozilla.org/en-US/docs/Web/API/Request/cache

**Comment by Jaifroid** [comment]
I don't have the knowledge to contribute to an httpd solution, though it certainly sounds like the best way to do it if it works with localhost. I wonder if some browsers disable caching for localhost?

Without wishing at all to distract you from doing it this way, I did develop back in May (intending to use this cleaner code to replace my current filesystem caching in Kiwix JS Windows) a caching solution that uses indexeddb, localStorage or memory cache, according to the capabilities of the browser. It can persist (if the user wishes) the cache across browsing sessions (if the browser can use indexeddb or localStorage). I applied it to Service Worker, but don't know if I'm catching Service Worker requests the right way. Maybe something like my solution could be used for jQuery mode, alongside an httpd version for Service Worker?

For what it's worth, the code is in https://github.com/kiwix/kiwix-js/tree/Persist-cache-in-localStorage , and a screenshot of the caching controls I added is below. I've rebased this on master so it uses the latest xzdec.

![image](https://user-images.githubusercontent.com/4304337/45638336-d245e900-baa4-11e8-8f8e-514f5f52083d.png)

**Comment by mossroy** [comment]
I just pushed some code on the branch to look into the browser HTTP cache for resources instead of reading them in the ZIM file.
But it does not work for now.
I think the issue is that the resources never get into the cache. I'm fearing that browsers populate their HTTP cache with the requests made by ServiceWorkers, but not with their responses.
In that case, we would be stuck on this issue, as I don't see any way to programmatically populate the cache.

**Comment by mossroy** [comment]
Recent versions of Chrome (at least for Chromium 75) seem to use a short-life memory cache (when run inside a webextension) for URLs inside the extension.
It gave some side-effects (see #530) but it also seems to implement this feature in that particular context.

**Comment by Jaifroid** [comment]
Could we close this issue as a result of #556? I realize Cache API caching is not the same as the browser standard cache., but Cache API is the Service Worker's "native" caching technology, so maybe this PR and branch are no longer needed (especially since Chromium has something equivalent for extensions).

**Comment by mossroy** [comment]
I agree that this can be closed, and I would also close #415
