### ISSUE TITLE
In ServiceWorker mode, render the page before extracting all resources

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#413]
In ServiceWorker mode, the browser prioritize the requests by itself, just like #412 tries to do in jQuery mode : HTML, then CSS, then visible images, then other images.
But, for some reason, the page does not render before all images are read.
On big pages, it would be a much better user feeling to be able to read the beginning of it, while the rest is read from the ZIM file. Just like browsers do on any online page.

**Comment by Jaifroid** [comment]
Ah, I've found an interesting difference! In Edge, in Service Worker mode, if you load a page by searching for it, we get the behaviour you describe. But if you load a page by clicking on a link in an article, I see the whole process of page composition, starting with the text and no stylesheet, then some images, then the stylesheets, etc. However, this isn't the case in Firefox Quantum. I haven't checked Chromium. It seems that Edge doesn't pause the rendering when clicking on a link, whereas Firefox does. When we load a page from the search field, then the article DOM is hidden, explaining why I don't see the composition process in Edge either in that case. But what causes it to render in Service Worker mode? Could we bring that moment forward in the process?

**Comment by mossroy** [comment]
On wikipedia_fr_all_novid_2018-03.zim, if I try to open the article "Paris" : 
- on Chromium, it takes 4s to have a first display of the article (with missing images), and 14 more seconds for all the resources to be loaded (which makes a total of 18s)
- on Firefox, it takes 7s to display everything

In any case, I suppose we won't have much influence on the rendering strategy of the browsers.
I'll create a PR from the branch to fix the behavior after a search.
