### ISSUE TITLE
Release a version 2.4.0

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#420]
@Jaifroid, I think it's time to release a version 2.4 before the end of the hackathon.
There are IMHO a few significant improvements that are worth a release : decompression performance, and ServiceWorker stability.

- merge #418
- a few tests
- update the changelog file
- move open issues to 2.5
- create a tag on git : it should trigger the generation of unsigned extensions by Travis
- upload the unsigned extensions on Firefox and Chrome stores
- upload the application for ubuntu touch on https://open.uappexplorer.com
- prepare the source code for version 2.5
- when available, copy the signed extension binaries in https://download.kiwix.org/bin/browsers/
- communicate about these new versions

**Comment by Jaifroid** [comment]
Great! Yes, the improvements to decompression speed and SW stability are notable, and should be released sooner rather than later.

**Comment by mossroy** [comment]
Version 2.4.0 is now available on the Firefox and Ubuntu Touch stores, and will shortly be on Chrome store too.
