### ISSUE TITLE
Malformed anchor hrefs can cause an app crash

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#430]
As reported in [this comment](https://github.com/kiwix/kiwix-js/pull/429#issuecomment-430373239) (but note the article was "Cancer Immunotherapy" in the September 2018 WikiMed, and it has been corrected in later versions), a malformed anchor href causes the app to crash, at least in Edge. The problem was a malformed DOI: reference. Although transient, as a Wikipedia bot no doubt corrected it, our app should be a bit more tolerant of the possibility that `this.href`, `this.protocol` and `this.host` could be `undefined`. The crash occurs [here](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L887), and when that is corrected, it occurs [here](https://github.com/kiwix/kiwix-js/blob/master/www/js/app.js#L906).

A workaround is to use jQuery for those specific `this` references, as elsewhere in this function. However, we could also or instead add a test, like `if (!this.href) return;`

**Comment by mossroy** [comment]
I vote to fix this issue, as the fix you proposed was generic.
If the `if(!this.href)` test is enough, it might be a less risky modification of the code, except if you see other benefits from switching to jQuery here?

**Comment by Jaifroid** [comment]
I've created https://github.com/kiwix/kiwix-js/tree/Prevent-app-crash-with-malformed-anchor-hrefs to test the issue. It's got the jQuery fix added to it so I don't forget that fix, but I'll look into the simpler fix.

**Comment by Jaifroid** [comment]
Just for info, I've re-downloaded the September WikiMed (which I had accidentally deleted), and the problematic article is indeed `Immunotherapy`, as I had originally stated. It "reliably" causes an app crash on master.
