### ISSUE TITLE
Support asset filenames that contain apostrophes

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#449]
I found an article that has an asset filename with an unescaped apostrophe in the filename. The article is `Giudicato of Logudoro` in `wikipedia_en_all_novid_2018-06.zim`. The referenced file appears in the html as:
```
<img width="220" height="157" id="mwLA"
   src="../I/m/Sant'antioco_di_bisarcio%2C_capitello_figurato_01.JPG"
   data-file-type="bitmap" data-file-height="1945" data-file-width="2729">
```
I was surprised that this had not been percent encoded. However, it means that we have to deal with apostrophes in the code, and in particular we have to change `regexpTagsWithZimUrl`.

We have two possibilities. Either we assume that, because they are produced programmatically, all ZIM asset references will be surrounded by double quotes, e.g. `src="../I/……."` will never appear as `src='../I/…….'`. From my experience, I feel that is a safe assumption. If so, it simplifies the regex to:

`/(<(?:img|script|link|video|audio|source|track)\b[^>]*?\s)(?:src|href)\s*=\s*"(?:\.\.\/|\/)+([-IJ]\/[^"]*)"/ig`

However, if it is not a safe assumption, then we must use a backreference in the regex to determine the type of quotation that is encountered in `src="` or `href='`. So we can surround it with parentheses and remember it in the form `(["'])`. This creates a backreference that will either be `'` or `"` according to what was found. Backreferences have the form `\1` or `\2` (etc.) according to the backreference number in the regex. In our case, it would be `\2`, so, we would need to rewrite the regex as:

`/(<(?:img|script|link|video|audio|source|track)\b[^>]*?\s)(?:src|href)\s*=\s*(["'])(?:\.\.\/|\/)+([-IJ]\/(?:(?!\2).)*)\2/ig`

I think this is perhaps overcomplicated and unnecessary. Thoughts?

**Comment by mossroy** [comment]
I agree that it's surprising that this apostrophe is not escaped inside the ZIM file.
You should report that on mwoffliner : it' probably a bug they need to fix.

**Comment by kelson42** [comment]
@mossroy @Jaifroid If you have double quote for the HTML attribute value, then you don't need to escape the apostrophe IMO. It does not look like to me that the HTML is wrong here.
