### ISSUE TITLE
Update Ray Charles ZIM to latest

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#456]
The current Ray Charles in kiwix-js is very old (2015-06). The latest Ray Charles is currently `wikipedia_en_ray_charles_2018-10.zim`. I realize some of the tests depend on checking expected output from the old Ray Charles, so this probably isn't as straightforward as splitting the ZIM and substituting the new for the old. But given the updated CSS and other differences, it may be worth the effort. On the other hand, it could be worth waiting until https://github.com/openzim/mwoffliner/issues/395 has worked its way into a new Ray Charles ZIM.

**Comment by mossroy** [comment]
I agree.
I think a complicated part will be to find an article with a content split inside 2 different files (we have a test that checks that the backend works properly in this case)
And many tests will have to be re-written because they check the content itself.

**Comment by kelson42** [comment]
@Jaifroid @mossroy What should be done with that ticket, we produce new Ray Charles ZIM files https://download.kiwix.org/zim/wikipedia/

**Comment by mossroy** [comment]
@kelson42 : please read the previous comments.
All the unit and UI tests are based on the content, at a low-level for many of them. So it probably needs to rewrite/adapt them.

**Comment by kelson42** [comment]
@mossroy Yes, but this seems important the automated tests run against modern ZIM files. I wonder a bit this has not been done since 4 years.

**Comment by kelson42** [comment]
I still believe this ticket is hardly actionable. First checking splitted zim files seems not necessary anymore to me. Then « yes » the tests will probably have to be adapted each time a new version of the test zim file is used… but this is a pretty easy and straight forward operation.

**Comment by Jaifroid** [comment]
I think this is superseded by #718 and #748. I close, but feel free to re-open if it's not covered by those issues.
