### ISSUE TITLE
Support ogg media type in jQuery mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#460]
In line with SW mode, I should add ogg (and related) media type support in jQuery mode.

**Comment by kelson42** [comment]
@Jaifroid Do you still really want to see this feature implemented some time?

**Comment by Jaifroid** [comment]
@kelson42 What would you recommend? It's only for jQuery which means IE11, Windows Mobile, Firefox OS and old Firefox such as IceCat (which keeps one rather well-known user happy). It wouldn't be difficult, probably 30-minute fix (including testing, if I can find a ZIM useing the format).

**Comment by kelson42** [comment]
@Jaifroid I would respect the decision of freezing the JQuery reader…. and don’t implement it… or implement it right now (if this is so easy/quick).

**Comment by Jaifroid** [comment]
If I knew of a ZIM with this format, I'd implement it, because it's no different form supporting mp3. But I wouldn't feel comfortable implementing without being able to test it, so until I come across a case, I'm happy to close.
