### ISSUE TITLE
Change description about audio and video not being supported

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#468]
Quick note that before finalizing 2.5, it will be necessary to change the warning on the Config page that is highlighted in the screenshot below. It reads: "Audio/video/dynamic contents are not supported for now." I suggest changing to "Dynamic content is not fully supported."

![image](https://user-images.githubusercontent.com/4304337/51010071-8da9f600-154a-11e9-82e3-ef7249062635.png)

**Comment by mossroy** [comment]
I agree

**Comment by Jaifroid** [comment]
I think this could be added to PR #467, since that PR deals with dynamic content.

**Comment by mossroy** [comment]
It's fine to put that in PR #467 . The wording looks good

**Comment by Jaifroid** [comment]
Closed with #467.
