### ISSUE TITLE
Do new Wikipedia TOP selection ZIMs work fine with 2.5

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#471]
For example https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_2019-01.zim

**Comment by Jaifroid** [comment]
Seems to be working fine from a quick check:

![image](https://user-images.githubusercontent.com/4304337/51090609-38eac300-1776-11e9-9d34-d541fa55abfc.png)

**Comment by Jaifroid** [comment]
Also working well in Kiwix JS Windows:

![image](https://user-images.githubusercontent.com/4304337/51090628-a1d23b00-1776-11e9-9c90-622c10af800e.png)

**Comment by kelson42** [comment]
Thx :)

**Comment by mossroy** [comment]
@kelson42 : you can easily try by yourself with a nightly build.
I did not see any visible problem, but don't know what to check specifically.

For some reason, the order of images is different in jQuery and ServiceWorker mode.
The image for Michael Jackson is missing.

In ServiceWorker mode, there are some errors in the console (but they do not seem to be specific to the top selection) : 
![image](https://user-images.githubusercontent.com/890923/51090673-bff06900-177f-11e9-8b40-fb02ce25dfbb.png)

**Comment by Jaifroid** [comment]
He he, I note this selection has `Birmingham` but not `London` or `Paris`, and `e (mathematical constant)` but not `Pi`...
