### ISSUE TITLE
Test version 2.5.0 on Ubuntu Touch

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#473]
I've uploaded version 2.5.0 on the Ubuntu Touch store : could you please test it?

In particular, I'm wondering if the ServiceWorker mode is supported by this platform? It probably depends on the version of the underlying Chromium engine.

Could you test in particular : 
- some ZIM files that use javascript, like the ones in https://download.kiwix.org/zim/phet/
- some ZIM files with videos, like the ones in https://download.kiwix.org/zim/ted/
- https://download.kiwix.org/zim/ted/ted_en_global_issues_2018-07.zim , on "A call for men", to see if subtitles can be selected and displayed. In order to see if this platform is affected by #461

By the way, I could upload this 2.5.0 version (only the xenial channel was proposed), even if #375 is not implemented.

**Comment by ernesst** [comment]
@mossroy,
The ServiceWorker mode doens't work on the UTouch platform, I guess due the platform restrictions.
I've tried both file, I got a error msg "unable to display content" i guess due to ServiceWorker is not activated.

**Comment by ernesst** [comment]
UTouch platform is migrating the webbrowser, so I'll retry when significant update will be done on thier side.

**Comment by mossroy** [comment]
OK thanks for your tests.
And yes, it would be worth trying again if the browser engine is upgraded

**Comment by mossroy** [comment]
@ernesst : was the web browser of Ubuntu Touch migrated?
If so, could you please try again if ServiceWorker mode is now supported? (with the latest nightly build from https://download.kiwix.org/nightly/)
BTW, we'll probably release a version 2.6 very soon

**Comment by ernesst** [comment]
i'm currently on an unstable version of Utouch (Edge) and the kiwix apps seems to not work with it. i'll investigate.
Nope unfortunatly there is no new version of the webbrowser, developpers are focused to bring the graphic server to the mainstream packages supported by ubuntu.

**Comment by mossroy** [comment]
@ernesst : is there any error message?
Is it broken only for a specific version of the app, or for all of them?
Should it be a blocker for our release of version 2.6? (I don't think so)

**Comment by mossroy** [comment]
As we're releasing version 2.6, I'll close this issue and open a new one for 2.6
