### ISSUE TITLE
Enable extraction of self-contained HTML of page

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#482]
As per https://github.com/kiwix/kiwix-js-windows/issues/70#issuecomment-478219821, I'd like to try to backport this code to Kiwix JS. Technically this is surprisingly easy. It works by using a combination of XHR and the FileReader API to transform the image URLs to dataURIs (without reloading the images). The resulting HTML is then passed to our existing code for downloading EPUBs and PDFs. It should work in jQuery mode, and I cannot think of a reason why it would not work in SW mode, but that is untested (because Kiwix JS Windows cannot currently use SW).

**Comment by Jaifroid** [comment]
PR #483 Is an initial backport of the code. It is tested in Edge, Firefox ESR, Chromium in both jQuery and SW modes. If the user turns on the option in Config, it will insert a "breakout" link on newly loaded pages (see screenshot), and when clicked, it will convert the page to a standalone format (using dataURIs) and then offer to save / open the new html document.

Observations: 

* The functionality is off by default -- to test, turn it on in Config;
* The icon used is a temporary one, constructed from a Unicode arrow symbol. Later, I'd expect to use an image, maybe;
* The code isn't working in FFOS simulator, because the browser seems to navigate to a non-existent page. This doesn't happen in Firefox ESR, so I'm not sure what the issue is;
* The code works in both SW and jQuery modes;
* If this code is on, then, in jQuery mode, BLOBs are not destroyed as soon as they are read, but they will remain in memory until the next page is loaded. This is necessary to be able to read the image BLOBs when the user asks to download the page.

![image](https://user-images.githubusercontent.com/4304337/55279952-ec476a80-5316-11e9-8218-de7dc0331bb5.png)

**Comment by Jaifroid** [comment]
The code isn't working in Internet Explorer for the same reason as it isn't working in FFOS simulator, i.e., the browser tries to navigate to the href of the breakout link. The navigation isn't being cancelled by jQuery. This needs further investigation.

**Comment by Jaifroid** [comment]
So, it wasn't a case of the navigation not being cancelled in IE11 and FFOS. It was because XHR is being blocked from the file:// URL in IE11, and I believe it may be blocked in FFOS more generally, or at least blocked for reading blob URLs. By wrapping the offending line in the try catch statement, it's at least possible to download a text representation of the page, without images, in IE11, and probably in FFOS.

**Comment by Jaifroid** [comment]
It's now working in IE11, and apparently in FFOS (though I can't fully test, because the downloaded file won't open in the simulator).

**Comment by Jaifroid** [comment]
I've replaced the Unicode arrow with the SVG icon provided by Wikimedia, as in screenshot below.

![image](https://user-images.githubusercontent.com/4304337/55289328-28cda180-53bd-11e9-83c8-7dad036e3da4.png)

**Comment by mossroy** [comment]
Sorry if my answer might be frustrating, but I'm not sure it is worth implementing this in kiwix-js.

If I come back to the initial user request (having many tabs), I tested in ServiceWorker mode, and it already works out-of-the-box : if the user opens a link in a new browser tab (through the standard feature of the browser), it works. There is only the content in the new tab (not any menus or app UI), and the hyperlinks can still be followed. It's not perfect, but it works pretty well with the standard features of the browser (in SW mode).

So we're talking about a jQuery-mode-only feature, that adds a not-so-insignificant amount of code for a rare use-case.
My first impression is that it's not worth finalizing, optimizing and maintaining this code in kiwix-js. I'd prefer to save our time to work on issues like #116

**Comment by Jaifroid** [comment]
That's OK, @mossroy , it's been a useful exercise backporting because it allowed me to find several problems in the code and generally tidy things up / make them more generic. I can't use the SW mode (yet) in Kiwix JS Windows, which is why I had to develop the feature. If a user requests a specific feature that I think is sensible, then I prefer to prioritize such a feature, especially if it's one I've felt is needed (H have been frustrated a few times when using Kiwix JS Windows for research not to be able to keep a page open while navigating to another).

Regarding the "native" ability to open a new tab in SW mode, for some reason it's extremely slow in Edge, and following links is very slow too. Not sure why. 

I am happy to keep this as a feature only in Kiwix JS Windows.

**Comment by mossroy** [comment]
Thanks for your understanding @Jaifroid , it's a pleasure to work with you on this project.
