### ISSUE TITLE
Image map links are not parsed by parseAnchorsJQuery

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#484]
Image maps work in SW mode, but in jQuery mode, they lead to an errorpage in the browser, which is ugly to recover from. An example would be the mammal image map in `Mammal.html` in English Wikipedia.

It shouldn't be difficult to parse these hrefs which have the format:

`<area title="Tasmanian devil" href="Tasmanian_devil.html" shape="rect" coords="0,68,100,136" alt="Tasmanian devil">`

**Comment by mossroy** [comment]
Yes, it's also the case in the home page of some wikivoyage ZIM files (which have an image map of the earth).
It's probably easy to trap the click events on each area (in a generic way), and inject some javascript to replace the hyperlink, like we do with classical hyperlinks. See https://stackoverflow.com/questions/29921696/can-i-have-an-onclick-event-on-a-imagemap-area-element (but I did not test)
