### ISSUE TITLE
Use a flat model for resolving hyperlinks in jQuery mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#495]
This is a thought exercise provoked by the issues in #494. I am in two minds myself, but it occurs to me and I've tried it out in Kiwix JS Windows in a test branch.

I am beginning to wonder if we are making too much work for ourselves in trying to emulate what the browser does when resolving hyperlinks in jQuery mode. I suggest we consider reverting to a "flat" model, by which I mean that we don't forcibly try to situate the browser inside any subdirectories by using the `<base>` tag. Since we have to use JS anyway to resolve all ZIM links, we don't need the browser to calculate relative links for us. It is adding a lot of support work -- see #487, #346, #484 and generally the fact that we have to programme every anchor (e.g. `<a href="#main_topic" ...>`).

ISTM that we could simplify quite a lot if we just let the browser think it's in the location of `article.html`. ~~We know how to find a ZIM link and whether it is in the A namespace, and any other namespaces will be provided explicitly. All we need is the URL (and namespace if the link has one) with no relative links attached. It's exactly the same as what we do with images: the browser doesn't really add any useful information by adding on extra ../../../ when it's in a "subdirectory". We can throw all that away and extract the ZIM link directly from the arcihive.~~

In fact, I now realize that SW mode operates a flat model too, which is why #494 doesn't affect it. The code `titleWithNameSpace = nameSpace + '/' + title;` (line 163 of `service-worker.js`) throws away any relative link info and just asks the back end for that ZIM URL (e.g. `I/myImage.jpeg`). This caused me a lot of puzzling over why obviously incorrect relative links in `Singapore/Riverside` were working fine in SW mode. Shouldn't jQuery mode use the same principle?

~~**An important caveat:** On the other side of the argument, if we had already implemented this, then we would never have caught the errors in #494 . So there is a useful diagnostic element to doing things the way we currently do in jQuery mode.~~

**Comment by Jaifroid** [comment]
This has already been discussed at some length in https://github.com/kiwix/kiwix-js/pull/309 .

**Comment by Jaifroid** [comment]
The PR #496 is a generic alternative to using the base tag. It simplifies the proliferation of link handling that the base tag was causing. Contrary to my (incorrect) caveat above, this code maintains the diagnostic / reference status of Kiwix JS.

**Comment by mossroy** [comment]
If I understood correctly, the goal is to remove the `base` tag, in order to simplify the code?
It sounds like a good idea.
