### ISSUE TITLE
Apply use of dirEntry.getMimetype() throughout the code

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#500]
Now that we have merged #490 , we need to apply it throughout the code.

**Comment by Jaifroid** [comment]
It looks to me that we can apply the use of `dirEntry.getMimetype()` to Service Worker code by sending the derived MIME type along with the post message from `app.js`, as part of the message object. This should simplify quite a lot of code in `service-worker.js`.

Would you like me to tackle it, @mossroy , or do you prefer to do it?

**Comment by mossroy** [comment]
Yes, that's how I would have implemented it, too.
It would be great if you can do it, else I would implement it later.
