### ISSUE TITLE
After a search, choosing an article should remove the focus from the search field

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#503]
It's an issue on mobile platforms, where a virtual keyboard is displayed when the focus is on a search field.
When an article has been chosen, the user should be able to read it on the whole screen, without having to manually hide the keyboard.

**Comment by Jaifroid** [comment]
OK. This might be a simple addition to #501, if indeed the issue persists with that PR.

**Comment by mossroy** [comment]
This is not solved by #501 (at least for now).
There is another side effect (on desktop) : if you want to use the keyboard to navigate, you are unable to scroll the article page with pageUp/pageDown keys if the focus is in the search field

**Comment by Jaifroid** [comment]
I haven't yet addressed this in #501. Will take a look.
We can either add code to focus on the iframe after the search is dispatched, or we can add code that focuses when the iframe is about to be loaded (in both jQuery and SW modes). I'll see what works best.

**Comment by Jaifroid** [comment]
Please see commit https://github.com/kiwix/kiwix-js/commit/de04b239b600f00d92575c81378eedc20e9a57e1 . Code appears to be working in Edge on desktop, but I guess it needs testing on a real mobile device to be sure on-screen keyboard is removed. As far as navigation with physical keys goes, focusing on the contentWindow of the iframe, as I do here, makes the iframe navigable (at least on Edge, will test other browsers later).

But in principle, do you think this is the right place to do it for SW and jQuery modes?

**Comment by Jaifroid** [comment]
#501 now incorporates a fix for this issue (see final code, not the commit referenced above).

I have another, related question, though it may be a separate issue. Currently, we explicitly give focus to the search (prefix) field on launch of the landing page. For a user launching a file for the first time, this obscures the information/images on the landing page with the on-screen keyboard. However, I recognize that it is useful for the user who is launching a ZIM s/he is familiar with and wants to get on with searching straight away.

A solution might be to store the name of the last-used ZIM in a cookie, and focus the search field (on opening the landing page) only if the name of the new ZIM matches the name of the last-used ZIM. Is this of interest?

**Comment by Jaifroid** [comment]
Closed with #501.
