### ISSUE TITLE
Read QRpedia codes and display the corresponding article

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#51]
I find the idea of QRpedia very interesting : https://en.wikipedia.org/wiki/QRpedia
I think it would be worth implementing it for Evopedia.
It would make sense to be able to read these articles without internet access, when visiting as a tourist (in a foreign country for example)

**Comment by kelson42** [comment]
I maintain (DEV & OPS) for Wikimedia UK. What might be challenging is to find a tech solution to catch all http requests (encoded in the QRcode) pointing to qrwp.org (qrpedia URL). I'm also interested in this kind of technology mix, even if I think the crossover kiwix-plug/qrpedia might be more promising.

**Comment by mossroy** [comment]
In Firefox OS, QRcode decoding is not built-in : it is implemented in some applications available on the Marketplace. It also might be implemented in Evopedia/Kiwix application itself too.
Regarding "catching" the http requests, I think the thing we might do is to declare Evopedia/Kiwix application as a handler of such qrpedia URLs, with a WebActivity. See https://wiki.mozilla.org/WebAPI/WebActivities
In this case, when a QRCode application scans a QRpedia code, and tries to open it in a browser, it should propose the normal browser AND our application to open it.

(I did not understood what you mean about the crossover thing...)

**Comment by kelson42** [comment]
OK for the integrated QRcode reader. What I mean with a kiwix-plug/QRpedia crossover is that IMO what is even more interesting than having the content on the smartphones is to have it provided by a local WIFI hotspot. That way the users just come with their smartphones, they don't have internet, but can enjoy everything (all QRpedia QRcodes).

**Comment by Jaifroid** [comment]
@mossroy Is this issue one that you are still interested in implementing? If not, I would suggest closing it with wontfix. I looked into the technology a bit, but it didn't seem to have taken off. I may be wrong!

**Comment by mossroy** [comment]
It's clearly not a priority, and is probably not easy to implement.
But not sure it's really a wontfix yet.

**Comment by Jaifroid** [comment]
OK, no problem!

**Comment by kelson42** [comment]
@mossroy New ZIM files URL scheme should exactly the same as online for Wikipedia. Which means that we a simple routine we could transform a wikipedia.org URL to a ZIM URL. IMO, this feature could be relatively easily implemented now - assuming you can get the URL easily from the camera/QR code.

**Comment by Jaifroid** [comment]
I believe it is extremely unlikely this issue will ever be implemented. If someone wishes to, they may of course re-open.
