### ISSUE TITLE
Move https://download.kiwix.org/bin/browsers/ to https://download.kiwix.org/release/browsers/

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#516]
In an attempt to reorganise a bit the storage of our binaries on download.kiwix.org. I want to move the Kiwix-JS extensions aside the other releases at https://download.kiwix.org/release/. I will also implement an HTTP redirect from the old location to the new, so all deep links should continue to work. Would that be OK for you devs?

**Comment by mossroy** [comment]
The URL is mentioned in the README.md, where it can be easily replaced.
As long as there is a redirection from the old location, it's perfectly fine for me.

**Comment by mossroy** [comment]
I've created PR #518 for that
