### ISSUE TITLE
Question about non-app store release files

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#517]
I try to keep, whatever the Kiwix port, a non-app store downloadable file. For Kiwix JS Windows, this is here: https://download.kiwix.org/release/kiwix-js-windows/

I just remarked that I don't have maintained that properly and the last releases are not available here. Where can I download them? On the Github release page, we have the `.appxbundle` files but not sure this is the same as the `.appxupload` files?

**Comment by Jaifroid** [comment]
Hi @kelson42 , the .appxbundle is the one that is needed for installing outside the app store, i.e. what is given on the GitHub releases. An .appxupload is only used for uploading to the Microsoft Store, and is useless for someone who wants to install outside the store. So I think it's best you link to .appxbundle (or keep a copy of it).

**Comment by kelson42** [comment]
@Jaifroid Thx, I will do it :)
