### ISSUE TITLE
Service Worker iframe document should be loaded in Standards Mode, not Quirks Mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#522]
Currently, documents loaded into the iframe in Service Worker mode cause the browser to think it is running in "Quirks Mode", at least in Edge and Chromium. This is a potentially serious issue going forward because many scripts are not compatible or only partially compatible with Quirks Mode. This includes jQuery, but also many others we may encounter in unknown ZIM archives.

![image](https://user-images.githubusercontent.com/4304337/59977690-7462a680-95cc-11e9-9171-75abd057c219.png)

**Comment by Jaifroid** [comment]
This is almost certainly due to the lack of a DOCTYPE declaration: see https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode.

Typical iframe contents in SW mode - note, no DOCTYPE is visible:

![image](https://user-images.githubusercontent.com/4304337/59977823-d243be00-95cd-11e9-94ed-7003651056ed.png)

**Comment by Jaifroid** [comment]
Might be worth checking if https://stackoverflow.com/a/33419051/9727685 works.
An alternative is to revert to document.write(), which allows setting the docType, but risks regressions (we've been round the houses on that).

**Comment by mossroy** [comment]
It looks like something that should be handled by the ZIM writer.
If the doctype is not declared, it should put the document in quirks mode for any Kiwix implementation (Android, desktop etc).
If the ZIM file works properly on other kiwix implementations (with or without quirks mode), I don't see why it would not work in kiwix-js.
Maybe the features of jQuery used in this ZIM file are compatible with quirks mode : according to https://stackoverflow.com/questions/1500353/does-jquery-work-well-in-quirks-mode, this mode is not tested by the jQuery team, and some features don't work, but not all of them.
Did you notice some problems (except the error message)?

Don't get me wrong : it looks like a real issue that should be fixed. But it should probably be reported on mwoffliner.

NB : in SW mode, we can't use document.write() as the content is sent by the ServiceWorker

**Comment by Jaifroid** [comment]
You're right that there is no DOCTYPE declaration in the source html (see snapshot of what comes from the decompressor below). I agree it should be fixed in mwoffliner. Nevertheless, I'll also do a test to see whether adding a doctype (i.e. injecting one) would in fact fix the issue in SW mode, because if it doesn't, we may have to think again.

![image](https://user-images.githubusercontent.com/4304337/59981007-adfbd780-95f5-11e9-98d3-29c9bfa122ad.png)

**Comment by kelson42** [comment]
@Jaifroid @mossroy FYI this commit made a few days ago might be relevant here (not sure) https://github.com/openzim/mwoffliner/commit/7e51da5ccc16116200cf06314899bba7e688a5ad

**Comment by Jaifroid** [comment]
Ah, excellent @kelson42 , that looks like just what we were looking for!

**Comment by Jaifroid** [comment]
OK, after testing with a branch that experimentally injects a DOCTYPE in Service Worker mode, I can say that it looks like the mwoffliner commit will solve our issue. FYI the branch that has this is my caching branch: https://github.com/kiwix/kiwix-js/tree/Persist-cache-in-localStorage. Outcome in screenshot below. Note that JQMIGRATE no longer shows the error. NB, the doctype was injected as `<!DOCTYPE html>`, but Chromium shows `doctype` in lowercase in screenshot below (Edge shows it in upper case). It still activates Standards Mode.

![image](https://user-images.githubusercontent.com/4304337/59981776-6c245e80-9600-11e9-8134-93cbdd4b21d5.png)

**Comment by Jaifroid** [comment]
The only question that remains is whether we want to inject a DOCTYPE *if one is missing*, to make the many old ZIMs work in Standards Mode. It's not hard to do. What do you think, @mossroy ? If not, please feel free to close this issue.

**Comment by mossroy** [comment]
We should not try to fix broken ZIM files if they are.
And, in this case, it does not seem to a major problem.
I close this issue.
