### ISSUE TITLE
2.6.0 does not run properly on Ubuntu Touch

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#537]
At least in jQuery mode (if SW mode is still not available).
In this version of kiwix-js, the Ubuntu Touch platform has been upgraded to Xenial.

**Comment by ernesst** [comment]
Hello, 
Just to let know, that i'm working on it, So far I cannot idenfied the pattern anabling the app to work sometime ... (i'm testing with the last daily built)

**Comment by kelson42** [comment]
Just have read https://medium.com/@probonopd/ubuntu-touch-reports-of-its-death-have-been-greatly-exaggerated-8517f8984b77 and was just about re-tweeting it and writing that "of course" Kiwix does support it... and then remember that ticket. @ernesst any news?

**Comment by ernesst** [comment]
Yes and no, 
No because I couldn't find the issue...
Yes because I had to move back from Edge to Devel ubuntu touch version thus getting less exotic version... which works with Kiwix 2.7  and looks greater than the previous version. 
![image](https://user-images.githubusercontent.com/11337464/69117832-a599b280-0a56-11ea-86da-6ee8a798325b.png)
![image](https://user-images.githubusercontent.com/11337464/69117849-b4806500-0a56-11ea-8328-8997ff7d689b.png)

The zim used to test was ubuntu fr 450mo, i'll try with giga size... that i'm worried my phone will not being able to handle, i'll give a shot.

**Comment by kelson42** [comment]
@ernesst Thank you for having tested again. I’m not sure I fully understand your last comment... but it seems we could close this ticket? You confirm?

**Comment by mossroy** [comment]
@ernesst : I did not see a conclusion for this ticket.

Could you test a recent nightly (from https://download.kiwix.org/nightly/) on your Ubuntu Touch device?
And let us know if we can release version 2.7 on https://open-store.io ?
Based on the statistics on open-store, version 2.6 has been downloaded 199 times, but we don't have more feedback than that.

Regarding the "devel" and "edge" versions of ubuntu touch, please let us know if there is something we could do to target only the versions where kiwix is working fine?

**Comment by ernesst** [comment]
Hello, 
I've tested the 03-16 version, it works well.

What I've try to mean between devel and edge version is that edge has lot of unstable package and the issue that i've found previously might have come from that. 

You can push this version to the store. 

As you suggested once, currently we don't have serviceworker enable, I suggest you to make a detailed request to the browser repo : https://github.com/ubports/morph-browser (as I'm not familiar with this technology)

**Comment by mossroy** [comment]
Thanks, that's good news : kiwix-js still works fine on Ubuntu Touch (in jQuery mode for now), so I'll close this issue.

**Comment by mossroy** [comment]
@ernesst : could you tell us which API status you get (with Ubuntu Touch) in the "configure" section about ServiceWorkers?
Do you have a "ServiceWorker API unavailable" or "ServiceWorker API available, but not registered"?
If it's "ServiceWorker API available, but not registered", could you give us the error message(s) you probably get in the browser console?

I need this information to make a proper request for the ubuntu touch browser

**Comment by ernesst** [comment]
Just to let you know that I working on your request... trying to figure out how to get these information

**Comment by mossroy** [comment]
@ernesst : to get the API status, you only need to start the app on your device, go to the "Configure" section and scroll down
