### ISSUE TITLE
Update deployment on kiwix.github.io and change to https

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#540]
The deployment at http://kiwix.github.io/kiwix-js/www/index.html is still http:// and as a result, it's not possible to run it in Service Worker mode. The link to the deployment simply needs to be changed to https:// (the deployment can be run by manually changing the protocol to https:// in the browser).

Additionally, I'm not sure whether the deployment updates automatically with the new version 2.6 (after a nightly, for example), but if not, the deployment needs to be updated to 2.6.

**Comment by mossroy** [comment]
The deployment on github pages is a manual step : I just did it.
Which http link to github.io are you mentioning? I did not find it in the source.

**Comment by Jaifroid** [comment]
It's the link from the "View deployment" button on https://github.com/kiwix/kiwix-js/deployments :

![image](https://user-images.githubusercontent.com/4304337/61608704-9db63700-ac4b-11e9-9e9f-3a71c6861cd7.png)

**Comment by kelson42** [comment]
Sounds to be Github itself which decides about that URL to be HTTP

**Comment by mossroy** [comment]
I have checked the https option in the settings (see https://help.github.com/en/articles/securing-your-github-pages-site-with-https), which should automatically redirect all http traffic to https, and seems to solve this issue
