### ISSUE TITLE
Can Kiwix-JS run on e-readers?

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#542]
Am asking here because the user specifically mentioned Kiwix-JS, but basically he's got an e-reader and wanted to run Kiwix-JS on it.
Is this possible or should I send him to another repo?

**Comment by Jaifroid** [comment]
@Popolechien , it would depend entirely on the browser in the e-reader. If it's a relatively recent Chrome / Firefox and can run extensions, then it should be possible. If it's a more basic html5 browser, and the e-reader has a file system, it would depend on whether the security settings allow running files from the file system in the browser. So, lots of variables. The user would need to experiment. As a first step, they should see whether Chrome or Firefox can be run on the e-reader, and if so, they should try to install the Kiwix JS extension.

**Comment by kelson42** [comment]
@Popolechien The question can not be properly answered with "yes" or "no" without know the model of the e-reader, because "it depends".
