### ISSUE TITLE
Question about / modification to privacy policy

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#548]
I find myself wondering whether, as a result of JavaScript running in Service Worker mode, we need a more explicit Privacy Policy. Currently we say:

> This application works offline. We do not collect any of your personal data and don't even know what you are doing with this application.
> Anyway, if you think your Internet access can be watched and/or if you are paranoid, you should shut down your 3G and Wifi access before using the application. This application only reads the archive files of your device : it does not read any other files.

While I think the above statements are true, scripts embedded in ZIM files could "collect [some] of your personal data" (e.g. browsing history), no? And they could contact a server (e.g. Google). Is this something we should warn against hypothetically, or are there guarantees in the production of all conceivable ZIM files that no "phone home" script, however "innocent", might be embedded? Sorry if this question is a bit paranoid, but I'm currently reading a book _The Age of Surveillance Capitalism_ (very good, I recommend it).

If you agree we should expand our statement, I would be happy to re-draft it. Alternatively, we could look into a technological block in line with #98, to capture any FETCH event to an external server, and filter it according to a global block in the UI.

**Comment by mossroy** [comment]
You're right. And I think I noticed that some old PhEt files make some calls to Google Analytics (in SW mode, where javascript is enabled).
This might be discussed with @kelson42 because I think it's not desirable that ZIM files contain such external calls. It's probably easy to remove them when creating the ZIM file (and maybe it's already done in recent versions), but I'm wondering if this could be a general rule, and ideally enforced by ZIM generators in some way.
#98 might be implemented in SW mode, but it would probably block external links too : this could be sometimes annoying, but would ensure no external calls are made.

In any case, I agree with you that this statement should now be rephrased

**Comment by Jaifroid** [comment]
Suggested rewrite below. I think it would be useful to implement #98, because it would simplify the statement below. We could then say that "by default" the app blocks any external Internet access unless the user explicitly allows it. Regarding external links (http hyperlinks), we could capture those in both SW and jQuery mode, and ask the user if they wish to visit an external server (yes/no). Most people are familiar with this, because in phone apps it's normal to be asked something like "This app is attempting to open an external site, do you wish to continue?" But I agree that guidance from @kelson42 would be very welcome! 

> Short answer:
> 
> This application works offline, and does not collect or record any of your personal data. It only remembers your browsing history for the duration of a session (for the purpose of returning to previously viewed pages). This history is lost on exiting the app and is not recorded in any way.
> 
> Longer answer:
> 
> This application only reads the archive files that you explicitly select on your device: it is not capable of reading any other files. Some ZIM archives contain active content (scripts) which may, in certain circumstances, attempt to contact external servers for incidental files such as fonts. If you believe your Internet access is insecure, or is being observed or censored, we recommend that you completely shut down your Internet (Data or WiFi) access before using the application.

**Comment by Jaifroid** [comment]
I think we need also to add this:

> Additionally, if you obtained this app from a vendor Store (including extensions), then the Store operator may track your usage of the app (e.g. download, install, uninstall, date and number of sessions) for the purpose of providing anonymous, aggregate usage statistics to developers. You should check the relevant Store privacy policy for further information.

**Comment by Jaifroid** [comment]
I guess a well-crafted CSP together with CORS should prevent scripts/fonts/assets accessing external sites? In browser context I believe this is already the case (I've seen console messages about fonts being blocked due to CORS), but not necessarily in other contexts unless the CSPs are watertight. However, I'm no expert, just going on observed behaviour.

**Comment by Jaifroid** [comment]
Closing due to merging of #571.
