### ISSUE TITLE
Make the application available on other devices

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#56]
As it written in HTML5/javascript, it should be very portable on recent browsers.

The main issue is the access to the archive files.
Having the user select them manually at each startup is not acceptable, except for testing.

Currently, the application detects if the API DeviceStorage is available. It it is, it uses it to browse the SD-card of the device for archives. For now, this API is only available on Firefox OS devices, but ... :
- the DeviceStorage API is to be ported on Firefox for Android, and on Firefox desktop. See https://wiki.mozilla.org/index.php?title=WebAPI
- a similar API seems to exist in Phonegap/Cordova : http://docs.phonegap.com/en/3.0.0/cordova_file_file.md.html#File . This would theorically enable porting this app to iOS and Android, but also Windows Phone and Blackberry
- The FileSystem API might also be used instead of DeviceStorage, when available. It is only implemented by Chrome for now, but has been proposed to W3C too : http://dev.w3.org/2009/dap/file-system/file-dir-sys.html . Note that it is sandboxed : you can not access standard directories with this API, and only the applicaiton itself can read/write in it.

**Comment by Jaifroid** [comment]
I think this issue could probably be closed now. There is quite a lot of diversity either of Kiwix JS directly (web extensions, Ubuntu), or of ports to other app platforms (obviously Kiwix JS Windows).  If anyone is still interested in reviving the Cordova APIs that were removed in an earlier version (I understand), there is a separate issue #287 for that. The FileSystem API is dead (only Chrome supports it and no other browsers plan to). ….

**Comment by mossroy** [comment]
I agree
