### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-js#560]
In order to support the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your reader:

* is feeding itself from the OPDS stream (using a local cache/copy or not)
* is using the lastest libkiwix (not released ATM). It supports new options and includes the backward-ompatibility bits you'd need.
* is using the [centralized Categories List](https://github.com/kiwix/kiwix-tools/issues/317)
* is using the new tags only for flavours and full-text index.

**NOTE**: This issue for planning purposes, OPDS and libkiwix **does not support** those features at the moment.

**Comment by Jaifroid** [comment]
I'm just going through old issues. Is this still relevant? Libkiwix hasn't been ported to Emscripten, so I'm not sure Kiwix JS can use these features other than on an ad hoc basis internally. In any case, Kiwix JS doesn't have in-app ZIM archive download. I'm closing, but please re-open if there is anything we can or should be doing on this front.

**Comment by rgaudin** [comment]
👍
