### ISSUE TITLE
There is a vertical scrollbar since bootstrap 4

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#566]
It did not show up in previous versions.

I'm not talking about a vertical scrollbar inside the iframe (which is normal), but one on the whole window.
It appears on both Firefox and Chromium.

**Comment by Jaifroid** [comment]
Interesting. It doesn't appear on Edge (classic). However, it's easy to fix.

**Comment by ab1nash** [comment]
I think I have a simple fix for this.
