### ISSUE TITLE
Travis broken with "An error occurred while retrieving a new session"

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#573]
@mossroy I wonder if you'd be able to cast your experienced eye over this very short Travis session:

https://travis-ci.org/kiwix/kiwix-js/builds/606027422?utm_source=github_status&utm_medium=notification 

You'll see there that with all the browsers we're getting the error "An error occurred while retrieving a new session", suggesting something fundamental is broken in Travis. This has occurred consistently on the new PR, and it's clearly not related to the code submitted in the PR...

**Comment by mossroy** [comment]
It might be a limitation on PRs coming from a forked repository.
I remember that there was such a limitation in the way I plugged travis with Sauce and nightwatch (not 100% sure).
At that time, it seems to me that there was no better way to do it, but maybe things have improved in between

**Comment by mossroy** [comment]
See #351

**Comment by Jaifroid** [comment]
@mossroy OK, thanks for the explanation! In that case, I'll do a test submit of the same code (when we have an accepted solution) on a dummy branch to run auto tests before merging.

**Comment by kelson42** [comment]
@Jaifroid I strongly suspect @mossroy is right. It would be interesting to see if new Github actions would allow us to solve this strong inconvenient for external contributors https://github.com/features/actions

**Comment by Jaifroid** [comment]
Thanks @kelson42 , I'll take a look at those Actions. They look interesting.

**Comment by kelson42** [comment]
@mossroy @jaiffroid We are moving our CI to github actions for better UX, faster CI and more supported platforms. Most of our repos have it done and devs are happy about it. Would you consider to do that move as well? This might help to fix that ticket!

**Comment by kelson42** [comment]
@mossroy @jaiffroid We are moving our CI to github actions for better UX, faster CI and more supported platforms. Most of our repos have it done and devs are happy about it. Would you consider to do that move as well? This might help to fix that ticket!

**Comment by Jaifroid** [comment]
@kelson42 It sounds good to have an automation system directly inside GitHub. It seems it's a somewhat different syntax, just looking at, e.g., https://javalin.io/blog/moving-a-jvm-project-from-travis-to-github-actions but has a lot of advantages. But I have no experience, yet, of setting up CI, so I'll defer to @mossroy on the viability.

**Comment by mossroy** [comment]
I've created #590 to evaluate switching from Travis to GitHub Actions

**Comment by mossroy** [comment]
I close this issue because I think i can not be solved with Travis.
IMHO, the solution is to switch to another Continuous Integration solution (like GitHub Actions)
