### ISSUE TITLE
Update deprecated Promise patterns and methods

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#588]
We have a number of non-spec-compliant deprecated Promise patterns and methods in the code. For example, `.fail()` is used instead of the ES6-compliant `.catch()` (no reason for this as the latter is fully supported by Q). We also have a few cases of the [`.defer` anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern). Correcting/re-factoring these will enable an easier transition to ES6, for example if/when we implement #554 .

**Comment by mossroy** [comment]
Good idea, and I suppose it's not risky

**Comment by kelson42** [comment]
@Jaifroid Should we close this ticket?

**Comment by Jaifroid** [comment]
Yes!
