### ISSUE TITLE
IE11 "freezes" (for several seconds) when loading large pages from latest WikiMed

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#594]
I thought this was a problem with #589 (Promise refactoring), but it turns out to occur on Master as well. When loading pages with a number of stylesheets from `wikipedia_en_medicine_maxi_2020-02.zim`, IE11 freezes for several seconds during the loading process. Even the UI spinner is frozen (it is a CSS spinner), which perhaps implies that at a very low level it is trawling through many stylesheet rules and getting clogged.

The same page loaded from `wikipedia_en_all_novid_2018-06.zim` loads much faster, with no freezes, even though the pages seem to be substantially the same.

Steps to reproduce:

* Load IE11 from index.html (I have tested this from the file system);
* Pick `wikipedia_en_medicine_maxi_2020-02.zim`
* Search for `Hepatitis A` and launch.

For comparison, search for the same page in `wikipedia_en_all_novid_2018-06.zim` or `wikipedia_en_all_novid_2018-10.zim`. At least in the former, there is no delay and no freeze.

Maybe we shouldn't care much about IE11 any more, but there are few options available for people with old machines now that the Desktop application is compiled only for 64 bit.

**Comment by kelson42** [comment]
@Jaifroid Not sure, this is still officially supported by Microsoft.

**Comment by Jaifroid** [comment]
@kelson42  IE11 is still "supported" in the sense that it is still packaged with Windows 10 mainly because businesses still use it for old software that has Active X proprietary technology. We took a decision to continue testing with IE11 because it is the only browser guaranteed to be available without further download in a Windows XP/Vista/7 machine, and those users (I guess mainly in Global South) have few options left for running Kiwix on 32-bit machines. But it's just a guess as to whether it's still worth supporting. It's not "too" hard to continue to do so, but I think once we achieve #554 (npm-webpack) it might be the time to drop it...

**Comment by Jaifroid** [comment]
This issue was fixed by #630.
