### ISSUE TITLE
Update application logo

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#604]
There is a new, slightly remodeled logo for Kiwix 
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.png
The app's icon needs to be updated accordingly

**Comment by ykabusalah** [comment]
Can I try this?

**Comment by Jaifroid** [comment]
@ykabusalah Yes, please do have a go.

**Comment by ykabusalah** [comment]
I have submitted a solution for this through #607 .

**Comment by FalakZ** [comment]
@Jaifroid Hello, I tried making a new logo for KIWIX .


![logo](https://user-images.githubusercontent.com/46991207/77821359-c0b8b500-710f-11ea-8306-a77d789a1a49.png)

**Comment by FalakZ** [comment]
Hello @Jaifroid ,
I created a logo for kiwix. Can you check it out.


![ff37d763-33ca-46ed-a412-ab119debc5ac_200x200](https://user-images.githubusercontent.com/46991207/77821833-3b370400-7113-11ea-8342-0df9e987ab0c.png)

**Comment by Jaifroid** [comment]
@FalakZ Nice! But I'm just a dev. I don't know if Kiwix Association is interested in a new logo, given that they have their own logos with wide recognition. Pinging @kelson42 in case Kiwix Association might be interested.

**Comment by Popolechien** [comment]
@FalakZ Hi, thank you very much but we already have an updated version as indicated in the first issue comment - we are just making sure it's consistent across all apps (see [here ](https://github.com/kiwix/kiwix-android/issues/1943) and [here](https://github.com/kiwix/kiwix-desktop/issues/388)). Maybe I should have been a little clearer, sorry about that.

**Comment by mossroy** [comment]
Implemented by #608
