### ISSUE TITLE
I want to contribute to kiwix butHow to set up this project on localhost in windows 10?

### ISSUE THREAD

**Issue by fabcoder547** [kiwix/kiwix-js#622]

**Comment by Jaifroid** [comment]
Hi @fabcoder547 you need to have a local web server / development stack. You could try Express - http://expressjs.com/ . Note that we haven't built Kiwix JS with Node / Webpack etc. It really is just plain html5 and javascript, so just use what you would normally use to develop those. It is possible to run Kiwix JS from file:// in Firefox, IE11 and old Edge, but not any more in Chrome I think, but note that Service Worker mode doesn't work from file://.

**Comment by fabcoder547** [comment]
@Jaifroid that means i just have to clone it and run index.htmk right?

**Comment by Jaifroid** [comment]
Yes, clone with git / github desktop or whatever you use, and then you can launch index.html from localhost (ideally) if you have a local Web server running, or else you can launch it from file:// protocol in the mentioned browsers (there may be an extra step required to unblock file access in Firefox).

**Comment by Jaifroid** [comment]
I assume this query is resolved, but if not please re-open and comment further.
