### ISSUE TITLE
Urdu rendering problem in Firefox Extension

### ISSUE THREAD

**Issue by xehroz** [kiwix/kiwix-js#623]
I have noticed a text rendering problem for Urdu language, i.e. besides the fact, that all necessary Fonts (Nastaliq & Naskh) were already installed in the OS, it was not possible/visible to see the text in proper font. May be this is the issue with CSS or something else.

FYI i have attached a screenshot, please note that this was on a 64-bit Fedora 32 and Firefox 77.0.1 without access to internet.

![KIWIX-FIREFOX-EXTENSION-FONT-RENDERING-PROBLEM-FOR-URDU-PK-ON-FEDORA-32Screenshot at 2020-06-14 21-26-20](https://user-images.githubusercontent.com/44346427/84616340-27ff2d80-aee5-11ea-9881-921fb8a37bd6.png)

When i tried to access the wiki through internet on a Windows 7 32-bit PC with Firefox 77.0.1 and same fonts installed i was able to get the proper text rendering.

![windows-7-32-bit-with-internet-firefox-77 0 1](https://user-images.githubusercontent.com/44346427/84616846-87aa0880-aee6-11ea-97af-f462295caeb7.png)

It is requested to look into this and counsel me way forward.

Shehroz
Email: me@shehroz.pk

**Comment by Jaifroid** [comment]
@xehroz Thank you for this report. As I don't read Urdu, could you kindly pinpoint exactly what is wrong here? I am seeing some script in your first screenshot, but I have no idea what is correct and what is incorrect. Is it using the wrong font? Is it missing just some characters? Or is it the fact that the first screenshot is missing the warning/info boxes that are in the online version?

**Comment by xehroz** [comment]
The problem is with the font in the body of paragraph, this is using a wrong font to render. FYI it is an Asian RTL Arabic/Persian like font called Nasta' Liq which is used to properly display (or render) the text in the paragraph. (i.e. Nasta'Liq have proper ligatures & glyph to render the text correctly) But i guess Kiwix was not able to load this.

FYI i am attaching a modified screenshot to point you to towards proper rendering. 

![proper-rendering-with-nastaliq](https://user-images.githubusercontent.com/44346427/84623390-9994a700-aef8-11ea-819c-d1e2e271e12b.png)

Where as font used by default, is not capable of to render the Urdu ligature & glyph. It looks fuzzy & odd. 

See 
![odd-text-rendering](https://user-images.githubusercontent.com/44346427/84623641-2475a180-aef9-11ea-925f-dcd05e58331e.png)

The missing warning/info boxes are of no concern, because the ZIM i use don't have those elements (That is not a Problem, i am definitely OK with that.)

**Comment by Jaifroid** [comment]
OK, yes that does look like a CSS issue. The problem may be upstream in mwoffliner (the scraping system), because Kiwix JS doesn't change any font info. I suspect mwoffliner is not picking up all the CSS from Wikipedia. It would be good to pinpoint the specific rule that makes the difference. Do you know how to check for that using dev tools? If not, don't worry, I can have a look mid-week.

**Comment by xehroz** [comment]
Yes this is the issue with mwoffliner :-)

I've verified this, it has nothing to do with Kiwix

**Closing the issue now**

Thanks @Jaifroid for help +1:

**Comment by kelson42** [comment]
@xehroz We should handle that in MWoffliner. Moving the ticket.
