### ISSUE TITLE
[REGRESSION?] Black baground at the footer of tiles based welcome page

### ISSUE THREAD

**Issue by Ubuntu-2020** [kiwix/kiwix-js#641]
The title pages of some ZIM files are not displayed correctly in web browser extensions. Here are some examples:
**wikipedia_ru_history_maxi_2020-05.zim**
![wikipedia_ru_history_maxi_2020-05 zim](https://user-images.githubusercontent.com/65112331/86588591-a9058e00-bf94-11ea-8f49-dc3e9ecb8950.png)

**wikipedia_ru_football_maxi_2020-04.zim**
![wikipedia_ru_football_maxi_2020-04 zim](https://user-images.githubusercontent.com/65112331/86588583-a4d97080-bf94-11ea-85d0-1b52c1af6737.png)

**wikipedia_ru_movies_maxi_2020-05.zim**
![Kiwix 2 7 0 extension for web browser Vivaldi-ru_movies_maxi_2020-05](https://user-images.githubusercontent.com/65112331/86588499-7e1b3a00-bf94-11ea-9bdb-70b387a97c7a.png)

In other words, you can't scroll the main page with pictures down in the browser! There is a huge black area at the bottom.
Images were taken in the Mozilla FireFox web browser.

**Comment by kelson42** [comment]
@mossroy @Jaifroid Tested `wikipedia_ru_football_maxi_2020-06.zim` with Kiwix JS for Firefox 2.8 and I can not scroll to the bottom of the welcome page anymore. I'm somehow stuck at the top without any scrollbar. I don't have this problem for example with Kiwix Desktop 2.0.

**Comment by Jaifroid** [comment]
Thank you for the report. This is the same issue as #552. The current workaround is to switch to Service Worker mode if that is available (may only be available in extension contexts or app contexts, because it requires https:// in browser context). The problem seems to be caused by late injection of CSS (which is done by jQuery in jQuery mode).

**Comment by Jaifroid** [comment]
NB this isn't a regression caused by 2.8, it's been there since the new landing pages started appearing.

**Comment by kelson42** [comment]
@Jaifroid Sorry, I had totally forgotten about that one.

**Comment by kelson42** [comment]
Duplicate #641
