### ISSUE TITLE
Images lazy loading

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#646]
Would this help if we would start to use image lazy loading in ZIM files?
https://web.dev/native-lazy-loading/

**Comment by Jaifroid** [comment]
Indeed it would help in Service Worker mode. I did implement custom lazy loading for both jQuery and SW modes for kiwix-js-windows (where it is merged and working) , and a candidate version for kiwix-js, but in the end it was felt better to await a browser - level solution like this. Only slight issue is it wouldn't work in jQuery mode.

**Comment by kelson42** [comment]
I have created a ticket at MWoffliner level, https://github.com/openzim/mwoffliner/issues/1264. Closing this one. Thank you for the answer.
