### ISSUE TITLE
Improve layout of articles

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#65]
Suggested by a Chinese user : 
in order to replace this layout :
![narrow](https://f.cloud.github.com/assets/890923/1831455/7a0477e4-7390-11e3-9227-c13cd5aea627.png)

by this one :
![wide](https://f.cloud.github.com/assets/890923/1831457/a06f0f02-7390-11e3-849a-1c591258b36d.png)

He suggests to add this CSS :

body {
  font-family: "Feura Sans","Microsoft JhengHei","Helvetica Neue", Helvetica, Arial, sans-serif;
}
h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6 {
  font-family: "Feura Sans","Microsoft JhengHei","Helvetica Neue", Helvetica, Arial, sans-serif;
}
tright{
border-width:0 !important;
float:none !important
}
thumbinner{
width:100% !important;
}
dd{
margin-left:0em !important;
}
table,.pp_warningbox{
float:none !important;
width:100% !important;
margin-left:0em !important;
margin-right:0em !important;
}
# articleContent div.thumbinner{

padding:0 !important;
}
# quickbar{

float:none !important;
margin-left:0em !important;
margin-right:0em !important;
}
# navigationButtons a{

padding-top:0.3em !important;
padding-bottom:0em !important;
}
# navigationButtons a span{

font-size:1.6em;
}

**Comment by kelson42** [comment]
This is a feature request for the content, not for the reader. An other point concerning the UI layout, the "software label" (currently "Evopedia 2.0-kiwix-WIP") should be on the right (for LTR languages) and not on the left.

**Comment by mossroy** [comment]
For an Evopedia archive, it would have been implemented in Evopedia itself.
For a ZIM archive, if we want to keep no wikimedia-specific code in the client, it has indeed to be implemented in the content. That would mean a specific ZIM file. In this case, #34 should be implemented in this file too. Maybe it would be worth having such small-screen optimized archives.

Regarding the "software label", why should it be aligned on the right? It's certainly easily do-able technically, but I don't see the goal.

**Comment by kelson42** [comment]
I will try soon to make offline versions of the mobile version of Wikipedia.

**Comment by kelson42** [comment]
@mossroy @Jaifroid We don't really control the layout of the content. In addition, things have seriously evolved since 2014-2015. I think this ticket needs to be re-evaluated/closed/moved to mwoffliner if a bug is obvious.

**Comment by Jaifroid** [comment]
If mobile is now the default style for Wikimedia ZIMs, then I think this issue can be closed, because the mobile style implements what the user wanted. I think Wikipedia English ZIM is still issued in Desktop style, presumably because it's not practical to use on most mobiles due to storage space requirement and difficulty in downloading the ZIM?

**Comment by kelson42** [comment]
@Jaifroid Current strategy get mobile layout if possible. As a result all Wikipedia and Wikivoyage are now (if newly generated) with a mobile layout.

**Comment by Jaifroid** [comment]
OK, then I close this issue.
