### ISSUE TITLE
Add support of ZIM without namespaces

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#684]
First test ZIM files have been created and are available at:
http://tmp.kiwix.org/nons_zims/

Almost all Kiwix ports work with them so far, but not Kiwix-JS unfortunately.

**Comment by Jaifroid** [comment]
You do like to keep us busy @kelson42 😉
I think I recently noticed at least one hard-coded A/ namespace, and probably specifically around binary search, which would explain the issue here.

**Comment by Jaifroid** [comment]
@kelson42 We have #597 for this issue, so I'm closing here but will copy your comment with location of files there.
