### ISSUE TITLE
Chrome Sync seems mandatory to get Kiwix JS working

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#693]
I use Chromium `87.0.4280.88 (Official Build) snap (64-bit)` and I fail to get Kiwix JS 3.1.0 icon display properlyws in my toolbar beside the other extensions. The installation from the Chrome store works fine, then it asks about "Sync", I just close the dialog as I don't want to use Sync and then the Kiwix icon disappears for always from the toolbar. The Kiwix JS extension seems properly installed and is listed as installed extensions but I have no way to make the Kiwix icon visible and therefore to use the extension.

Do I'm the only one with this problem?

**Comment by mossroy** [comment]
I use the exact same Chromium version on Ubuntu 20.04 (the default snap) and do not have this issue.
I already had the plugin installed (from the Chrome store) : it has been upgraded to 3.1.0, the icon is visible and kiwix-js works as expected. It does not ask about Sync

**Comment by kelson42** [comment]
@mossroy Thx for the feedback. Pribably a pb on my end then.
