### ISSUE TITLE
Allow to get more suggestions

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#696]
If the 25 first suggestions are not enough it would good to be able to continue to surf over the next suggestion batch. First suggested by RMS

**Comment by Jaifroid** [comment]
@kelson42 In the UI (Configuration) there is a slider by which users can set the number of search results from a minimum of 5 to a maximum of 50, with a default of 25. We could increase the maximum to 100, but I'm not sure how useful 100 results are compared to refining ones search.

**Comment by kelson42** [comment]
Ideally this should just expand on demand without any limit.

**Comment by mossroy** [comment]
> First suggested by RMS

RMS = https://en.wikipedia.org/wiki/Richard_Stallman? 
I know he refuses to have a github account (which looks logical) : where would be his complete feedback?

**Comment by Jaifroid** [comment]
Logical that RMS would use Kiwix!

A quick fix could be to change the slider to allow 10-100.

Another fix would be to have a "Next" link at the bottom of the results that would load the next X results. I have something like this in KJSW (see screenshots below) so users can access articles on ZIMs that use a proprietary dynamic UI, where it is important to be able to "browse" the index (e.g. Gutenberg).

A more complete fix that I think @kelson42 is referring to would be a "perpetual scroll", which would load more results as you scroll.

![image](https://user-images.githubusercontent.com/4304337/105580423-2e5f5d00-5d84-11eb-8bf3-d5ab97a4a9da.png)

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

![image](https://user-images.githubusercontent.com/4304337/105580412-1982c980-5d84-11eb-84f7-8cf83d1cceef.png)

**Comment by Jaifroid** [comment]
Optimization suggestions from RMS:

> * When a list of matches has been found, and the user enters another 
> character, don't search the database afresh.  Instead, look at the 
> list of matches and keep whichever ones match with the new character. 
> This should be MUCH faster. 
> 
> * If the earlier (longer) list of matches has been displayed in its 
> entirety, don't rebuild the display from the new (shorter) list; 
> rather, delete from the DOM he matches that should no longer be 
> present. 
> 
> * Cache the list of matches for each prefix, IF there was a chance to 
> finish searching for that prefix.  If the user ever gets back to that 
> prefix, use the cached list of matches. 
> 
> How long to keep these matches is up to you.  I guess it depends 
> on how much space they take up. 
> 
> * Define some keyboard input to mean "delete the characters at the end 
> that can't match anything."  Is there a quick way to test whether 
> a prefix has at least one match?  If so, this command should be fast 
> enough to be worth implementing.
