### ISSUE TITLE
Add tests on reference version of no-namespace Ray Charles with ZSTD compression

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#718]
This issue supersedes #651. As soon as we have a reference no-namespace version of Ray Charles, we should beging to add tests that are specific to both a no-ns version and to ZSTD compression.

**Comment by kelson42** [comment]
@Jaifroid This will take a bit, because we need first to (1) release libzim7 (2) Update + release node-libzim (3) Adapt + Release MWoffliner (4) Publish a new ZIM file. All of this might take around 3 months.
