### ISSUE TITLE
REGRESSION: random button no longer truly random

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#720]
Due to the changes implemented to support v1 title indices, the random button appears no longer to be random. This is best observed on a small Wikipedia ZIM such as `wikipedia_en_100_maxi_2021-03`. The random buttom predominantly picks articles towards the end of the alphabet, often repeating the same three articles in succession, as if caught in a loop.

I *believe* this may be caused by picking the article from the full pool of entries in the v0 index, and then filtering for those that are articles. This will cause the random function to be selecting from a much larger pool of articles than are actually in the article index. This will tend to skew the random result probabilistically towards larger numbers, and hence will tend to pick articles weighted towards the end of the range of actual articles.

This should not be difficult to fix.

**Comment by mossroy** [comment]
Nice catch!
