### ISSUE TITLE
Missing image in custom Wikipedia ZIM

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#730]
When generating a test zim file from https://farm.openzim.org/recipes/wikipedia_en_for_schools the corresponding zim file seems to have missed an image.
I ran the recipe twice, and the same image (https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_for_Schools/Welcome/Mathematics#/media/File:Fisher_iris_versicolor_sepalwidth.png) is always missing:
![Capture d’écran 2021-06-08 à 14 55 48](https://user-images.githubusercontent.com/21675885/121188743-af1d8200-c869-11eb-9a22-62fbf9170499.png)

Same issue appears on [Android](../../kiwix-android/issues/2664), but not on Kiwix-Serve

**Comment by kelson42** [comment]
@Popolechien What is your browser (version)? What is the KiwixJS version?

The ZIM seems OK, served by Kiwix Serve.

**Comment by kelson42** [comment]
My bad, the image is not in the ZIM. This is probalem with MWoffliner. Sorry about that.
