### ISSUE TITLE
Typing a word searches only a title beginning with it?

### ISSUE THREAD

**Issue by user0022** [kiwix/kiwix-js#734]
Hello!
For my first message, I just would like to say:
-Thanks for your work, because I find it some useful, and even if in fact I don't really like Kiwix for several reasons but I may be wrong.
-Excuse me for: my bad english I'm french, also almost zero technical level, and also ignorance about Kiwix I'm a new user.
-Hope I can help to improve this awful software ;).

I use Firefox addon, and Lubuntu 32 bits.

*
**Issue description.**
I've been amazed seeing this.
Only article titles are indexed for the moment if I understood. OK I think it's more or less bearable.
But other problem, is that I've just noticed that apparently (on my computer at least), typing a word in the search bar gives only titles which BEGIN with this word!

**Examples of the catastrophy (if needed).**
- In SuperUser archive, typing ZIM.
  6 results, but 0 in fact, for 1 is the ZIM tag, and the 5 others were titles beginning with "Zimbra".
  But opening the "ZIM" tag shows 10 results, "ZIM" being in the title or not. (Some about ZIM format and some about the Zim text editor.)
  And so it means that, if the ZIM tag wouldn't have been created, then 0 results, never! Even if there may be 50 titles with ZIM, but not in the beginning and not tagged with it.
  I tried *ZIM, or * ZIM, but still the same. 
- In Wikipedia (computer maxi) archive, typing Babbage.
  It won't give "Charles Babbage" article (since this article begins with "Charles"). Lucky for him, his "Charles Babbage" appears fast in the 2 pages beginning with "Babbage", but how many words don't have this luck?

For Wiktionary or Wikipedia, titles are often limited to 1 word, so here the catastrophy is a bit reduced...
But well if Kiwix works and will always work this way, I think it's dead for me, or for many ZIMs at least.

**Comment by mossroy** [comment]
It's unfortunately the way kiwix-js works for now, but we're working on improvements.
As you discovered, only titles are searchable and it's a "starts with" search strategy.

If it's important for you and you can't wait, you might switch to another kiwix client, like the desktop one or a mobile one, see https://www.kiwix.org/fr/ . They are able to do full-text search in the content, which should solve both problems you described.
If you're geek enough, the kiwix-js-windows client very recently implemented the ability to use some regular expressions (and, despite its name, it has a linux .deb and appImage packages)

But we're working on using the same code used in other kiwix clients, to have the same full-text search capability.
It's a big challenge, so I can't promise we will achieve it.
We should be able to work on that at the end of October 2021 (no promise on a release date)

**Comment by Jaifroid** [comment]
@user0022 See this issue: https://github.com/kiwix/kiwix-js-windows/issues/165 .
If you want to test that version, you can do so by visiting https://kiwix.github.io/kiwix-js-windows/ (this is a development version, the next full release of the PWA will be at pwa.kiwix.org ).

It would be useful to know if that version serves your needs with the Super User archive (I tested it on the Stackexchange Philosophy archive).

But, as @mossroy says, you might be better off using the full Kiwix client rather than these HTML/JS versions, which are intended to be lightweight alternatives supporting older hardware and systems/browsers.

Vous pouvez écrire en français ici si vous voulez.

**Comment by Jaifroid** [comment]
PS The wildcard you can use to test that version is `.*`, so for example you would type `.*babbage` in the Computer maxi archive. Result below.

![image](https://user-images.githubusercontent.com/4304337/125660856-0a5bc304-5ffb-4213-b451-c2250e9f5354.png)

**Comment by Jaifroid** [comment]
@user0022 #733 has added some explanation on the 'About' page as to how search operates. This is the best we can do for now. Wildcard search of titles is enabled in https://pwa.kiwix.org, in case that is useful to you.
