### ISSUE TITLE
Only polyfill Promise API if browser needs it

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#735]
I realize this is an optimization that would be better served by https://github.com/kiwix/kiwix-js/issues/554, where we would include babel or whatever the latest polyfill solution is, but "in the meantime" we could do "babel-lite", by using the currently recommended Promise polyfill from https://polyfill.io/v3/url-builder/ . This would be a more intelligent version than our current Promise polyfill, as it would only load if it detects that it is needed. Modern browsers handle promises very well and fast.

Alternatively, we could include the full ES6 polyfill package, and it would only polyfill these APIs if missing. It would allow us to write more modern code:

- Array.from
- Array.of
- Array.prototype.@@iterator
- Array.prototype.copyWithin
- Array.prototype.entries
- Array.prototype.fill
- Array.prototype.find
- Array.prototype.findIndex
- Array.prototype.keys
- Array.prototype.sort
- Array.prototype.values
- Function.prototype.name
- Map
- Math.acosh
- Math.asinh
- Math.atanh
- Math.cbrt
- Math.clz32
- Math.cosh
- Math.expm1
- Math.fround
- Math.hypot
- Math.imul
- Math.log10
- Math.log1p
- Math.log2
- Math.sign
- Math.sinh
- Math.tanh
- Math.trunc
- Number.Epsilon
- Number.MAX_SAFE_INTEGER
- Number.MIN_SAFE_INTEGER
- Number.isFinite
- Number.isInteger
- Number.isNaN
- Number.isSafeInteger
- Number.parseFloat
- Number.parseInt
- Object.assign
- Object.is
- Object.seal
- Object.setPrototypeOf
- Promise
- RegExp.prototype.flags
- Set
- String.fromCodePoint
- String.prototype.@@iterator
- String.prototype.codePointAt
- String.prototype.endsWith
- String.prototype.includes
- String.prototype.repeat
- String.prototype.startsWith
- Symbol.hasInstance
- Symbol.isConcatSpreadable
- Symbol.iterator
- Symbol.match
- Symbol.replace
- Symbol.search
- Symbol.species
- Symbol.split
- Symbol.toPrimitive
- Symbol.toStringTag
- Symbol.unscopables
- Symbol
- WeakMap
- WeakSet

**Comment by Jaifroid** [comment]
PS current recommended Promise polfill source is here:

https://github.com/Financial-Times/polyfill-library/tree/master/polyfills/Promise

(ignore Financial Times -- this is just being used by polyfill.io as a reliable and secure source for the open-source polyfill).

**Comment by mossroy** [comment]
In #67 you had made a few performance tests, and it appeared that Q was sometimes faster than native promises (and also sometimes slower...).
It was 4 years ago, so it would probably be worth checking that again.
I'm in favor of removing Q, and use a polyfill when needed, if there are not too many drawbacks

**Comment by Jaifroid** [comment]
You have a very good memory! Yes, it would be quite easy to remove Q and add the polyfills.io version  and then re-run the tests.
