### ISSUE TITLE
Add instructions for building Emscripten binaries with docker

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#739]
While looking to do some testing of #652, I stumbled upon a new official docker image for the Emscripten stack:

https://hub.docker.com/r/emscripten/emsdk

This ought to be very useful for #508, #511, #652, etc. With docker desktop (for example), you just type

`docker pull emscripten/emsdk`

This image is very new, I gather.

**Comment by mossroy** [comment]
I had seen. These images exist since one year, and it's probably the way to go for all future emscripten compilation
I had started using one in https://github.com/mossroy/libzim_wasm/tree/update_to_emsdk_2.0.15 but did not have the time to finalize it (I had C compile issues, probably due to our code, not to the docker image)

**Comment by Jaifroid** [comment]
Ah, OK, glad to know you've tried out this method!

I had a lot of difficulty getting emsdk to run stably on Windows (natively), as it's obviously not the dev's main target and things were always a bit broken with each update. So I switched to using WSL, which required me to install an older node verstion to run (at that point in time the emsdk was broken with latest node), but now that WSL instance is badly out of date and node complains it needs a newer version to do anything. I probably misconfigured something...

All in all, this docker container should simplify things a lot by providing a stable and predictable environment supported by the dev. It will be important, if we solve #508, that we can easily recompile libzim on a regular basis in an at least semi-automated way.
