### ISSUE TITLE
Improve transitions between screens, with a slide effect for example

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#74]
It seems possible via CSS3 + hashtags. See https://hacks.mozilla.org/2014/02/the-making-of-the-time-out-firefox-os-app/
Anyway, we already use hashtags for title names...

**Comment by Swayamsvk** [comment]
Do you mean we should be able to switch between pages with a slide feature also?

**Comment by mossroy** [comment]
The idea would be to have some beautiful transition when the user switches between the different sections : main page (where the ZIM content is displayed), settings, and about.
We currently simply hide/show some divs to do that : some CSS transitions might be applied, so that the settings and about sections could look like they were sliding in/out.

**Comment by vasusharma7** [comment]
Yes I would like to work on this....This looks quite interesting.

**Comment by vasusharma7** [comment]
@mossroy I have implemented a transition effect between pages....Please see PR #579 [https://github.com/kiwix/kiwix-js/pull/579](579)..and guide further
