### ISSUE TITLE
Upgrade Nightwatch

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#743]
This follows on from #742. Nightwatch 1.5.1 depends on packages with severe vulnerabilities, but upgrading to 1.7.7 causes tests to fail due to connection to the wrong port (80 instead of 8080 see https://github.com/kiwix/kiwix-js/pull/742#issuecomment-885425167).

![image](https://user-images.githubusercontent.com/4304337/126797680-12e1e38d-6f67-40f4-b9d4-d4c40bf17693.png)

**Comment by Krinkle** [comment]
I don't know Nightwatch very well, but searching upstream I found this issue which might be related:

* https://github.com/nightwatchjs/nightwatch/issues/2803

**Comment by Jaifroid** [comment]
I never could fix this, but now I aim to use #907.
