### ISSUE TITLE
Recent stackexchange ZIM files have broken responsive design in jQuery mode

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#756]
https://mirror.download.kiwix.org/zim/.hidden/dev/alcohol_meta_stackexchange_com_2021-08.zim has a responsive design : the Questions/Tags/Users/About items that appear on the left side on large screens should be moved at the top on smaller screens : 

  * With a large window/screen, the header looks like this :
![image](https://user-images.githubusercontent.com/890923/130267182-978f7cce-7d55-4628-bbe2-c56f1bd5dd23.png)

  * With a smaller window/screen ((width<=640px), it should look like this : 
![image](https://user-images.githubusercontent.com/890923/130267273-2f9a2a2d-a709-470a-9341-e0828a21f23c.png)

In ServiceWorker mode, it works fine (even if I find the difference surprising, see https://github.com/openzim/sotoki/issues/237)
But in jQuery mode, the left panel remains in small screens : 
![image](https://user-images.githubusercontent.com/890923/130363602-40182625-d904-44fb-93bb-a3ae5861eeba.png)

I initially thought it was because of some javascript handling (unsupported in jQuery mode), but @rgaudin says javascript is not used for that (see https://github.com/openzim/sotoki/issues/237#issuecomment-903233613)

We should investigate to see where it comes from. If it's something we can't easily fix in kiwix-js, it might be still time to ask for a change on sotoki (if it's not complicated).

**Comment by Jaifroid** [comment]
I wonder if this has anything to do with the order in which CSS is loaded and applied. Very wild guess.

**Comment by kelson42** [comment]
We finally are refreshing all StackExchange ZIM files (180 of them) with version 2.0.0 of Sotoki. Therefore, from now, this bug will have more impact.

**Comment by Jaifroid** [comment]
I confirm this issue is still present (jQuery mode only) in Stack Exchange ZIMs produced this month (yesterday). I tested with `french_stackexchange_com_2022-05.zim`. The issue seems to come from the fact that the screen of the inner div does not in fact resize when the page as a whole is resized. The same issue affect KJSW (in jQuery mode only).

![image](https://user-images.githubusercontent.com/4304337/167365877-27732224-b4ae-4e21-be93-8f28030dc76b.png)

**Comment by kelson42** [comment]
Bug is still there in `3.6.0` with [beer.stackexchange.com_en_all_2022-11.zim](https://download.kiwix.org/zim/stack_exchange/beer.stackexchange.com_en_all_2022-11.zim), but really wonder this is worth investigating considering that SW mode is default one and we priority is not anymore to fix bugs in JQuery mode.

**Comment by Jaifroid** [comment]
I confirm. It's clearly not a problem with the ZIM, because it affects only jQuery mode. I agree it's not worth fixing for JQuery mode only. This is therefore very low priority. I'll close it as wontfix.

**Comment by mossroy** [comment]
I agree
