### ISSUE TITLE
Khan Academy videos do not play in jQuery mode

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#760]
I tested with `khan-academy-videos_en_special-relativity-physics-khan-academy_2021-03.zim`. The video pages look very similar to TED Talks (which do work), so it's probably something small that we can fix without extra coding. Videos play in SW mode.

**Comment by Jaifroid** [comment]
I've determined that the codec of both TED Talks and Khan Academy videos is VP80 with Vorbis audio. Identical format (in WebM shell), yet the former can be loaded in jQuery mode, and the latter can't, in both Kiwix JS and KJSW. In KJSW a media download is offered, and doing so succeeds (the resulting webm can be played in the system media player as well as in VLC). So there is no issue with extracting the BLOB and making a blob: URI.

**Comment by Jaifroid** [comment]
OK, I can copy the blob URI for the video, e.g. `blob:http://localhost/0147b46f-622b-4cad-9ebf-aa031ba654da`, and paste it into a new tab, and it will play fine in Edge (Chromium). Therefore the blob URI is fully accessible (and not revoked), but the browser doesn't seem to be able to read it when it is injected as the src of a `<source ... >` tag, even though it can do so for a TED talk equivalent. Strange.

**Comment by Jaifroid** [comment]
I've found the issue. There is a missing `controls="true"` property in the `<video ... >` container in the Khan Academy ZIM. In fact, at least in Chromium, you can right-click the video and select "Show controls...", and it is then possible to play it. So, no problem with our code, but a problem with the ZIM, which assumes that every ZIM reader will use JavaScript.

It is very easy to patch this, to test for the missing control (I've done it in diagnostic code). I think we probably have to because there are a lot of ZIMs out there with this issue, and possibly even recent TED talks (I've only tested on an old one, this issue might have crept in more recently). However, it should be fixed in source as well.

**Comment by Jaifroid** [comment]
@kelson42 Where do I report this issue with Khan Academy ZIMs? To summarize, the issue is that the ZIM assumes that the ZIM reader can run JS, and has removed basic HTML controls. I guess it also affects any recent ZIM created with the same video setup code, possibly recent TED talks as well (I need to check that, but the page design looks identical).

**Comment by kelson42** [comment]
@Jaifroid Kind of surprising problem to me.... but this ZIM file is done with the Youtube scraper... therefore if you believe there is a problem with this scraper please open a ticket at https://github.com/openzim/youtube.

**Comment by kelson42** [comment]
@Jaifroid If you visit http://library.kiwix.org/khan-academy-videos_en_special-relativity-physics-khan-academy_2021-03 (online demo) with Chrome, everything seems to work fine to me.

**Comment by Jaifroid** [comment]
> @Jaifroid If you visit http://library.kiwix.org/khan-academy-videos_en_special-relativity-physics-khan-academy_2021-03 (online demo) with Chrome, everything seems to work fine to me.

Yes, but that's not using Kiwix JS, and it runs JS from the ZIM. As usual, our issue is that for a large number of users (notably those using the Firefox Extension, but also our mobile users), it is not possible to run JS from the ZIM. Therefore the `video.js` doesn't run. If the controls are are only shown by the JS, then users who don't run JS are unable to access the ZIM's content. But the solution is very simple.
