### ISSUE TITLE
Add tooltips to icons and settings

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#775]
As suggested by RMS, this could be a useful way of explaining our UI to new users. It is very easy to add these to icons and to settings in Configuration. where an additional explanation of what a setting does can be helpful. Of course we need to be mindful that the more text that is added, the more translation will be required of the UI when we implement #13.

**Comment by ankur12-1610** [comment]
I would like to work on this issue, but I'm not sure how to start. Could you please explain:sweat_smile:?

**Comment by Jaifroid** [comment]
@ankur12-1610 Thanks for the offer.

You'll need a local web server (I recommend npm's http-server), and a code editor like Visual Studio Code set up to work with HTML and JavaScript. Clone the repository. Then you'll need to study the code in the app's main index.html file, to look for the places where tooltips can be inserted. When you have a working version that you can serve from http://localhost:8080 (in the case of http-server), and you're happy with it, you can make a Pull Request for us to review. Please don't reformat or prettify the entire HTML file. We will want to see only the tooltips you have added, not a lot of other formatting changes.

I hope this helps. I'll assign the issue if you confirm you can work on it and understand what you need to do above.

**Comment by ankur12-1610** [comment]
> @ankur12-1610 Thanks for the offer.
> 
> You'll need a local web server (I recommend npm's http-server), and a code editor like Visual Studio Code set up to work with HTML and JavaScript. Clone the repository. Then you'll need to study the code in the app's main index.html file, to look for the places where tooltips can be inserted. When you have a working version that you can serve from http://localhost:8080 (in the case of http-server), and you're happy with it, you can make a Pull Request for us to review. Please don't reformat or prettify the entire HTML file. We will want to see only the tooltips you have added, not a lot of other formatting changes.
> 
> I hope this helps. I'll assign the issue if you confirm you can work on it and understand what you need to do above.

Thanks @Jaifroid :), got the issue, I'll work on it!

**Comment by Jaifroid** [comment]
Well, this is how I did it in Kiwix JS Windows (see green underlining). Basically add a `title="[Tooltip text goes here]"` to the icons and labels. For some it will be really simple. For example, for the Random button, add the attribute `title="Random"` to the element that displays the button. For the configuration options, you probably want a bit more text, but it doesn't have to be as long as my example below. You need to test your work in more than one browser. I'd suggest testing in Chromium (Chrome or Edge) and Firefox. If you can test in Internet Explorer too, that would be great, but don't worry about that.

![image](https://user-images.githubusercontent.com/4304337/145113922-1c916087-4390-411d-b10c-6a35305ded0c.png)

**Comment by ankur12-1610** [comment]
> Well, this is how I did it in Kiwix JS Windows (see green underlining). Basically add a `title="[Tooltip text goes here]"` to the icons and labels. For some it will be really simple. For example, for the Random button, add the attribute `title="Random"` to the element that displays the button. For the configuration options, you probably want a bit more text, but it doesn't have to be as long as my example below. You need to test your work in more than one browser. I'd suggest testing in Chromium (Chrome or Edge) and Firefox. If you can test in Internet Explorer too, that would be great, but don't worry about that.
> 
> ![image](https://user-images.githubusercontent.com/4304337/145113922-1c916087-4390-411d-b10c-6a35305ded0c.png)

Oh! got it, thanks a lot for resolving the doubt:)

**Comment by ankur12-1610** [comment]
@Jaifroid I've raised a PR, can you please verify?

**Comment by Jaifroid** [comment]
@ankur12-1610 Thanks!

**Comment by Harshsharma-dev** [comment]
Hey! I would like to work on this but can you please guide me, that do i have to add tooltips only to the display settings?

**Comment by Jaifroid** [comment]
@Harshsharma-dev Thanks for the offer, but this issue is already being worked on by @ankur12-1610 , and there is an active PR in progress.

**Comment by Harshsharma-dev** [comment]
okay :D

**Comment by ankur12-1610** [comment]
> @Harshsharma-dev Thanks for the offer, but this issue is already being worked on by @ankur12-1610 , and there is an active PR in progress.

Yeah:sweat_smile:, btw I've updated the PR with the changes. Can you please review the PR? :')

**Comment by Jaifroid** [comment]
@ankur12-1610 I'll get to it as soon as I get some time!
