### ISSUE TITLE
Insufficient form height of the text in input checkbox of `Display Settings`.

### ISSUE THREAD

**Issue by ankur12-1610** [kiwix/kiwix-js#776]
![kiwix](https://user-images.githubusercontent.com/76884959/145025407-1837f3e7-3420-4c3b-8a7f-02437f3dbbb9.png)

![darkki](https://user-images.githubusercontent.com/76884959/145025669-2d464238-cd79-44db-a92a-2bfae8a78c18.png)

Some parts of the text are not fully visible.

**Comment by ankur12-1610** [comment]
I would like to work on this issue.

**Comment by Jaifroid** [comment]
OK, thanks.

**Comment by ankur12-1610** [comment]
> 

I have created a PR which solves this issue, can you please review :sweat_smile: ?
