### ISSUE TITLE
Simplify the source code for hiding/showing of HTML elements

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#78]
It's becoming a bit complicated to maintain all these .hide() and .show()

**Comment by Jaifroid** [comment]
There is a lot of repeated code, whether it's jQuery hide and show statements or native JS equivalents. These hide or show UI elements when the Home button is clicked, when the Random button is clicked, when a search is launched, when the user goes to Configuration or About. A lot of the code is the same and could be tidied away into non-jQuery functions.
