### ISSUE TITLE
Search-bar not properly aligned with the search button.

### ISSUE THREAD

**Issue by ankur12-1610** [kiwix/kiwix-js#780]
The search-bar on `Home` is not properly aligned with the search button.
![search-bar](https://user-images.githubusercontent.com/76884959/145457840-a8fdefc7-2e77-4fc7-a1b2-d1a2725e920e.png)

**Comment by ankur12-1610** [comment]
I'll like to work on this issue, it is a minor frontend bug fix :)

**Comment by ankur12-1610** [comment]
@Jaifroid added a PR which solves this issue, it is just a small change and might not bother much :sweat_smile: 

Kindly review!

**Comment by Jaifroid** [comment]
OK, thanks. I'll take a look.
