### ISSUE TITLE
Dragging of elements may cause unexpected behavior

### ISSUE THREAD

**Issue by try-catch-stack** [kiwix/kiwix-js#782]
Few elements like the navigation bar on the bottom and Kiwix logo are draggable which can cause unexpected behavior and can also interfere with the drag and drop feature of ZIM files.

https://user-images.githubusercontent.com/77742477/146038674-c36be025-992f-4531-8186-acaa385548d9.mp4

**Comment by Jaifroid** [comment]
Thank you, I can reproduce this issue on Edge (Chromium).
