### ISSUE TITLE
Mention the Kiwix REPORT_BUG as the guideline for kiwix-js

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#784]
Maybe by creating a file with the same name, that would point to this URL :

https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

and/or mentioning that in the README.md and/or the "About" section of the app

**Comment by try-catch-stack** [comment]
Hey @mossroy , I would like to work on it. But can you tell me what exactly is the desired output. I mean do you want a section like usage,feedback,credits on the About page?

**Comment by mossroy** [comment]
Thanks @try-catch-stack but I'd prefer to discuss and do that ourself with @Jaifroid

**Comment by mossroy** [comment]
If https://github.com/kiwix/overview/issues/61 is accepted and done, we should also mention it here

**Comment by Jaifroid** [comment]
@mossroy Where do you think we should mention this? It looks very sensible. In the README on the front page? Do you have something specific in mind that you'd like me to review, or shall I propose some text to add to README?

I think we could say that we are very happy to receive feedback and reports of issues encountered by users, but that, whether reporting issues by email or directly on GitHub, all users should follow the procedure laid out in https://github.com/kiwix/overview/blob/master/REPORT_BUG.md .

We could add some default text to new issues asking users to check REPORT_BUG before they start to describe their issue. Of course this won't help with email users, and we don't have significant numbers of users submitting issues via GitHub.

**Comment by mossroy** [comment]
I've created a PR with a code of conduct : https://github.com/kiwix/overview/pull/62

**Comment by mossroy** [comment]
Now that kiwix/overview#62 has been merged, I think we can manually copy the files CODE_OF_CONDUCT.md and REPORT_BUG.md here (and maybe mention them in README.md, along with CONTRIBUTING.md too? Maybe after #792 is merged)
