### ISSUE TITLE
Add CONTRIBUTING.md to the repo

### ISSUE THREAD

**Issue by gaurav7019** [kiwix/kiwix-js#799]
With reference to #792, the repo should have a CONTRIBUTING.md file to help out the newcomers to the repo.

**Comment by gaurav7019** [comment]
@Jaifroid Please assign this issue to me, I can't self-assign it seems. Also, please add the appropriate labels.

**Comment by Jaifroid** [comment]
@gaurav7019 Done.

**Comment by gaurav7019** [comment]
> @gaurav7019 Done.

Yeah, thanks :)

**Comment by gaurav7019** [comment]
@Jaifroid Should I also the contributions instructions to fork the repo before contributing. It's not there in your [text](https://github.com/kiwix/kiwix-js/tree/Update-documentation-to-include-new-implementation#contributing), is it because it's obvious and hence unnecessary to mention or developers can directly clone the original remote.

**Comment by Jaifroid** [comment]
@gaurav7019 We do expect familiarity with GitHub as a precondition of contributing, but if you'd like to explain how to fork and clone a repo (very briefly), that would be fine.
