### ISSUE TITLE
Decode WebP data: URI images properly in browsers that do not support WebP

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#816]
[This would be for v3.4. I'm just putting down a marker now before I forget. I'm not proposing for v3.3 because a) it's too late, and b) I want to find an example in a recent ZIM as a test case.]

**The issue:** We are claiming to support data: URI images in #805, but there is a small category of browsers that cannot deal with WebP for which this claim is not true if an image is WebP-encoded. IE11 is the obvious one, but not only.

I believe we can fix by adding this to `uiUtil.feedNodeWithBlob()`:
```
            // If we're dealing with a dataURI, first convert to Uint8Array
            if (/^data:/i.test(content)) {
                content = util.dataURItoUint8Array(content);
            }
```
It's an edge case, but easy to fix. WebP Machine cannot deal with dataURIs (even though it produces dataURIs), but it can deal with `Uint8Array`s.

JFYI, this fix is actually road tested as it's been in KJSW for at least a year due to the fact that I do some special processing with data URIs in order to enable exporting an article to a self-contained browser tab with all images and CSS encoded as dataURIs. I'm not proposing to backport that code, just the lines above.

**Comment by mossroy** [comment]
All right, why not
