### ISSUE TITLE
[UT] App ID needed?

### ISSUE THREAD

**Issue by cibersheep** [kiwix/kiwix-js#819]
I need to verify if this parameter is still needed but it might make life easier :)

By memory, I think `--app-id=[appname.appdev]` is needed to handle .cache and .local files accordantly

https://docs.ubports.com/en/latest/appdev/webapp/guide.html#command-line-arguments

**Comment by cibersheep** [comment]
Mhm, you have set up the app name as "ubports-little-webapp"

https://github.com/kiwix/kiwix-js/blob/master/ubuntu_touch/manifest.json#L10

Maybe this can be address in the future:
- the webapp is not from UBports (the foundation) so it shouldn't be in the app id
- more conventional app id should be something like `kiwix.kiwixteam` for example. Changing this will break compatibility from older app versions (and may need to be published as a 'new' app in the Open Store

**Comment by cibersheep** [comment]
I have updated the manisfest: https://github.com/kiwix/kiwix-js/pull/827

but I think the [name](https://github.com/kiwix/kiwix-js/blob/master/ubuntu_touch/manifest.json#L2) parameter needs to be updated to `name.organisation` format. This might be not needed and will make OpenStore force to create a "new app" due to the change of the name.

Do you want me to update or wait?

**Comment by mossroy** [comment]
The problem of a "new app" is that previous users will not automatically be upgraded.
As we currently have a regression that needs to be fixed, I would hold this update for now, and discuss it later

**Comment by cibersheep** [comment]
Perfect. Thank you
