### ISSUE TITLE
Remove usage of innerHTML of our code

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#824]
It is currently the case in app.js and uiUtil.js, but it should be searched everywhere (excluding the third-party libraries like fontawesome or jquery).

`.innerHTML` can be unsafe in terms of security. Its usage triggers warnings (at least when we upload the package on Mozilla store).

It should be possible to replace them by `.textContent` when it's unformatted text.
When it's not simple text, it should be possible to create the nodes programmatically.

**Comment by Jaifroid** [comment]
Where it's not too complicated, I agree. The safety issues are minimal given that we only inject html from ZIM archives. But I guess it's possible a ZIM could unintentionally have malicious code.

**Comment by mossroy** [comment]
It's true that the usage we do of `.innerHTML` is probably not risky.
But the automatic tools can not know that. Plus using `.textContent` is probably a bit faster (as the browser does not have to convert HTML to/from the DOM)
In any case, this is not high priority.

**Comment by prsndp** [comment]
@mossroy Hey, if it is a valid and possible issue then I would like to work on this. please let me know. Thanks:)

**Comment by mossroy** [comment]
Thanks @prsndp 
I've assigned it to you. Please read the CONTRIBUTING.md guidelines before creating a PR

**Comment by prsndp** [comment]
@mossroy  Yeah, Sure :)

**Comment by prsndp** [comment]
@mossroy Hey, please review this PR.

**Comment by me-aashish** [comment]
Hey, @mossroy  if this issue is still available, I would like to work upon it. Please do let me know if this is the case.

**Comment by me-aashish** [comment]
@kelson42 can you tell me please how to get started ?

**Comment by Jaifroid** [comment]
@me-aashish Thanks for the offer. Please see https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md for information on how to get started. When you've set up and have looked around the code a little, come back here and let us know how you plan to tackle the issue.

**Comment by me-aashish** [comment]
Sure. Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by me-aashish** [comment]
By looking at the codebase, I came to know that besides app.js and uiUtil.js, .innerHTML is used several times in node_modules file. So I have to replace .innerHTML from node_modules file too ?

**Comment by Jaifroid** [comment]
@me-aashish No, these are NPM libraries that are only used during development. It's only in our own app's files that we need to find alternatives for .innerHTML.

**Comment by me-aashish** [comment]
Got it! Thanks!

**Comment by me-aashish** [comment]
I am having problem in setting up local web server. Can you please guide me once ?

**Comment by Jaifroid** [comment]
Make sure you've set up node and npm on your system. Then run `npm install --global http-server`.

**Comment by me-aashish** [comment]
ok!

**Comment by me-aashish** [comment]
I have created a PR changing the contents of only app.js. Will also modify uiUtil.js once you verify if all the things are working well.
So, can you please review my PR?

**Comment by mossroy** [comment]
You have to test your changes first, by running the app on your branch (see https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md ).
Did you already did that? Which tests did you do?

**Comment by me-aashish** [comment]
Firstly, ServiceWorker API was working on my PC but not it is not working right now while testing. Can you tell the possible reasons for that ?

**Comment by mossroy** [comment]
Check that you run the webserver from the root of the git repo (not from a subdir). That might be the reason.
ServiceWorker mode should always work on http://localhost URLs

**Comment by me-aashish** [comment]
Ok! Got you!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by me-aashish** [comment]
Now, the server is working fine on http://localhost:8080/www/index.html but the changes I make in the code is not getting reflected back in http://localhost URL. Please can you tell some possibilities for that ?

**Comment by mossroy** [comment]
Please re-read completely the CONTRIBUTING.md file, where you should find your answer, and other important directions.

**Comment by Jaifroid** [comment]
And just a quick tip: once you select the "Bypass App Cache" setting (only available when you have turned on Service Worker mode), you can refresh everything by having Dev Tools open and pressing Ctrl-Shift-R (not just Ctrl-R) for a complete re-load of the app. Just do this after each significant code change.

**Comment by me-aashish** [comment]
When I replace .innerHTML with .textContent, changes are visible only in ServiceWorker mode not in JQuery mode in localhost url. Why it is happening?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Jaifroid** [comment]
@me-aashish The code for jQuery mode and the code for Service Worker mode are quite separate in lots of places. I.e., if you're in one mode, a lot of the code in the other mode is not running, and vice-versa. Code in the backend is common to both modes.

**Comment by me-aashish** [comment]
I have performed all the tests which includes testing in both jQuery and Service Worker mode. Also tested the extension version as  stated in CONTRIBUTING.md and these two PRs are made after all the tests. Kindly review them. #874 #873 #

**Comment by aritroCoder** [comment]
Hello, I have some experience with reactjs and javascript, so I want to work on this issue. Please guide me how to set up this project initially, and then assign this to me

**Comment by Jaifroid** [comment]
@aritroCoder Please take a look at https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md for getting started with this project. If you've been able to set things up and are ready to contribute, come back here and confirm, and we can then assign you. Also please read carefully the first post, because previous contributors who have attempted this issue simply tried to use `.textContent` everywhere, and that is not viable, as we have HTML-formatted dialogue boxes that are currently using `.innerHTML`. For cases where we need/want to insert HTML, the idea is to see if this can be inserted by creating the nodes programmatically, using an API.

**Comment by aritroCoder** [comment]
Hello, I have been able to set up the project, and have already made changes in the `navbar` section and footer `Settings Storage API` section.  I think using `appendChild(document.createTextNode("text");` can be beneficial here, I was trying to use that

**Comment by aritroCoder** [comment]
@Jaifroid just to be sure, there is only `innterHTML` in the app.js file, and I do not need to modify the libs

**Comment by aritroCoder** [comment]
@mossroy @Jaifroid I have removed all `innerHTML` files from app.js

**Comment by mossroy** [comment]
@aritroCoder please test browsing ZIM files to check there is no regression, then create a PR if everything works properly

**Comment by aritroCoder** [comment]
![image](https://user-images.githubusercontent.com/92646038/193458630-691c43ef-64f9-4fc1-a0bf-169f447d7839.png)

![Screenshot from 2022-10-02 19-45-07](https://user-images.githubusercontent.com/92646038/193458706-74073b18-5710-46b3-846f-2ad545359736.png)
Looks like thinks are working fine

**Comment by Jaifroid** [comment]
Thanks!

Please be sure to test in jQuery mode as well. Also check the API panel in Configuration, as a lot of the info there is injected via innerHTML currently.

Please follow all the tests mentioned here: https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md .

When you're happy everything is OK, please create a PR so we can review your work.

**Comment by aritroCoder** [comment]
> Thanks!
> 
> Please be sure to test in jQuery mode as well. Also check the API panel in Configuration, as a lot of the info there is injected via innerHTML currently.
> 
> Please follow all the tests mentioned here: https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md .
> 
> When you're happy everything is OK, please create a PR so we can review your work.

Sorry for the delay, I was out for few days. I have checked the jQuery mode and API panels, both are working fine

**Comment by aritroCoder** [comment]
> Thanks!
> 
> Please be sure to test in jQuery mode as well. Also check the API panel in Configuration, as a lot of the info there is injected via innerHTML currently.
> 
> Please follow all the tests mentioned here: https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md .
> 
> When you're happy everything is OK, please create a PR so we can review your work.

Sorry for the delay, I was out for the few days. The tests are passing so I think it is time to make a PR
