### ISSUE TITLE
Rework the code on startup to prevent some alert/confirm popups overlaping

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#841]
In app.js, there is some code that is always run on startup. Some of these steps might trigger an alert/confirm:

1. restore parameters from settingsStore
2. apply parameters from queryString
3. apply theme
4. set home key behavior
5. set content injection mode
6. define behavior of HTML elements (event listeners)
7. handle and test DeviceStorage (this is Firefox OS specific)
8. else (if not on Firefox OS), see if there is a selected file (it can only happen on Firefox). If yes, open this archive. Else go to configuration section
9. load blank article in the iframe
10. resize iFrame

There are at least steps 5, 7 and 8 that can trigger an alert/confirm.
So the problem _might_ occur here.
To avoid this, we might move some of these synchronous steps to new functions, that would be called asynchronously, after the user closes the modal window.

**Comment by Rbcoder1** [comment]
I think I can fixed
Can I Work On It

**Comment by Jaifroid** [comment]
@Rbcoder1 I'm not sure if this issue is current. I've never seen overlapping system alerts...

**Comment by Rbcoder1** [comment]
Ok
