### ISSUE TITLE
Remove unused functions from util.js (possibly also elsewhere)

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#843]
Quite a few functions exported in `util.js` are unused currently in the app. Some may be interesting techniques that we want to keep for reference, but then we shouldn't expose them. Others are obsolete and should be removed.

Any PR based on this issue should await merging of #838 because some functions are already being removed there.

**Comment by kelson42** [comment]
#838 has been merged, it should be easy (my guess) to implememt that one now.

**Comment by me-aashish** [comment]
Hello there! I want to resolve this issue. Can someone please guide me for that ?

**Comment by Bam92** [comment]
Hello!

Just to let you know that I am working on this issue given that no PR has been submitted since January.

**Comment by dipenr06** [comment]
@Bam92 hey there mate, I would like to confirm if you still working on this issue?

**Comment by Bam92** [comment]
Hey @dipenr06,

Yes, I planned to work on in this hacktoberfest.

**Comment by dheerajdlalwani** [comment]
Don't mind if I do?

**Comment by amitpanwar789** [comment]
can I work on this issue?

**Comment by Jaifroid** [comment]
@Bam92 It appears you didn't get a chance to work on this in October, so unless I hear from you, I'll assign it to the next person in the queue who has expressed an interest, @dheerajdlalwani. @amitpanwar789 I'd suggest you choose something else unless @dheerajdlalwani says he's not interested.

**Comment by dheerajdlalwani** [comment]
I have exams going on right now. It will be some time before I can get to it. So in the mean time, i think @amitpanwar789 can go for it?

**Comment by Jaifroid** [comment]
OK, thank you for letting me know @dheerajdlalwani. I'll wait a little to hear from @Bam92, and if he is no longer interested, I'll assign to @amitpanwar789.

**Comment by amitpanwar789** [comment]
@Jaifroid Should I wait or start working on it?

**Comment by Jaifroid** [comment]
@amitpanwar789 You can go ahead, thanks!

**Comment by amitpanwar789** [comment]
@Jaifroid  should I remove those unused functions completely from the util.js or just remove them only from return(export)?

**Comment by Jaifroid** [comment]
@amitpanwar789 You should remove them completely, please. They will remain in the git history in case anyone ever needs to find them again.
