### ISSUE TITLE
Release 3.4.0

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#850]
It seems to me that we have enough changes to release a 3.4.0

- [x] Update the changelog file
- [x] Further tests 
- [x] Rename existing milestones (increment their names), create a new 3.5 milestone and move open issues to this new 3.5
- [x] Create a tag on git
- [x] Generate unsigned extensions (should be automatically triggered on GitHub Actions by the tag creation)
- [x] Check that the PWA version is correctly set in moz-extension.kiwix.org (should be automatically triggered by tag creation)
- [x] Upload the unsigned extensions to Stores:
  - [x] Firefox - https://addons.mozilla.org/fr/developers/addon/kiwix-offline/edit
  - [x] Chrome
  - [x] Edge - https://partner.microsoft.com/en-us/dashboard/microsoftedge/
  - [x] Ubuntu touch - https://open-store.io
- [x] Prepare the source code for version 3.5
- [x] When available, copy the signed extension binaries to https://download.kiwix.org/release/browsers/
- [x] Update the kiwix.github.io implementation - should no longer be required, but check that the implementation is synchronized automatically with master
- [x] Publicize these new versions

**Comment by Jaifroid** [comment]
@mossroy Would you like me to tackle changelog? I now have more stable Internet access.

**Comment by mossroy** [comment]
There's no rush.
I won't be available this weekend. And if you're on vacation, we can do that a bit later.

**Comment by mossroy** [comment]
I've tested various ZIM files on my Firefox OS device, Chrome and Firefox extension (except the PWA is still in version 3.3.1, which is normal).
I'll prepare the milestones

**Comment by Jaifroid** [comment]
Tests to be done:

- [ ] IE11 from file system
- [ ] IE11 from Web server
- [ ] Edge legacy from Web server
- [ ] Edge Chromium from Web server

**Comment by Jaifroid** [comment]
All my tests completed. Icecat is showing the workaround, and it works. I updated the implementation at https://kiwix.github.io/kiwix-js/www/index.html in order to test Edge Legacy via Windows Mobile (it's no longer available in any Windows desktop OS). No issues detected. IE11 still works fine from the file system.

**Comment by Jaifroid** [comment]
@mossroy Would you like me to create the tag, or shall I wait until you're free for any troubleshooting? I haven't tested any extensions (packed or unpacked) -- have you done that?

**Comment by Jaifroid** [comment]
(of course I would squash the changelog PR first)

**Comment by mossroy** [comment]
Sorry, I was busy.
I had tested unpacked extensions on Chrome, and on Firefox (even if the PWA is still in version 3.3.1, which is normal).
To me, it's enough for us to go on.

**Comment by Jaifroid** [comment]
Miz-extension appears to have updated correctly

**Comment by mossroy** [comment]
I've uploaded this version for Ubuntu Touch and Firefox.

@kelson42 and @Jaifroid: please upload https://download.kiwix.org/nightly/2022-04-10/kiwix-chrome-unsigned-extension-3.4.0.zip to Google and Microsoft stores

**Comment by Jaifroid** [comment]
I've uploaded the Edge add-on.

**Comment by mossroy** [comment]
@kelson42 did you upload to Google Chrome store?
Please also upload the new files to https://download.kiwix.org/release/browsers/

**Comment by kelson42** [comment]
@mossroy Sorry for slowing down your publishing process, I just have done it (it's in review).

**Comment by Jaifroid** [comment]
I made a reddit post to publicize both this release and the most recent Kiwix JS Windows/Linux version (in the same post), here:

https://www.reddit.com/r/Kiwix/comments/u2pi4m/new_releases_of_kiwix_js_browser_extension_and/

@kelson42 or @Popolechien, can you do the Twitter publicity for this release?

**Comment by kelson42** [comment]
At the release page https://github.com/kiwix/kiwix-js/releases. I would recommend for the title of the release to just put the version number. This is IMO clearer (it's impossible in a few words to summarize a release... and the changelog is just below).

**Comment by Jaifroid** [comment]
Thanks for the publicity!

**Comment by Jaifroid** [comment]
I think we just need to prepare source code for 3.5 and then this issue is complete.

**Comment by mossroy** [comment]
Done, thanks to everyone who contributed!

**Comment by mossroy** [comment]
> At the release page https://github.com/kiwix/kiwix-js/releases. I would recommend for the title of the release to just put the version number. This is IMO clearer (it's impossible in a few words to summarize a release... and the changelog is just below).

I agree, I've changed that on github
