### ISSUE TITLE
Nightly releases are failing on both Kiwix JS and Kiwix JS Windows

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#851]
This must be to do with the change of infrastructure, because I see several Kiwix builds of different flavours are missing from nightly. @kelson42 @rgaudin  do we need new credentials to upload to download.kiwix.org or is there some other issue? The logs are showing:
```
kex_exchange_identification: read: Software caused connection abort
banner exchange: Connection to 51.1[59](https://github.com/kiwix/kiwix-js-windows/runs/5782022446?check_suite_focus=true#step:6:59).108.60 port 22: Software caused connection abort
lost connection
```

**Comment by rgaudin** [comment]
Yes it changed. Don't touch credentials, I'll send a PR to fix it as I did for the other projects ; sorry for the delay

**Comment by Jaifroid** [comment]
Thanks @rgaudin . Both KJS and KJSW also use local copies of the credentials because we run some local scripts too, not only on GitHub Actions. No rush at all, but in due course it would be great if you could send those credentials to @mossroy and me by Signal.

**Comment by rgaudin** [comment]
> No rush at all, but in due course it would be great if you could send those credentials to @mossroy and me by Signal.

Sent.
