### ISSUE TITLE
Update logo on Firefox and Windows stores

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-js#856]
These two ([here](https://addons.mozilla.org/en-US/firefox/addon/kiwix-offline/) and [here](https://www.microsoft.com/fr-ch/p/kiwix-js/9p8slz4j979j?rtc=1&activetab=pivot:overviewtab)) are still using the old logo. 

The updated one has been around for nearly two years now:
https://commons.wikimedia.org/wiki/File:Kiwix_logo_v3.svg

**Comment by Jaifroid** [comment]
Oops, sorry! I have been meaning to update the Windows Store one, but other things always ended up having higher priority. I agree this is getting long in the tooth...

**Comment by mossroy** [comment]
I've updated it on Firefox store: https://addons.mozilla.org/en-US/firefox/addon/kiwix-offline/

**Comment by Jaifroid** [comment]
I'll update the Microsoft Store for the next release, early next month.

**Comment by mossroy** [comment]
@Jaifroid : it seems to me that you updated the logo in the Microsoft Store, so I'm closing this issue.
Feel free to reopen it if necessary

**Comment by Jaifroid** [comment]
Yes, thanks -- updated vis v2.0.0 release.
