### ISSUE TITLE
Publish the docker image used to compile libzim with emscripten

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#866]
In some docker registry.
So that it's ready-to-use for developers on kiwix-js, without forcing them to build the image

**Comment by kelson42** [comment]
@mossroy Not sure to understand the rationals behind this ticket? Why such a Docker image shoukd be necessary if https://github.com/kiwix/kiwix-build/issues/503 is inplemented?

**Comment by mossroy** [comment]
That depends on how far we go on integrating the emscripten build(s) in kiwix-build.
The first step is libzim itself, with https://github.com/kiwix/kiwix-build/issues/503
If we only do this first step, there will still be a second emscripten compilation step to be done on the C "glue" code that allows to call libzim from javascript. In this case, it might be relevant to share one docker image for both compilation steps.

But if we go further and implement https://github.com/kiwix/kiwix-js/issues/768 to do all the emscripten compilation in kiwix-build, I agree with you it might not be necessary to share the docker image

To sum up, I think that depends on how much we integrate build steps on kiwix-build
In all cases, it should not be considered as a blocker: it's always possible to re-build the docker image when it's needed

**Comment by kelson42** [comment]
@mossroy I will discuss this with @mgautierfr, but to me the goal is clearly that libzim is directly usable in Javascript.

**Comment by kelson42** [comment]
I guess this ticket should ne now mode to `openzim/javascript-libzim`?

**Comment by mossroy** [comment]
> I guess this ticket should ne now mode to `openzim/javascript-libzim`?

Yes

**Comment by kelson42** [comment]
@mossroy done with Kamino https://github.com/gatewayapps/kamino

**Comment by mossroy** [comment]
Well, it indeed copy/pasted the issue and its comments, but it also changed the order of comments, and lost the author/date of each comment.
It makes it really hard to understand without referring to the original ticket (here)
