### ISSUE TITLE
Move source code for libzim wasm in kiwix-js repository

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#867]
It's currently in https://github.com/mossroy/libzim_wasm
Now that #513 is solved, we don't need to keep it separated any more, IMHO.

It should be moved in this kiwix-js repo (probably in branch https://github.com/kiwix/kiwix-js/tree/libzim-experiments at the beginning), with the necessary information to build libzim.

**Comment by mossroy** [comment]
The most important part is the C "glue" code that allows to call libzim from javascript (currently in file demo_file_api.cpp).
Note that, in the mid-term, compiling the libzim itself should become part of kiwix-build CI: https://github.com/kiwix/kiwix-build/issues/503
So that, in kiwix-js, we would take the already-compiled libzim binary files (in the version we choose), and only compile the glue C code

**Comment by kelson42** [comment]
Hmm, wonder if this ticket is not deprecated, or if this code in not already in `kiwix/kiwix-build` becaue of https://github.com/kiwix/kiwix-build/pull/548... or this is a ticket for `openzim/javascript-libzim`?

**Comment by mossroy** [comment]
I'm closing this issue, indeed.
The C glue code is now in `openzim/javascript-libzim` and kiwix-js should take the libzim binary from it (with the javascript bindings)
What will probably remain is to add clear explanations on how to check the source code and reproduce the build (at least for the Mozilla addons reviewers). Feel free to create a new ticket for that if you think it might be forgotten (see https://github.com/kiwix/kiwix-js/issues/910#issuecomment-1312507489)
