### ISSUE TITLE
Firefox extension does not switch to the PWA any more since Firefox 103.0

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#877]
On several devices where I have kiwix-js 3.4.0 Firefox extension installed, it no longer switches to the PWA when trying to use the ServiceWorker mode.
It says "The ServiceWorker API is not available on your device. Falling back to JQuery mode".

I suspect that there has been a change in Firefox behavior, in version 103.0.
In previous version of Firefox, the ServiceWorker API was available in extensions (`'serviceWorker' in navigator` returned `true`), but failed to register. And we trapped this registraion exception to propose a switch to the PWA (when inside a Firefox extension).

In my current version (103.0 64 bits on Ubuntu), `'serviceWorker' in navigator` now returns `false` in the extension, so kiwix-js does not propose to use the PWA, and fallbacks to jQuery mode.

I do not see any mention of this change in https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/103 so am not 100% sure

**Comment by mossroy** [comment]
I downloaded a few Firefox versions from https://ftp.mozilla.org/pub/firefox/releases/ (linux 64-bits versions), ran them in a VM, and tested to switch to SW mode in Kiwix extension on each:

- 100.0.2: works (proposes the PWA)
- 101.0.1: works (proposes the PWA)
- 102.0.1: works (proposes the PWA)
- 103.0: fails
- 103.0.1: fails

(if you try to reproduce, don't get fooled by the fact that these versions have auto-update enabled: on restart, you can end up on latest version instead of the one you extracted)

**Comment by mossroy** [comment]
I probably found the relevant change in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1593931

**Comment by mossroy** [comment]
The first solution I would think of would be to switch to the PWA if the protocol is `moz-extension` and the ServiceWorker API is unavailable.

It would work for recent versions of Firefox, but could be a problem for some old versions that really do not support ServiceWorkers (or have it disabled). In this case, the extension would suggest a switch to the PWA, that would not work either.

Based on https://caniuse.com/serviceworkers , the affected versions would be:
* Firefox 42 and 43 (Firefox 42 is the first version we officially support in the extension manifest)
* Firefox 45 ESR
* Firefox 52 ESR
* Firefox 60 ESR
* Firefox 68 ESR
(Firefox OS should not be affected as it uses a protocol different than 'moz-extension', IIRC)

We should test if the behavior is acceptable on these browser versions. At the very least, the user should be able to switch back to local jQuery mode.

**Comment by mossroy** [comment]
Maybe we should quickly release a new kiwix-js version with this fix?

**Comment by Jaifroid** [comment]
> Maybe we should quickly release a new kiwix-js version with this fix?

Yes, I agree. We don't want people using the extension suddenly finding that they can't switch to SW mode, especially given the aggressive updating that all modern browsers do without giving users much control over it.

**Comment by mossroy** [comment]
OK I'll create the ticket with the TODO-list
