### ISSUE TITLE
Test current kiwix-js with very old Firefox/Chrome browsers

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#879]
We claim to support Firefox >=45 and Chrome >=58, and our CI tests a scenario on these versions.

However, when working on #878, I did not always manage to run kiwix-js properly on old versions Firefox.
For example, on Firefox 45.0.2 (on Ubuntu 16.04), it does not manage to switch to the PWA for the ServiceWorker mode (maybe we use some unsupported syntax there).
I also see errors in the console regarding communication between the iframe and its surrounding document.

This should be investigated (with Chromium/Chrome 58, too) to have a status.

If it's easy to fix, let's fix these problems. Else we could consider adjusting our support policy.

NB: I regularly test on Firefox OS (which uses Gecko 44). As Firefox OS does not support ServiceWorkers, it's normal that I did not see the issue with the PWA switch. However, I do not see the errors regarding iframe communication on Firefox OS either...

**Comment by Jaifroid** [comment]
Interesting. I guess we didn't test enough on these early versions. Although I have a vague recollection of some remarks on a very early Firefox having non-stable support for Service Workers? Or was that when we were testing IceCat versions?

If there's a quick syntax fix, I'm all for doing that. Communication between PWA and the extension could indeed depend on it having been enabled by a specific Firefox version. It might have been more locked down in the "distant" past. It would need debugging.

**Comment by 456535688765** [comment]
can you assign this issues to me

**Comment by Jaifroid** [comment]
@456535688765 Happy to do so!

**Comment by Jaifroid** [comment]
I guess the outcome of this issue would be a PR changing our documentation, as the automated tests are not currently functioning well. However, if you have experience setting up automated tests, then that could be a possibility (we would use Browser Stack in that case). If you will undertake manual testing, that's fine too.

**Comment by Jaifroid** [comment]
It's currently assigned. @456535688765, any news? if the assigned person is no longer interested, I can reassign.
