### ISSUE TITLE
Release 3.5.0

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#880]
- [x] Update the changelog file
- [x] Further tests 
- [x] Rename existing milestones (increment their names), create a new 3.6 milestone and move open issues to this new 3.6
- [x] Create a tag on git
- [x] Generate unsigned extensions (should be automatically triggered on GitHub Actions by the tag creation)
- [x] Check that the PWA version is correctly set in moz-extension.kiwix.org (should be automatically triggered by tag creation)
- [x] Upload the unsigned extensions to Stores:
  - [x] Firefox - https://addons.mozilla.org/fr/developers/addon/kiwix-offline/edit
  - [x] Chrome
  - [x] Edge - https://partner.microsoft.com/en-us/dashboard/microsoftedge/
  - [x] Ubuntu touch - https://open-store.io
- [x] Prepare the source code for version 3.6
- [x] When available, copy the signed extension binaries to https://download.kiwix.org/release/browsers/
- [x] Check that the implementation on kiwix.github.io/kiwix-js/ is synchronized automatically with master
- [ ] Publicize these new versions

**Comment by mossroy** [comment]
Oops, I directly updated the changelog on master, by mistake.
Feel free to review it anyway, it's still possible to update it

**Comment by Jaifroid** [comment]
No problem. I saw some small typos, but am on my phone, will review later.

**Comment by mossroy** [comment]
I tested on my Firefox OS device with various ZIM files, and also in Firefox (103) and Chromium extensions.
Did not see any regression.
I tested in particular in SW mode: the switch to PWA, external links and video seeking

**Comment by Jaifroid** [comment]
```
## Kiwix-JS v3.5.0

Released on *2022-08-05*

* FEATURE: Bootstrap dialog boxes now handle a default action with Enter key
* FIX: Siwtch to the PWA version for Firefox in SW mode was broken by a behavior change of Firefox 103
* FIX: Video seeking in ServiceWorker mode in some browser extensions
* FIX: In ServiceWorker mode, open external links in new tabs (instead of inside the iframe, which could fail), and warn the user
* FIX: Directory Entries were wrongly assumed to be no larger than 2048 bytes
* UPDATE: Update logo on Firefox and Windows stores
```

@mossroy Just two slight rewordings for clarity and also typo `Siwtch`. I changed two spellings to British spelling, but US spelling is OK of course if you prefer it or if it is the standard for computing terminology:

1. FEATURE: The Enter key is now handled in Bootstrap dialogue boxes, triggering the default action
2. FIX: Switch to ServiceWorker mode via PWA workaround was broken due to a behaviour change in Firefox 103

**Comment by mossroy** [comment]
Thanks! I've updated the changelog.
Would you like to do some tests on Microsoft browsers before I create the tag? I don't think it's really necessary: as you wish/can

**Comment by Jaifroid** [comment]
No, there's no need for me to do more tests because I did a few tests today for your PR and didn't find any issues.

**Comment by mossroy** [comment]
I've created the release and uploaded it in Firefox and Ubuntu Touch stores.
Firefox store was the most important, as it's Firefox that had the regression. I confirm it's now fixed.

@Jaifroid can you upload it for Edge?
@kelson42 can you upload it for Chrome? and put the binaries in https://download.kiwix.org/release/browsers/?

**Comment by Jaifroid** [comment]
Yes, will do.

**Comment by Jaifroid** [comment]
Note I got a warning from the Edge Store:

`Warnings: It is recommended to upgrade your extension to manifest version 3. Code: manifest_version: 2 Line: 2 Column: 25`

I went ahead and published anyway without upgrading the manifest version. Are we ready for Chromium Extension manifest version 3?

@kelson42 Note that the file you need to upload to Chrome Store is https://download.kiwix.org/nightly/2022-08-05/kiwix-chrome-unsigned-extension-3.5.0.zip.

**Comment by Jaifroid** [comment]
Edge Store says it might take up to 7 days to validate...

In the meantime, I thought you might like to see the analytics from the Edge Extensions Store:

![image](https://user-images.githubusercontent.com/4304337/183239360-c6a7a0db-b771-4e4a-b9c1-7a62e8aeac6c.png)

Slow but steady climb to ~800 **weekly** users is not too shabby. We first uploaded to the Edge Store July 19th 2020.

I'm sure analytics for the other Stores will be much much higher. Chrome has something like 77% market share on desktop and the extension has been in the Chrome and Mozilla Stores for many years.

**Comment by Jaifroid** [comment]
Interesting use case from a Chinese reviewer in Edge Store:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/4304337/183239686-cbb70f3c-b072-448a-95dd-397be9878abf.png">

**Comment by kelson42** [comment]
New release published (still in review) in Chrome store and all 3 packages uploaded to download.kiwix.org

**Comment by mossroy** [comment]
I think this can be closed.
The only remaining part is to publicize the new version
