### ISSUE TITLE
Seems impossible to print an article

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-js#887]
I tried to print to a PDF file and this is what I get with FF:
![image](https://user-images.githubusercontent.com/1029718/189485950-86dc63ab-1c7e-4f1d-901b-8d529292f75f.png)

**Comment by mossroy** [comment]
Please give more detail: which ZIM file, which mode (jQuery/ServiceWorker) etc

I manage to print a wikipedia article content (to printer or PDF), in SW mode, by choosing to print the iframe (and not the surrounding UI). You can do that through a right-click in the ifame (i.e. in the content), and choose "this frame" -> "print the frame"

**Comment by kelson42** [comment]
The ZIM file is `wikipedia_fr_all_maxi_2022-03.zim` and this is the defaul JQuery mode. I just made CTRL+P to trigger the print dialog.

**Comment by mossroy** [comment]
I've created #888 to workaround this
