### ISSUE TITLE
Add a "print" feature

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#888]
If you just use ctrl-p in your browser, it will (badly) print the UI and only the beginning of the content (see #887)
It works well if you ask the browser to print the content of the iframe. On Firefox, you can right-click in the content, choose "this frame" -> "print the frame".

To avoid this issue, I don't see a better solution than to provide a "print" feature in the app, that would trigger the browser print on the iframe:

`document.getElementById("articleContent").contentWindow.print()`

**Comment by BBentleyDev** [comment]
Hi there, can I be assigned this issue?

**Comment by Jaifroid** [comment]
This issue is a duplicate of #350. That issue has some more information. A feature implementing this was developed for Kiwix JS Windows, and can be tested by going to https://pwa.kiwix.org.

**Comment by Jaifroid** [comment]
I transferred comment above to #350.

**Comment by mossroy** [comment]
Thanks @Jaifroid , I had indeed forgotten this existing ticket
