### ISSUE TITLE
When going quickly through history (back/forward buttons), it displays some parts of random articles

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#89]
It's certainly because the callbacks are not ignored after the user went to another page in history

**Comment by kelson42** [comment]
@mossroy @Jaifroid Considering the age of that ticket, it might be good to confirm this is still a problem.

**Comment by jsaenzes** [comment]
I'm not sure if this will be helpful or not but I attempted to recreate the issue (v 2.6). After a while of going back and forth in the history it would eventually have me on the same two articles (not random ones) rather than all the ones I had been on. I also tried testing on previous versions like 1.2 and 2.1 but was unable to see this issue appear in part because it was running very slowly and would crash. 
If there's any way I can help if this isn't useful please let me know!

**Comment by mossroy** [comment]
Thanks @jsaenzes : your test confirms the issue is still there.

It's certainly a "race condition" : on each click on back or forward button, it starts a code flow in the background that reads the content of the article and displays it.
If an article takes a long time to be read, it may appear after another has been displayed.

I think we need a way to ensure the last article always has priority over the other pending ones.

Maybe a way to do that would be to add a global variable holding the article title :
- we set it at the beginning of `goToArticle` function in app.js
- just before displaying the article, we check it still has the same value (title of the article) : if it isn't, we don't do anything

The "before displaying the article" would probably be in `readArticle` for ServiceWorker mode (before setting the iframe src), and in `displayArticleContentInIframe` for jQuery mode (before removing the iframe content, and probably before setting the `innerHTML` of the iframe too).

I won't have the time to code and test it myself in the next monts, but I added the label "good first issue" to that, because it does not seem complicated, hoping someone will pick it up and propose a Pull Request.

**Comment by zengchu2** [comment]
Let me check if I am understanding this problem correctly. 
Here is my running environment: **Chrome 78.0,  Kiwix v2.6 ** 
I open pages  **x, y, z** in order, and then I quickly click the **Back** and **Forward** buttons at the bottom of the web app. When I stop, I am on page with link "http://localhost:3000/www/index.html?title=A/z" and I **expect to see page z, but then page x and y pops up (whih is not expected).**

**Comment by mossroy** [comment]
@zengchu2 : yes, you correctly understood the issue
