### ISSUE TITLE
Normalize spelling of "ServiceWorker Mode" vs "Service Worker"

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#904]
We are currently inconsistent in sometimes using "Service Worker Mode" and (mostly) "ServiceWorker Mode". In the files touched by #903 I have normalized this to "ServiceWorker Mode" (since it is what we mostly use), but when discussing "Service Workers" (not followed by "Mode", I retain the space. However, there are many other places in the app where this is inconsistent, and it would be good to normalize elsewhere. It's out of scope for #903 because it would introduce a lot of noise into the PR.

**Comment by siddhant-afk** [comment]
Is this issue still open? I think I can work on it.

**Comment by sambhavgupta0705** [comment]
@Jaifroid Can I work on this issue?

**Comment by Jaifroid** [comment]
Yes, I'll assign you.

**Comment by Rbcoder1** [comment]
Is this issue is still open 
If no one can solved it then can I try to solved it

**Comment by Daksh119** [comment]
@Jaifroid I see the issue is still open. If it is not currently assigned to anyone can I work on this issue?

**Comment by Daksh119** [comment]
@Jaifroid Let me know if I can complete this existing issue

**Comment by Jaifroid** [comment]
@Daksh119 I think this is no longer an issue since the internationalization of the app recently. Sorry it wasn't closed earlier. I'd recommend finding another issue to work on.
