### ISSUE TITLE
Add cross-browser end-to-end testing with BrowserStack

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#907]
As a result of #894 and #895, end-to-end tests with SauceLabs have been disabled. These need to be replaced with a more modern configuration. While the longer-term aims are outlined in https://github.com/kiwix/kiwix-js/pull/895#issuecomment-1303104400, in the short term I aim to add an Action to run our end-to-end tests on BrowserStack, given that they have very thorough documentation of how to set this up. This would address the long-standing issues in #737 as well.

**Comment by Krinkle** [comment]
Fwiw, I'm quite happy with BrowserStack in several projects as well, numerically more often than Sauce even.

If you experience flakiness that seems specific to their hardware for some reason, that's worth considering I'd say. It's also possible that it's something else however. I'm not saying this to defend a vendor, but rather to potentially save you time.

I'll comment further at https://github.com/kiwix/kiwix-js/issues/737

**Comment by Jaifroid** [comment]
Now that I have been able to re-enable Unit testing of the source app with GitHub Actions and TestCafé in the ES6 modules branch, it should be relatively easy to begin porting our end-to-end UI tests to run on the bundled version of the app on BrowserStack. See #1025.

**Comment by Jaifroid** [comment]
Closed in favour of #1041.
