### ISSUE TITLE
Convert jQuery `.click()`, `.focus()`, `.attr()` and other homologous functions to their native equivalents

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#919]
Sub-issue of #367.

**Comment by dheerajdlalwani** [comment]
This seems like a nice, low hanging fruit to start contributing. I'd like to take this one up, @Jaifroid

**Comment by Jaifroid** [comment]
@dheerajdlalwani Thank you for the offer. Please note that for these issues about jQuery, it's mandatory to test on IE11, or in IE11 mode in Edge Chromium. This is because it is old browsers that are likely to be affected by removal of jQuery. Please also read the [CONTRIBUTING](https://github.com/kiwix/kiwix-js/blob/master/CONTRIBUTING.md) guidelines, and confirm you're happy to follow them and also to test on IE11 or IE Mode. This complicates things a bit. If you are running Windows 11, let me know and I can tell you how to open real IE11 very easily even though it has been "removed" from the OS. If you run Linux and don't have access to a Windows machine/OS, probably this issue might not be the best one for you.

**Comment by dheerajdlalwani** [comment]
Oh yes! I read the CONTRIBUTING guidelines and I am more than happy to do the required testing for IE 11.
And also, yes I am running Windows 11.

**Comment by Jaifroid** [comment]
Great thanks. The easiest way to open IE11 in Win11 is to open Control Panel (win key -> type "control"), click on "Network and Internet", then "Internet Options". A dialogue box like below should open up. Then click on the question mark circled in red. IE11 should open up. You can open Dev Tools as usual with F12 key.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/4304337/202233903-f01e1ce4-cb27-4303-8565-8c54865c62ba.png">

**Comment by Jaifroid** [comment]
You should find https://youmightnotneedjquery.com/ helpful in finding alternatives and ensuring they are valid for at least IE11+. There's another resource listed towards top of #367 that allows you to view jQuery's own source code for its functions. That resource is archived on the Internet Archive.

**Comment by dheerajdlalwani** [comment]
While working on this, I realized many a times, jQuery `.on` event listeners and `.click()` are used in quite an intertwined fashion. I also noticed #918 is open. While I am working on this, do you mind if I also work on #918 ?

**Comment by Jaifroid** [comment]
@dheerajdlalwani If you find cases that are intertwined, feel free to include some elements of #918 in any PR fixing this issue. But I think you may find that some of the changes required in #918 are a bit more complicated.
