### ISSUE TITLE
Remove as much jQuery as possible from Bootstrap modal invocations

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-js#921]
Sub-issue of #367. Some, possibly most, use of jQuery to invoke and close Bootstrap modals can be substituted with native JS, but the underlying Bootstrap code depends on jQuery, so some methods will have to remain until #705 (which removes jQuery from Bootstrap).

**Comment by Abhishek-1337** [comment]
Hey,
I am new to open source and I am thinking of contributing to this issue. Should I go on with this one?

**Comment by Jaifroid** [comment]
@Abhishek-1337 If you're new to JS development, then you might find #918 to be easier. I've unassigned the person who was going to do that, as there's been no movement for 2-3 months.

**Comment by Abhishek-1337** [comment]
@Jaifroid   #918 looks fine to me. Working on it, Is there any info/advice that I should know about?

**Comment by aritroCoder** [comment]
Can I work in this issue?

**Comment by Jaifroid** [comment]
@aritroCoder Yes, that's fine. I'm assigning you.

**Comment by aritroCoder** [comment]
@Jaifroid have a look at the PR

**Comment by satyampsoni** [comment]
can i work on this?

**Comment by Jaifroid** [comment]
@satyampsoni There is already a PR in progress! Please choose another issue.
