### ISSUE TITLE
Adding `http-server` run script

### ISSUE THREAD

**Issue by ankur12-1610** [kiwix/kiwix-js#969]
Instead of running `http-server` command just add it to scripts, for eg:
![Screenshot from 2023-02-28 21-12-21](https://user-images.githubusercontent.com/76884959/221940991-461c2842-71f7-4ccd-a4a8-feb5f643708b.png)

or `npx http-server .`  will work as well.

**Comment by Jaifroid** [comment]
@ankur12-1610 This seems like a good idea, thanks! You'd also have to add http-server as a developer dependency.

**Comment by ankur12-1610** [comment]
On it!

**Comment by satyampsoni** [comment]
Hey @ankur12-1610. Have you completed it?
I would like to work on it too.
