### ISSUE TITLE
Recent wiktionary archives break the iframe and destroy the app's controls

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-js#972]
*EDIT by @Jaifroid: Discussion of issue should be in https://github.com/openzim/mwoffliner/issues/1803. This issue is to consider implementing a local patch.*

Kiwix-js no longer works with `wiktionary_en_all_maxi_2023-02.zim`. It was working fine with `wiktionary_en_all_maxi_2022-09.zim`. Now it just redirects to some other URL for the main page that doesn't have the search bar.

Editing the URL manually doesn't work around this. It goes to "404 Not Found nginx." when I replace `Wiktionary%3AOffline` with `wiki`. I also shows "404 Not Found" when I press the back button. My browser keeps on showing the page icon as the browser's loading animation for a long time before it switches to no icon at all. Pressing back at the original page goes back to the proper app with the search bar, but then it immediately redirects again. I need to close the tab and open another one to get something usable.

This affects ServiceWorker mode only. There is no redirect problem in JQuery mode and I am able to open articles. However, I do not like JQuery because it doesn't support my browser's CSS :visited, bfcache, nor Dark Reader extensions. This does not affect Android either.

I think the problem is that kiwix-js ServiceWorker mode is failing to intercept the redirect, while the other modes/apps were able to. Here is a video of the problem:

https://user-images.githubusercontent.com/25646384/222708434-9b531e0b-018b-48fe-a2c9-a0f4f543ac3a.mp4

**Comment by Jaifroid** [comment]
@danielzgtg Thank you for the error report. I'll investigate!

**Comment by Jaifroid** [comment]
Oops, I can't transfer the issue across orgs (from Kiwix to OpenZIM), so I'll just copy the issues.

**Comment by Jaifroid** [comment]
Closing in favour of https://github.com/openzim/mwoffliner/issues/1803

**Comment by danielzgtg** [comment]
Here is a Tampermonkey userscript to work around this:

```js
// ==UserScript==
// @name         Kiwix fix rogue redirect
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://moz-extension.kiwix.org/*
// ==/UserScript==

(function() {
    'use strict';
    const iframe = document.querySelector('iframe');
    iframe && (iframe.sandbox = "allow-same-origin allow-scripts");
})();
```

**Comment by Jaifroid** [comment]
Thanks for the suggestion. I did test, some time ago, adding a sandbox attribute: see #753 and in particular https://github.com/kiwix/kiwix-js/issues/404#issuecomment-861280543. However, we now have a different solution for external links, so it would be worth testing again.

**Comment by danielzgtg** [comment]
I think your different solution might work better.

The equivalent code outside of Tampermonkey and in the codebase would be to edit https://github.com/kiwix/kiwix-js/blob/6792f8133d13498eed449de1eec3a17fbb8c8b92/www/index.html#L689 and add a `sandbox="allow-same-origin allow-scripts"` attribute there. Here is a breakdown of the permissions:
- "": Disable everything, most importantly `allow-top-navigation`
- "allow-same-origin": Fix nginx 404
- "allow-same-origin allow-scripts": Try to fix collapsible sections as well. This doesn't work yet, so I will write a comment on the other issue.

This might not be the best solution, as I wrote only the code required to get my own zims working. I heard that in addition to Mediawiki dumps, Kiwix supports other things like TED talks. Depending on what those zims need, you may need to add more permissions from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#sandbox , possibly all of them except `allow-top-navigation.*` to get a much of the old behavior back as possible for those zims. In particular, they might need fullscreen, sound, or video things but I didn't check.

**Comment by Jaifroid** [comment]
Thanks for the information @danielzgtg. I've been experimenting with the sandbox attribute of the iframe (initially using Kiwix JS Windows), and it does seem to fix this issue for those browsers that support some of the directives of the feature. When loading the offending Wiktionary home page I get this in console log:

![image](https://user-images.githubusercontent.com/4304337/222967400-3d2edb93-ae14-4324-bd5f-6255f2f6295f.png)

Because the navigation is blocked, the page loads correctly. I need to test browser support more widely. I'm using this directive:

`sandbox="allow-same-origin allow-scripts allow-modals allow-forms allow-popups"`
