### ISSUE TITLE
Add a setting to block all network activity

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-js#98]
So that even the images (and any other remote resource) are not fetched from the Internet.
It's a feature of the Qt version, that is missing here.

In FxOS 2.1, there will be a way to disable mobile data per application : https://bugzilla.mozilla.org/show_bug.cgi?id=1035553
But it would not block network through Wifi, if available.

**Comment by Jaifroid** [comment]
Is this issue still valid? I guess it would be possible to trap any calls to non-local resources in the Service Worker code. I don't think it's possible in jQuery mode, though the CSP in app context and Cross-Origin blocking in browser context provides some protection for scripts / css / fonts.

**Comment by mossroy** [comment]
I think it's still valid.
It's a kind of paranoid mode, when you want to ensure no HTTP request is done on the network (because of an external image or link in a ZIM file).
It's low-priority as most platforms already have such feature (even if it blocks all the network activity of the browser or device).

Yes, it's certainly possible in ServiceWorker mode. I doubt it's possible to be 100% reliable in jQuery mode.

**Comment by Jaifroid** [comment]
We have gone as far as we can with this issue: we have good CSPs, but they can't be made more restrictive without making it impossible for the app to access content in the iframe. We block all external Fetch, except specifically authorized sites like browser-extension.kiwix.org. We can't prevent a malicious ZIM from removing the sandbox, however, without disabling scripts in ZIMs. See #976 and  #986.
